UK-Export-Finance/exip

e2e-tests/cypress/integration/journeys/before-you-start.spec.js, ui/server/controllers/before-you-start/index.js, ui/server/controllers/before-you-start/index.test.js, ui/server/controllers/buyer-based/index.js, ui/server/controllers/buyer-based/index.test.js, ui/server/controllers/company-based/index.js, ui/server/controllers/company-based/index.test.js, ui/server/controllers/final-destination/index.js, ui/server/controllers/final-destination/index.test.js, ui/server/controllers/tried-to-obtain-cover/index.js, ui/server/controllers/tried-to-obtain-cover/index.test.js, ui/server/controllers/uk-content-pecentage/index.js, ui/server/controllers/uk-content-pecentage/index.test.js, ui/server/helpers/sanitise-form-data.js, ui/server/helpers/sanitise-form-data.test.js, ui/server/helpers/update-submitted-data.js, ui/server/helpers/update-submitted-data.test.js, ui/server/routes/index.js, ui/server/routes/index.test.js, ui/templates/before-you-start.njk
- Create `sanitise-form-data` function
- Create `update-submitted-data` function
- Update session/submitted data on every form POST
- Before you start page using POST redirect instead of a link
- Before you start page creating a new empty session on submit
=> Save submitted data to session storage

e2e-tests/cypress/e2e/journeys/buyer-based/buyer-based-unsupported-country.spec.js, e2e-tests/cypress/e2e/journeys/buyer-based/user-testing-scenarios/buyer-based-submit-country-Angola.spec.js, e2e-tests/cypress/e2e/journeys/company-based/company-based-answer-no.spec.js, e2e-tests/cypress/e2e/journeys/tried-to-obtain-cover/tried-to-obtain-cover-answer-yes.spec.js, e2e-tests/cypress/e2e/journeys/uk-content-percentage/uk-content-percentage-answer-no.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/user-testing-scenarios/your-quote-buyer-country-Algeria.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/user-testing-scenarios/your-quote-buyer-country-Bahrain.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote.spec.js, ui/server/controllers/company-based/index.js, ui/server/controllers/company-based/index.test.js, ui/server/helpers/is-country-supported.js, ui/server/helpers/is-country-supported.test.js
- add mock unsupported country
- add e2e tests for mock scenarios used for user testing
- fix issue where 'company based' exit page would have incorrect back link
- add e2e test coverage for back links on all exit page scenarios
=> feat/EMS-193 - mock unsupported country, improve e2e test coverage

e2e-tests/cypress/e2e/journeys/change-your-answers/change-your-answers-policy-type-and-length.spec.js, e2e-tests/cypress/e2e/journeys/check-your-answers-multi-policy.spec.js, e2e-tests/cypress/e2e/journeys/check-your-answers-single-policy.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote-change-answers-multi-policy.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote-change-answers-single-policy.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote-large-contract-value.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote-multi-policy.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote-non-gbp-currency.spec.js, e2e-tests/cypress/e2e/journeys/your-quote/your-quote-single-policy.spec.js, src/ui/server/helpers/data-content-mappings/map-cost.test.ts, src/ui/server/helpers/data-content-mappings/map-cost.ts, src/ui/server/helpers/data-content-mappings/map-quote-to-content.test.ts, src/ui/server/helpers/data-content-mappings/map-quote-to-content.ts, src/ui/server/helpers/format-currency.test.ts, src/ui/server/helpers/format-currency.ts
Also includes adding `decimalPoints`param to `format-currency` for  `minimumFractionDigits` and `maximumFractionDigits.
=> feat(EMS-279): do not render decimal points in 'contract value' and 'max amount owed' summary list rows

e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js, src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-high-risk.test.ts, src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-standard-risk.test.ts, src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-very-high-risk.test.ts, src/ui/server/generate-quote/get-premium-rate/index.test.ts, src/ui/server/generate-quote/index.test.ts, src/ui/server/generate-quote/index.ts, src/ui/server/generate-quote/pricing-grid.json
- Update pricing grid.
- Update quote calculation logic to _not_ use policy length for a multi poicy.
- Update e2e tests to use new multi policy calculation results.
- Remove now outdated unit tests for multi policy calculations for over 3 months (maximum in the pricing grid is 3 months).
- Rename some variables/tidy some comments.
=> feat/EMS-302: update pricing grid. Do not use policy length in multi policy calculation

e2e-tests/content-strings/footer.js, e2e-tests/content-strings/links.js, src/ui/server/content-strings/footer.ts, src/ui/server/content-strings/links.ts, src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/server/controllers/quote/buyer-country/index.ts, src/ui/templates/partials/footer.njk
This PR fixes an issue where the buyer country controller would not pick up a submitted country name when JS is disabled.
Also fix a typo where the privacy link HREF had duplicate wording.
=> fix(EMS-379): fix issue with buyer country form when JS is disabled

src/ui/server/constants/api.ts, src/ui/server/constants/invalid-CIS-countries.ts, src/ui/server/helpers/mappings/map-countries.test.ts, src/ui/server/helpers/mappings/map-countries.ts
The CIS API returns some invalid countries. This PR filters out these specific invalid countries.
=> feat(EMS-380): filter out invalid country names from CIS API

src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts, src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
This PR fixes an issue where if the currencies API is down when we call it in the "Tell us about your policy" page, the server would crash. Now we redirect to problem-with-service page.
=> fix(EMS-465): Redirect to problem with service page if no currencies are returned from API

src/ui/server/controllers/quote/policy-type/index.test.ts, src/ui/server/controllers/quote/policy-type/index.ts, src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
This passes "links" content strings to the policy type pgae, so that the "skip to main content" nunjuck partial, has a "skip" link and text.
=> fix(EMS-458): Fix issue where Policy type page would not render skip content link/text

e2e-tests/content-strings/index.js, e2e-tests/content-strings/pages/quote.js, e2e-tests/content-strings/uk-goods-and-services-description.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/cypress/e2e/pages/shared/ukGoodsOrServices.js, e2e-tests/cypress/e2e/partials/index.js, e2e-tests/cypress/e2e/partials/ukGoodsAndServicesDescription.js, e2e-tests/cypress/support/check-uk-goods-and-services-description.js, src/ui/server/content-strings/index.ts, src/ui/server/content-strings/pages/quote.ts, src/ui/server/content-strings/uk-goods-and-services-description.ts, src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.test.ts, src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.ts, src/ui/server/controllers/quote/uk-goods-or-services/index.test.ts, src/ui/server/controllers/quote/uk-goods-or-services/index.ts, src/ui/templates/insurance/eligibility/uk-goods-or-services.njk, src/ui/templates/partials/uk-goods-and-services-description.njk, src/ui/templates/quote/uk-goods-or-services.njk
This PR adds an expandable details section of "What counts as UK Goods and services", to the "UK goods and services" page of the Insurance Eligibility section.
- Extract the existing "What counts as UK Goods and services" part of the UK page in the Quote flow into it's own component/partial.
- Consume this component in both UK goods and services pages in the Quote flow and Insurance Eligibility flow, but with the Quote version rendering and additional line of text.
- Extract relevant content strings and e2e assertions into their own files, to be consumed in multiple places.
=> feat(EMS-457): UK goods or services - expandable description

e2e-tests/constants/field-ids.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields.js, e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js, e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js, e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js, e2e-tests/cypress/e2e/pages/quote/buyerCountry.js, src/ui/server/constants/field-ids.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields.ts, src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/server/controllers/quote/buyer-country/index.ts, src/ui/server/controllers/quote/buyer-country/validation.test.ts, src/ui/server/controllers/quote/buyer-country/validation.ts, src/ui/server/helpers/single-input-page-variables.test.ts, src/ui/templates/quote/buyer-country.njk
This PR fixes an issue where buyer country would not update in a 'change answer' scenario if JS is disabled.
- Remove `COUNTRY` field id, use `BUYER_COUNTRY` instead.
- Simplify buyer country controller and validation logic for getting the submitted country when JS is enabled or disabled.
- Remove client side JS `onConfirm` function for when a country is selected via autocomplete component.
=> fix(EMS-379): fix issue where buyer country would not update when JS is disabled

e2e-tests/constants/field-ids.js, e2e-tests/constants/routes/insurance.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-apply-page.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/check-if-eligible.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount-answer-yes.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/speak-to-ukef-efm.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js, e2e-tests/cypress/e2e/pages/insurance/eligibility/index.js, e2e-tests/cypress/e2e/pages/insurance/eligibility/speakToUkefEfm.js, src/ui/server/constants/field-ids.ts, src/ui/server/constants/routes/insurance.ts, src/ui/server/constants/templates/insurance/eligibility/index.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/server/controllers/insurance/eligibility/insured-period/index.test.ts, src/ui/server/controllers/insurance/eligibility/insured-period/index.ts, src/ui/server/controllers/insurance/eligibility/speak-to-ukef-efm/index.test.ts, src/ui/server/controllers/insurance/eligibility/speak-to-ukef-efm/index.ts, src/ui/server/routes/insurance/eligibility/index.test.ts, src/ui/server/routes/insurance/eligibility/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/shared-validation/yes-no-radios-form/index.test.ts, src/ui/templates/insurance/eligibility/insured-period.njk, src/ui/templates/insurance/eligibility/speak-to-ukef-efm.njk
This PR adds the “Insured period” page/form to the Insurance Eligibility flow.
- Create “Insured period” page.
- Create “Speak to a UKEF EFM” exit page.
- Redirect to new exit page if Insured Period answer is submitted as “Yes” (if Exporter wants cover for over the maximum period available online).
- Rename `WANT_COVER_FOR_MORE_THAN_MAX_PERIOD` to `WANT_COVER_OVER_MAX_AMOUNT`
- Rename `WANT_INSURANCE_OVER_MAX_PERIOD` constant to `INSURED_PERIOD`
- Rename exit page reason `WANT_COVER_OVER_MAX_PERIOD` to `WANT_COVER_OVER_MAX_AMOUNT`
- Improve some E2E test descriptions.
- Remove some commented out lighthouse checks in E2E tests
=> feat(EMS-485): Insurance eligibility - Insured period page, speak to EFM exit page

e2e-tests/constants/field-ids.js, e2e-tests/constants/routes/insurance.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount-answer-yes.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties-answer-yes.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties.spec.js, e2e-tests/cypress/e2e/pages/insurance/eligibility/index.js, e2e-tests/cypress/e2e/pages/insurance/eligibility/otherParties.js, src/ui/server/constants/field-ids.ts, src/ui/server/constants/routes/insurance.ts, src/ui/server/constants/templates/insurance/eligibility/index.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/server/controllers/insurance/eligibility/other-parties/index.test.ts, src/ui/server/controllers/insurance/eligibility/other-parties/index.ts, src/ui/server/routes/insurance/eligibility/index.test.ts, src/ui/server/routes/insurance/eligibility/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/templates/insurance/eligibility/other-parties.njk
This PR adds a new page to the Insurance eligibility flow for "other parties
- Add new route, controller and validation for "other parties" page.
- Redirect to "apply offline" exit page if the answer to "are other parties involved" is yes.
- EMS-460: Add "what counts as another party" expandable details to the "other parties" page.
=> feat(EMS-365): Insurance eligibility - other parties

e2e-tests/constants/field-ids.js, e2e-tests/constants/routes/insurance.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period-answer-yes.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js, e2e-tests/cypress/support/analytics/check-analytics-cookie-properties.js, src/ui/README.md, src/ui/server/constants/field-ids.ts, src/ui/server/constants/routes/insurance.ts, src/ui/server/constants/templates/insurance/eligibility/index.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/server/controllers/insurance/eligibility/pre-credit-period/index.test.ts, src/ui/server/controllers/insurance/eligibility/pre-credit-period/index.ts, src/ui/server/routes/insurance/eligibility/index.test.ts, src/ui/server/routes/insurance/eligibility/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/templates/insurance/eligibility/pre-credit-period.njk
This PR adds a new page to the Insurance eligibility flow for "pre-credit period"
- Add new route, controller and validation for "pre-credit period" page.
- Redirect to "apply offline" exit page if the answer to "need cover for pre-credit period" is yes.
=> feat(EMS-367): Insurance eligibility - pre-credit period

e2e-tests/constants/field-ids.js, e2e-tests/constants/routes/insurance.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number-answer-no.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js, src/ui/server/constants/field-ids.ts, src/ui/server/constants/routes/insurance.ts, src/ui/server/constants/templates/insurance/eligibility/index.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/server/controllers/insurance/eligibility/companies-house-number/index.test.ts, src/ui/server/controllers/insurance/eligibility/companies-house-number/index.ts, src/ui/server/routes/insurance/eligibility/index.test.ts, src/ui/server/routes/insurance/eligibility/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/templates/insurance/eligibility/companies-house-number.njk
This PR adds a new page to the Insurance eligibility flow for "do you have a companies house number"
- Add new route and controller for "companies house number" page.
- Redirect to "apply offline" exit page if the answer to "do you have a companies house number" is no.
=> feat(EMS-367): Insurance eligibility - companies house number

CHANGELOG.md, e2e-tests/constants/field-ids.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country-unsupported-country.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country.spec.js, e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js, e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js, e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js, e2e-tests/cypress/e2e/pages/shared/buyerCountry.js, e2e-tests/cypress/support/check-buyer-country-form.js, package-lock.json, package.json, src/ui/server/constants/field-ids.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields.ts, src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts, src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts, src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/server/controllers/quote/buyer-country/index.ts, src/ui/server/helpers/page-variables/single-input/index.test.ts, src/ui/server/middleware/headers/security.ts, src/ui/server/shared-validation/buyer-country/index.test.ts, src/ui/server/shared-validation/buyer-country/index.ts, src/ui/templates/shared-pages/buyer-country.njk
This PR fixes merges the `main` branch into `main-application`, thereby fixing an issue where Buyer Country would not change when going through a "change" journey in the Quote tool when JS is disabled.
Also:
- Updated the buyer country controller in Insurance eligibility so that a previously submitted country will now be pre-populated.
- Update E2E tests to use the new buyer country helpers/assertion functions used.
=> fix(EMS-523): Buyer country change not updating and not rendering in Insurance eligibility when previously submitted

e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields.js, e2e-tests/content-strings/pages/index.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/cypress/e2e/pages/shared/index.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields.ts, src/ui/server/content-strings/pages/index.ts, src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/templates/components/yes-no-radio-buttons.njk, src/ui/templates/insurance/eligibility/pre-credit-period.njk, src/ui/templates/insurance/eligibility/uk-goods-or-services.njk
This PR fixes or adds various copy/field hints in insurance eligibility and shared pages in quote and insurance eligibility.
- Fix/add hint to “pre credit” period form used in insurance eligibility.
- Fix/update both instances of “exporter location” page/field to use the same, new title.
- Fix/update error message used in “minimum UK goods or services” form.
- Fix/add hint to “minimum UK goods or services” form in insurance eligibility.
- Remove now unused test in quote - buyer country controller after merging `main` into `main-application`
=> fix(EMS-531, 536, 551, 524): various copy issues

e2e-tests/cypress/e2e/journeys/switch-between-services/via-buyer-country-routes/complete-insurance-eligibility-then-get-a-quote.spec.js, e2e-tests/cypress/e2e/journeys/switch-between-services/via-buyer-country-routes/get-a-quote-then-complete-insurance-eligibility.spec.js, e2e-tests/cypress/e2e/journeys/switch-between-services/via-start-now-routes/complete-insurance-eligibility-then-get-a-quote.spec.js, e2e-tests/cypress/e2e/journeys/switch-between-services/via-start-now-routes/get-a-quote-then-complete-insurance-eligibility.spec.js, e2e-tests/cypress/support/insurance/eligibility/forms.js, src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts, src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts, src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/server/controllers/quote/buyer-country/index.ts, src/ui/server/controllers/root/index.test.ts, src/ui/server/controllers/root/index.ts
This PR fixes an issue where the server could crash when visiting the buyer country pages in the quote tool and insurance eligibility.
- Refresh `req.session.submittedData` in the buyer country controllers when the required object does not exist.
Added tests for the following scenarios, in a single session:
- Get a quote, complete insurance eligibility, then go back to the quote tool. 
- Complete insurance eligibility, get a quote, then go back to insurance eligibility.
Also have tests for the same as above, but by visiting the buyer country page directly, instead of going via a 'start now' page or root URL. Each milestone (get a quote, complete insurance eligibility, go back to ...), starts by visiting the appropriate buyer country page/route directly.
=> fix(EMS-616): Refresh req.session.submittedData in buyer country controllers

package-lock.json
* `jpeg-js` has a high vulnerability as being raised by `npm audit`.
* `npm audit fix`, updated package version to `0.4.4`.
* No fix is currently available for moderator vulnerability master package `got <11.8.5`.
=> chore: High vulnerability - `jpeg-js` updated from `0.4.3` to `0.4.4`

e2e-tests/cypress/e2e/journeys/insurance/eligibility/need-to-start-again.spec.js, src/ui/server/controllers/insurance/eligibility/need-to-start-again/index.test.ts, src/ui/server/controllers/insurance/eligibility/need-to-start-again/index.ts
* In the insurance section, need to start again link would take you to insurance start page
* This would wipe all the data stored on filled application
* Changed route to countries page on link
* Updated unit and e2e tests
=> fix(EMS-623): Insurance need to start route

.gitignore, package-lock.json, package.json
* `cypress-audit` dependency has introduced transitive dependency of `CVE-2022-33987` for package `got`.
* Removed `cypress-audit`
* Added `api/src/.keystone` to `.gitignore`.
=> chore: Dependency vulnerability removal

e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-submit.spec.js, e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js, src/ui/server/controllers/insurance/business/company-details/helpers/companies-house-search.helper.test.ts, src/ui/server/controllers/insurance/business/company-details/helpers/companies-house-search.helper.ts, src/ui/server/controllers/insurance/business/company-details/index.POST.test.ts, src/ui/server/controllers/insurance/business/company-details/index.test.ts, src/ui/server/controllers/insurance/business/company-details/index.ts, src/ui/server/controllers/insurance/business/company-details/validation/companies-house/index.ts, src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.test.ts, src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.ts, src/ui/templates/insurance/your-business/company-details.njk
* Changed companies detail template to be single form
* Added routes to search and submit button for different endpoints (companies house search or company details page post)
* Added companies house search helper which makes api call and returns validation errors/company
* Added tests
* Added to e2e tests
=> feat(EMS-746): Company details page submit validation

e2e-tests/content-strings/error-messages.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-policy-currency-code.spec.js, e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/policy-currency-code.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/policy-currency-code.ts, src/ui/server/graphql/queries/application.ts, src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
This PR adds "contract currency code" field validation to the Single contract policy page and ensures that a previously submitted value is displayed in the form. 
- Add validation rule to check that the field is not empty.
- Add policy currency code to the graphQL mutation.
- Add tests.
- Update "save and go back" unit test to ensure the functionality works when the form has every valid field provided.
=> feat(EMS-510): Policy and exports - Single contract policy - policy currency code validation

README.md, src/ui/server/controllers/insurance/policy-and-export/save-data/index.ts
- Add links to the tech stack list
- Add a section briefly explaining what keystone does, including:
- What keystone generates when we add something to the keystone schema
- What keystone hooks are
- How we customise the generated graphql schema
- Why we use keystone
- How and when the UI calls the API
- Remove the deployment section as this has changed and is currently undergoing discussions of what we should/shouldn't put in the README.
Also, improved the documentation/description for the policy and export's "save data" function.
Quick link of the updated README in generated format: https://github.com/UK-Export-Finance/exip/blob/f393d29dae0c5885591d400c263e753a8c5d70d7/README.md
=> chore(EMS-786): update README

database/exip.sql, e2e-tests/content-strings/error-messages.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-sales-to-buyer.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js, e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js, src/api/.keystone/config.js, src/api/schema.graphql, src/api/schema.prisma, src/api/schema.ts, src/ui/package-lock.json, src/ui/server/content-strings/error-messages.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/index.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-sales-to-buyer.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-sales-to-buyer.ts, src/ui/server/graphql/queries/application.ts
This PR adds "total sales to buyer" field validation and data saving to the Multiple contract policy page.
- Add `totalSalesToBuyer` to the schema and DB dump.
- Add validation handling for if the field is submitted without a value or has an incorrect value.
- Also fixed some naming typos.
=> feat(EMS-573): Policy and exports - Multiple contract policy - total sales field

database/exip.sql, e2e-tests/constants/application.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-maximum-buyer-will-owe.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js, e2e-tests/cypress/e2e/pages/insurance/policy-and-export/multipleContractPolicy.js, e2e-tests/cypress/fixtures/application.js, e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js, e2e-tests/cypress/support/insurance/complete-and-submit-single-contract-policy-form.js, src/api/.keystone/config.js, src/api/schema.graphql, src/api/schema.prisma, src/api/schema.ts, src/ui/server/constants/application.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/index.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/maximum-buyer-will-owe.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/maximum-buyer-will-owe.ts, src/ui/server/graphql/queries/application.ts, src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk, src/ui/types/application.ts
This PR adds "estimated max amount owed" field validation and data saving to the Multiple contract policy page.
- Add `maximumBuyerWillOwe` to the schema and DB dump.
- Add validation handling for if the field is submitted without a value or has an incorrect value.
- Fix a typo in an E2E test.
- Create `/fixtures/application` in E2E tests. This can be used moving forwards for storing application values that we type and assert in E2E tests.
- Update single and multiple contract policy tests to consume the fixtures.
=> feat(EMS-574): Policy and exports - Multiple contract policy - estimated max amount owed field

e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-credit-period-with-buyer.spec.js, e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/index.ts, src/ui/server/shared-validation/credit-period-with-buyer/index.test.ts, src/ui/server/shared-validation/credit-period-with-buyer/index.ts
This PR adds the "credit period" field to the multiple contract policy page.
- Move the credit period validation function used in "single contract policy" into the shared validation directory.
- Consume the credit period validation in "multiple contract policy" validation.
- Add/update tests.
=> feat(EMS-575): Policy and exports - Multiple contract policy - credit period field

src/ui/server/api/keystone/application/index.ts, src/ui/server/api/keystone/countries/index.ts, src/ui/server/api/keystone/index.ts, src/ui/server/graphql/queries/countries-by-iso-code.ts, src/ui/server/graphql/queries/countries.ts
This PR adds a countries graphql query - required for at least 2 pages. So now we have:
- `countries.getAll()`
- `countries.get(isoCode)`
Also fixed a typo in the "get country by iSO code" query.
=> feat(EMS-609): add countries graphql query

README.md, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js, src/ui/server/controllers/insurance/policy-and-export/map-and-save/index-api-errors.test.ts, src/ui/server/controllers/insurance/policy-and-export/map-and-save/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/map-and-save/index.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/save-and-back/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/index.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/index.ts
This PR adds "save and go back" functionality to the "multiple contract policy" page.
- Add "save and go back" route and POST controller.
- Add E2E test.
- Add documentation RE submit button requirements, update "what happens when a form is submitted" section. Here is the markdown generated section: https://github.com/UK-Export-Finance/exip/blob/e0b3c3552c0a1f9926b38ad6ffcc0a3385a97d9c/README.md#requirements-for-submitting-a-form
- Create a `mapAndSave.policyAndExport` function. This can be used in all POST methods for any page in the policy and export section. This function:
- Maps any form data (if required). E.g, transform day/month/year fields into a timestamp.
- Calls `save.policyAndExport` with the mapped data and any passed validation errors.  This save function then sanitises the …
=> feat(EMS-570): Policy and export - multiple contract policy - save and go back. Improve save data approach

database/exip.sql, e2e-tests/constants/field-ids/insurance/exporter-business/index.js, src/api/.keystone/config.js, src/api/custom-schema.ts, src/api/keystone.test.ts, src/api/schema.graphql, src/api/schema.prisma, src/api/schema.ts, src/api/types.ts, src/ui/server/api/keystone/application/index.ts, src/ui/server/constants/field-ids/insurance/exporter-business/index.ts, src/ui/server/graphql/mutations/update-application/exporter-company.ts, src/ui/server/graphql/queries/application.ts, src/ui/types/application.ts
This PR adds the ability to get and save exporter company details, for the "Company details" page.
- Add `exporterCompany` and `exporterCompanyAddress` to the keystone schema/DB/API. These are available to be queried from the top level of the application.
- Add placeholder `ExporterCompanySicCode` and `ExporterBusiness` to the schema, ready for further development.
- Create a new custom resolver in keystone schema to update an exporter company _and_ address.
- The requirement we have is to update an exporter's company for an application, as well as the company address. We want to keep these pieces of data seperate to have a clean database structure.
- For various reason, it is troublesome/not possible or results in poor code quality, to update 2 tables at the same time with one query. …
=> feat(EMS-808): API/DB structure for exporter company

src/ui/server/controllers/insurance/policy-and-export/call-map-and-save/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/call-map-and-save/index.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/save-and-back/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.ts
This PR adds a new function to the policy and export controllers directory - `callMapAndSave`. This is to reduce repeated logic in the "save and back" controllers.
- Extract repeated logic and unit tests from "save and back" controllers and move into a single function.
- In the "type of policy" validation, return an empty object instead of null. This was causing issues with the improved codebase changes. Add a `objectHasValues` check to the controller so it works as before.
=> feat(EMS-607): Policy and exports - callMapAndSave function

e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js, src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/save-and-back/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/index.ts
This PR adds "save and go back" functionality to the "about goods or services" page.
- Add save and go back route and controller
- Add E2E test coverage
=> feat(EMS-607): Policy and exports - about goods or services - save and go back

e2e-tests/content-strings/fields/insurance/exporter-business/index.js, src/ui/server/content-strings/pages/insurance/your-business/exporter-business/index.ts, src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts, src/ui/server/helpers/summary-lists/company-house-summary-list.ts
* Companies house summary list had incorrect heading
* Companies house summary list date was in the wrong format
* Changed title of summary list
* Changed date to be one digit for day if between 1-9
=> fix(EMS-795):  Company Details - Companies house search heading and date

e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-credit-period-with-buyer.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-credit-period-with-buyer.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts, src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk, src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
This PR fixes two issues in the single/multiple policy type page where:
- After submitting the form and revisiting the page, the "credit period with buyer" field would render an incorrect value.
- When submitting the form with a currency selection, but there are other validation errors, previously selected currency would not be auto selected.
- Add currency mapping to the single and multiple POST controllers.
- Fix a typo in the templates for single and multiple "credit period with buyer" field.
=> fix(EMS-792-810): Policy end exports - pre-population issues

e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js, src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts, src/ui/server/controllers/insurance/business/company-details/index.test.ts, src/ui/server/controllers/insurance/business/company-details/index.ts, src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/index.ts, src/ui/server/helpers/get-valid-fields/index.test.ts, src/ui/server/helpers/get-valid-fields/index.ts, src/ui/server/helpers/has-form-data/index.test.ts, src/ui/server/helpers/has-form-data/index.ts, src/ui/server/helpers/sanitise-data/index.test.ts, src/ui/server/helpers/sanitise-data/index.ts, src/ui/server/helpers/string/index.test.ts, src/ui/server/helpers/string/index.ts
This PR changes the "sanitise form data" functions and therefore fixing an issue where a text input would not be sent to the API/saved in the database, if the value has been removed after being submitted with a value. We previously stripped out empty form fields before sending to the API. Also includes some technical improvements.
- Update `sanitiseData` function so that it does not return a field that is in a set of specific number fields and has an empty value. Without this, trying to send number fields with an empty string or value of 0, results in API/DB error and the data is not saved. 
- Created `NUMBER_FIELDS` array of specific number fields that are in the applicatino forms.
- Created `shouldIncludeAndSanitiseField` check.
- Improved `shouldChangeToNumber` checks so that all …
=> fix(EMS-793): Policy and exports - fix string fields/inputs not saving as empty with save & back functionality

src/ui/server/helpers/mappings/map-countries.test.ts, src/ui/server/helpers/mappings/map-countries.ts
Update `mapCountries` funciton to order the countries alphabetically.
This mapping function is consumed only in the full application i.e not in eligibility - eligibility uses countries from the CSI API and has a  a different mapping function (due to different data structure).
=> fix(EMS-852): Order countries alphabetically

e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js, src/ui/server/helpers/sanitise-data/index.test.ts, src/ui/server/helpers/sanitise-data/index.ts
This PR adds a an explicit list of string number fields, `STRING_NUMBER_FIELDS` - string fields that could be numbers.
When sanitising form data before sending to the API, we have a check - `shouldChangeToNumber`. This is great - ensuring that a pure number in a string, is converted to an actual number type.
However, there are scenarios where a user could enter a pure number, e.g "1234" into a free text field. The default sanitise data behaviour is to transform this into a number type, but we do not want this to happen on specific fields.
Without introducing an explicit "string number fields that we don't want to transform if they have pure numbers", the data save will fail and the user will be taken to a "problem with service" page. 
An alternative approach is to add additional …
=> fix(EMS-851): Explicit list of string number fields to allow submission/saving if submitted as a pure number

e2e-tests/content-strings/error-messages.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js, e2e-tests/cypress/support/insurance/requested-start-date-field.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/insurance/your-buyer/index.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.ts, src/ui/server/shared-validation/requested-start-date/index.test.ts, src/ui/server/shared-validation/requested-start-date/index.ts, src/ui/templates/insurance/your-buyer/company-or-organisation.njk
This PR adds "is valid"  checks to the "cover start" and "contract completion" date fields in the policy and exports section. We now present an error to the user if they e.g enter an incorrect month of e.g "24", or in US style. Also fixed a small typo bug in the your buyer page.
- Use `isValid` date-fns function to check the date for invalid formatting in both date validation functions.
- Rename `IS_EMPTY` error message to `INCORRECT_FORMAT`.
- Add E2E tests for all instances (single and multiple pages).
- Align requested start date and contract completion date validation patterns (returning errors in each condition instead of assigning variable and simplify the default return param).
- EMS-877: Fix some typos for maximum characters allowed in the "address" field of Your buyer.
=> fix(EMS-867-EMS-877): Policy and exports - add invalid date format validation, fix typos in Your buyer address field

e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js, e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js, src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts, src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
This PR updates the hint for "total contract value" in the single contract policy page. Also fixes some incorrect external links.
=> fix(EMS-834-911): Policy and exports - update total contract value hint, update external links

e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js, src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.test.ts, src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.test.ts, src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
The policy and exports summary list was rendering a default date (with year 1970) for the "contract completion date" field if a date is not passed.
- Add a condition to the summary list row value param.
- Improve test coverage for summary list row value conditions.
- Add E2E test to ensure we don't regress in the future.
=> fix(EMS-913): Policy and exports - fix date issue when changing contract from multiple to single

e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js, src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
Update the link used in 3 policy and export fields so the link goes directly to an external form instead of a page that links to the PDF.
=> fix(EMS-911): policy and exports - update links to external proposal form

e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/insurance/account/index.js, e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation-password.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js, e2e-tests/cypress/e2e/pages/insurance/account/create/yourDetails.js, e2e-tests/cypress/fixtures/account.js, src/ui/package-lock.json, src/ui/package.json, src/ui/server/constants/account.ts, src/ui/server/constants/index.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/insurance/account/index.ts, src/ui/server/content-strings/fields/insurance/index.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/rules/email.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/rules/index.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/rules/password.test.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/rules/password.ts, src/ui/server/shared-validation/password/index.test.ts, src/ui/server/shared-validation/password/index.ts, src/ui/templates/insurance/account/create/your-details.njk
This PR adds password validation to the "your details" page of account creation.
- Add `joi-password` package to easily read and maintain password rules; and validate without introducing regex.
- Create a shared, reusable validation function for checking a password with Joi and `joi-password`.
- Add password hints as per design.
- E2E test coverage.
- Also fixed a typo where "email" validation rule mentioned "first name".
=> feat(EMS-781): Account creation - password validation 

e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js, e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js, e2e-tests/cypress/support/insurance/check-policy-currency-code-input.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
This PR fixes 2 issues in the Policy and exports - single contract policy page.
- Incorrect link to external form in the "maximum buyer will owe" field hint.
- Incorrect/outdated error message for the "total contract value" field.
- Also updated the E2E tests for single/contract policy hint links to external form so that they assert from link content strings instead of field content strings.
=> fix(EMS-911-919): Policy and exports - fix field hint link and error message

e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-refresh-page.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-renders-submitted-email.spec.js, src/ui/templates/insurance/account/create/confirm-email.njk
This PR adds a condition to the "confirm email" page to conditionally render the "we sent a link to ..." text. The email that is rendered in this page/sentence is only available for one request - it's (rightly) deleted in GET request.
- Conditionally render the text on the page.
- Add test coverage for scenarios where the text would not appear:
- When a user refreshes the page.
- When a user submits the cookie consent banner form.
=> fix(EMS-958): Account creation - conditionally render 'we sent a link to...' text

e2e-tests/content-strings/fields/insurance/account/index.js, e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js, e2e-tests/cypress/support/commands.js, e2e-tests/cypress/support/insurance/account/assert-password-reveal-button.js, src/ui/server/content-strings/fields/insurance/account/index.ts
This PR ensures that password reveal functionality is working for the Account sign in page.
- Create a cypress command for checking password reveal functionality. This is now a feature used in 2 places and there will be more in the future.
- Call this new command in the "create account" and "sign in" E2E page tests.
=> feat(EMS-871): Account sign in - password reveal

e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js, src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.ts, src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.test.ts, src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts, src/ui/server/helpers/whole-number-validation/index.test.ts, src/ui/server/helpers/whole-number-validation/index.ts
* `estimatedTurnover` did not allow values below 0
* Added optional `allowNegativeValue` variable to `wholeNumberValidation`.  If set to true, then will allow numbers below 0
* Updated validation for estimate-annual-turnover to set flag to true
=> fix(EMS-990): Company Details - Turnover - Allow negative turnover

e2e-tests/constants/field-ids/insurance/account/index.js, e2e-tests/constants/routes/insurance/account.js, e2e-tests/content-strings/fields/insurance/account/index.js, e2e-tests/content-strings/pages/insurance/account/index.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code.spec.js, e2e-tests/cypress/e2e/pages/insurance/account/sign-in/enterCode.js, e2e-tests/cypress/e2e/pages/insurance/account/sign-in/index.js, e2e-tests/cypress/e2e/pages/insurance/account/sign-in/signIn.js, e2e-tests/cypress/e2e/partials/insurance/accountFormFields.js, src/ui/server/constants/field-ids/insurance/account/index.ts, src/ui/server/constants/routes/insurance/account.ts, src/ui/server/constants/routes/insurance/index.ts, src/ui/server/constants/templates/insurance/account/index.ts, src/ui/server/content-strings/fields/insurance/account/index.ts, src/ui/server/content-strings/pages/insurance/account/index.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/routes/insurance/account/index.test.ts, src/ui/server/routes/insurance/account/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/templates/insurance/account/sign-in/enter-code.njk
This PR sets up the "security code" page/form for the Account sign in flow.
Note: there is no form validation or actual security code functionality, this PR just sets up the GET route and renders the form.
- Setup route, controller and nunjucks template.
- Add temporary POST route that redirects to dashboard route (this will be updated in a future PR for validation API response handling).
=> feat(EMS-870): account sign in - security code page setup

e2e-tests/content-strings/error-messages.js, e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.test.ts, src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.ts, src/ui/server/helpers/percentage-number-validation/index.test.ts, src/ui/server/helpers/percentage-number-validation/index.ts, src/ui/types/errors.ts, src/ui/types/index.d.ts
* percentageTurnover field allowed commas as valid input
* Added new helper to handle all validation for percentage numbers
* Removed commas being valid for percentages
* Added tests
=> fix(EMS-991): Your business - Turnover - Percentage Turnover allowed commas

e2e-tests/content-strings/error-messages.js, e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation-account-already-exists.spec.js, src/api/.keystone/config.js, src/api/custom-resolvers/account-sign-in.test.ts, src/api/custom-resolvers/create-account.test.ts, src/api/custom-resolvers/create-account.ts, src/api/custom-schema.ts, src/api/schema.graphql, src/ui/server/content-strings/error-messages.ts, src/ui/server/controllers/insurance/account/create/your-details/index.test.ts, src/ui/server/controllers/insurance/account/create/your-details/index.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/index.test.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/index.ts, src/ui/server/graphql/mutations/account/create.ts
This PR updates account creation to ensure that an account can only be created if the email is unique and has not been used before.
- Update `createAccount` resolver to reject if an account has already been created with the provided email address.
- Render a new validation error in the UI if an account already exists.
- Improve/add test coverage for the `createAccount` resolver.
=> feat(EMS-1013): Account creation - only create an account if the email is unique

src/ui/server/middleware/insurance/application-access/index.test.ts, src/ui/server/middleware/insurance/application-access/index.ts
Currently in dev if an application does not have an exporter ID, the application access middleware fails because it cannot read the ID and then the server crashes.
The middleware might be running somewhere were it doesn't need to - need to look into this (not a quick thing). In the meantime, need this changes merged so we can unblock QA / dev environment.
- Add an additional check to make sure exporter object exists.
=> fix(EMS-1263): application access - add a check for exporter ID

e2e-tests/constants/field-values.js, e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-multiple-applications.spec.js, e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js, e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js, e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js, e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js, e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js, e2e-tests/cypress/support/commands.js, e2e-tests/cypress/support/insurance/assert-all-sections-url.js, e2e-tests/cypress/support/insurance/your-buyer/complete-and-submit-company-or-organisation-form.js, src/ui/server/constants/field-values.ts, src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.test.ts, src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.ts
This PR updates the "code of conduct" declaration to redirect to the appropriate place depending on yes or no answer. Also improves E2E test coverage for answering yes/no in all declaration forms via "save and back" button.
- Update code of conduct controller to redirect to a different page depending on the answer.
- Add yes/no field values constants.
- Add and improve E2E test coverage.
- Create new cypress command: `assertAllSectionsUrl`
- Add `cy.wait()` to company/organisation form submission function used throughout the E2E tests. As we are adding more E2E tests, we are pinging the companies house API very frequently. Without introducing a delay, the API call starts to fail when running the entire E2E suite.
=> feat(EMS-1183): Declarations - Code of conduct - yes/no redirections

src/api/Dockerfile, src/ui/Dockerfile
Azure Web App containers are not compatible to run Node >= 19 base docker image.
* Downgraded to base image containing node `18.15`.
=> fix(docker): downgraded docker image to Node 18.15

src/ui/server/controllers/root/contact-us/index.test.ts, src/ui/server/controllers/root/contact-us/index.ts, src/ui/server/test-mocks/mock-buyer.ts
* Contact us page does not show account header links
* Added authenticated header code to contact-us controller
* Added unit test
* Added more realistic address to mock-buyer test mock
=> fix(EMS-1186): Contact us page - Authenticated header

src/api/.keystone/config.js, src/api/emails/send-application-submitted-emails/index.test.ts, src/api/helpers/get-application-submitted-email-template-ids/index.test.ts, src/api/helpers/get-application-submitted-email-template-ids/index.ts, src/api/test-mocks/mock-buyer.ts
This PR fixes an issue where an incorrect flag was being used in a condition to trigger a particular email template from being sent as part of application submission.
- Rename usage of `buyer.exporterIsConnectedWithBuyer` with `buyer.exporterHasTradedWithBuyer` in the `getApplicationSubmittedEmailTemplateIds` function.
- Update `exporterHasTradedWithBuyer` mock data/answer to reflect what is actually stored in the DB.
=> fix(EMS-1254): Application submission - fix incorrect flag used for sending emails

e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/need-to-start-new-application/need-to-start-new-application-page.spec.js, e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/need-to-start-new-application/need-to-start-new-application-start-new-application.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted.spec.js, e2e-tests/cypress/support/insurance/eligibility/submit-answers-happy-path.js, src/ui/server/controllers/insurance/check-your-answers/start-new-application/index.test.ts, src/ui/server/controllers/insurance/check-your-answers/start-new-application/index.ts, src/ui/server/controllers/insurance/no-access-application-submitted/index.test.ts, src/ui/server/controllers/insurance/no-access-application-submitted/index.ts
* start new application button in check your answers section redirected to insurance start
* no access to application application submitted page did not have authenticated header
* Added authenticated header to no access application submitted page
* Added correct redirect to buyerCountry for start new application
=> fix(EMS-1522-1555): Application submitted page authenticated header and start new application redirect

generate-exip-pricing-grid/package-lock.json, generate-exip-pricing-grid/package.json
All versions of SheetJS CE through 0.19.2 are vulnerable to "Prototype Pollution" when reading specially crafted files. Workflows that do not read arbitrary files (for example, exporting data to spreadsheet files) are unaffected.
Security alert: https://github.com/UK-Export-Finance/exip/security/dependabot/18
* Updated to `node-xlsx` to `0.4.0`
=> fix(CVE-2023-30533): updated node-xlsx to 0.4.0

e2e-tests/cypress/e2e/journeys/insurance/account/manage/account-manage.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-and-sign-in.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code-without-completing-eligibility.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/request-new-code/account-sign-in-request-new-code.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation-unverified-account.spec.js, e2e-tests/cypress/support/insurance/account/complete-and-submit-sign-in-account-form.js, e2e-tests/cypress/support/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js, e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-dashboard.js, e2e-tests/cypress/support/insurance/account/sign-in-and-go-to-url.js, src/api/.keystone/config.js, src/api/custom-resolvers/mutations/account-sign-in.test.ts, src/api/custom-resolvers/mutations/account-sign-in.ts, src/api/custom-resolvers/mutations/send-email-confirm-email-address.test.ts, src/api/custom-resolvers/mutations/send-email-confirm-email-address.ts, src/api/custom-schema/type-defs.ts, src/api/emails/index.test.ts, src/api/emails/index.ts, src/api/helpers/send-email-confirm-email-address/index.test.ts, src/api/helpers/send-email-confirm-email-address/index.ts, src/api/schema.graphql, src/api/schema.prisma, src/api/schema.ts, src/api/test-mocks/index.ts, src/api/types.ts, src/ui/server/controllers/insurance/account/sign-in/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/index.ts, src/ui/server/graphql/mutations/account/sign-in.ts
This PR improves a the account sign in process for unverified users. If a user has not verified their email during the account creation process, when they attempt to sign in, we now do the following:
- If an account has a verification hash/token and the expiry period has not passed:
- Reset the verification period.
- Resend the "verify your email address" email (with the token).
- In the UI, redirect to the user to the "new link has been sent" page.
- Update account sign in resolver to execute the above checks and return a new flag, `resentVerificationEmail` for the UI. Also improved documentation and logging.
- Extract the email sending logic in `sendEmailConfirmEmailAddress` resolver, into a new helper function to be DRY as it is now executed in multiple places.
- Update the UI to …
=> feat(EMS-1087): Account sign in - Reset verification expiry if account is unverified

e2e-tests/cypress/e2e/journeys/insurance/cannot-skip-flow/declarations/navigate-to-declarations-pages-without-completing-previous-sections.spec.js, e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-only-my-applications.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted/no-access-application-submitted-check-your-answers.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted/no-access-application-submitted-declarations.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted/no-access-application-submitted.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-to-application/acannot-access-application-signed-in-check-your-answers.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-to-application/cannot-access-application-signed-in-check-your-answers.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-to-application/cannot-access-application-signed-in-declarations.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-to-application/no-access-to-application-signed-in.spec.js, e2e-tests/cypress/e2e/journeys/insurance/no-access-to-application/no-access-to-application.spec.js, src/api/.keystone/config.js, src/api/schema.prisma
This PR adds E2E test coverage to ensure that:
- A user cannot access any "declarations" page if the user is not the application owner.
- A user cannot access any "check yor answers" page  if the user is not the application owner.
- A user cannot access any "declarations" page if the application is submitted.
- A user cannot access any "check yor answers" page if the application is submitted.
Also aligned a few comments/conventions.
=> feat(EMS-1344-1346): Application access - E2E test coverage

src/api/.keystone/config.js, src/api/custom-resolvers/mutations/account-password-reset.test.ts, src/api/custom-resolvers/mutations/account-password-reset.ts, src/api/custom-resolvers/mutations/account-sign-in.ts, src/api/custom-resolvers/mutations/verify-account-sign-in-code.ts, src/api/helpers/get-authentication-retries-by-account-id/index.test.ts, src/api/helpers/get-authentication-retries-by-account-id/index.ts
This PR updates the account password reset GQL resolver to reset the account's authentication retry entries.
- Update account password reset GQL resolver to call `deleteAuthenticationRetries` helper function.
- Fixed some typos.
- Added missing test coverage for `getAuthenticationRetriesByAccountId` helper function.
=> feat(EMS-1662): Account password reset - reset auth retries

e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/sign-in-already-blocked/account-sign-in-already-blocked.spec.js, src/api/.keystone/config.js, src/api/custom-resolvers/mutations/account-sign-in.test.ts, src/api/custom-resolvers/mutations/account-sign-in.ts
This PR updates account sign in so that if an account is already blocked, we reject the sign in.
- Update the sign in GQL resolver to return `isBlocked=true`, if the account is already blocked.
- Add E2E test coverage for this scenario.
=> feat(EMS-1639): Account sign in - reject if already blocked

e2e-tests/cypress/e2e/journeys/insurance/complete-eligibility-ansewrs-for-a-second-time.spec.js, e2e-tests/cypress/support/assert-unchecked-yes-no-radios.js, e2e-tests/cypress/support/commands.js, src/ui/package-lock.json, src/ui/package.json, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
This PR updates the UI's "create application" logic so that insurance eligibility session data is wiped after account creation, which in turn forces a user to complete insurance eligibility answers when creating a new application. Previously, eligibility answers would be prepopulated.
- Update "sign in - enter code" UI controller to wipe insurance eligibility session data after application creation.
- Update "eligible to apply online" UI controller to wipe insurance eligibility session data after application creation.
- Add E2E test coverage to check the insurance eligibility answers are not prepopulated when going through the flow for a second time. Uses new cypress command, `assertUncheckedYesNoRadios`.
- Add missing data sanitisation to the "sign in - enter code" UI controller.
- Bump …
=> fix(EMS-1623): Wipe insurance eligibility session data when creating a new application

e2e-tests/content-strings/pages/quote.js, e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/link-sent/account-password-reset-link-sent.spec.js, e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js, e2e-tests/cypress/e2e/pages/quote/yourQuote.js, src/ui/server/content-strings/pages/quote.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts, src/ui/templates/quote/your-quote.njk
This PR updates the "start full application" link in the "your quote" page to point to the insurance start page, instead of an external PDF form.
- Update the "start full application" link.
- Refactor some content in the "your quote page to use standard HTML elements instead of `detailsText` nunjucks component - makes it easier to read and maintain.
- Add missing E2E test coverage for the "what happens next" section and refactored content.
- Fixed a UI unit test relating to date stub/time of year.
- Added a missing `deleteAccount` cypress command in an E2E test for password reset.
=> feat(EMS-1687): Quote - Update 'full application' link, refactor some page content

e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js, e2e-tests/cypress/support/insurance/account/assert-confirm-email-page-content.js, src/ui/server/controllers/insurance/business/nature-of-business/map-submitted-data/index.test.ts, src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts, src/ui/server/test-mocks/index.ts, src/ui/server/test-mocks/mock-business-nature-of-business.ts
This PR fixes a typo and improves some E2E test coverage.
- Rename all instances of `mockExporterNatureOfBusiness` to `mockBusinessNatureOfBusiness`.
- Add missing assertion to "resend confirm email - go back" E2E test.
- Simplify `assertConfirmEmailPageContent` link checking in cypress command.
=> chore(tech): Fix typo, E2E test coverage improvement

e2e-tests/cypress/e2e/journeys/insurance/account/account-creation-and-sign-in-with-eligibility-answers.spec.js, e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-application.js, src/api/.keystone/config.js, src/ui/server/controllers/insurance/account/create/your-details/index.test.ts, src/ui/server/controllers/insurance/account/create/your-details/index.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts, src/ui/server/helpers/can-create-an-application/index.test.ts, src/ui/server/helpers/can-create-an-application/index.ts, src/ui/server/test-mocks/mock-application.ts, src/ui/server/test-mocks/mock-eligibility.ts
This PR updates the POST controller for "account creation - your details" so that if eligibility answers are in the session, we create an application associated to the account.
This fixes an issue/enhances the UX where if a user verifies an account via email link, the eligibility session answers are lost because a new session has started.
- Update "your details" POST controller to call the API to create an application if eligibility answers are available.
- Create a new helper function `canCreateAnApplication`, since we would otherwise have the same conditional statment in 3 places.
- Add more documentation.
- Extract `eligibility` test mocks into its own directory.
- Fixed a typo.
=> feat/fix(EMS-1688): Account creation - create an application if eligibility answers are available

src/api/.keystone/config.js, src/api/constants/index.ts, src/api/custom-resolvers/mutations/verify-account-sign-in-code.test.ts, src/api/helpers/generate-otp/index.test.ts
This PR extends the OTP expiration time. This is due to some user/accessibility issues where the OTP/security code would not arrive in an email inbox in time and therefore a user would not be able to sign in to their account.
- Create `DATE_30_MINUTES_FROM_NOW` constant.
- Update `OTP.VERIFICATION_EXPIRY` constant.
- Update unit tests.
=> feat(EMS-1710): Account sign in - update OTP expiry time

e2e-tests/content-strings/pages/index.js, e2e-tests/cypress/e2e/journeys/insurance/page-not-found.spec.js, e2e-tests/cypress/e2e/journeys/page-not-found.spec.js, e2e-tests/cypress/support/check-page-not-found-page-text.js, e2e-tests/cypress/support/commands.js, src/ui/server/content-strings/pages/index.ts, src/ui/templates/insurance/page-not-found.njk, src/ui/templates/page-not-found.njk
* Page not found page for quote/root had missing contact us text
* Added to PAGE_CONTENT_STRINGS so there is a HREF for quote and insurance
* Added missing text to page not found
* Refactored tests with shared function
=> fix(EMS-1554): Page not found - Missing wording

e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset.spec.js, e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-single-policy-type-different-contact-details.spec.js, e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js, e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js, e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/summary-list/check-your-answers-policy-and-exports-multiple-summary-list.spec.js, e2e-tests/cypress/support/insurance/complete-and-submit-your-contact-form.js, e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-multiple.js, e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-single.js, e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js, src/api/.keystone/config.js, src/api/constants/XLSX-CONFIG/index.test.ts, src/api/constants/XLSX-CONFIG/index.ts, src/api/content-strings/XLSX.ts, src/api/generate-xlsx/header-columns/index.test.ts, src/api/generate-xlsx/header-columns/index.ts, src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.ts, src/api/generate-xlsx/map-application-to-XLSX/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.ts, src/api/generate-xlsx/styled-columns/index.test.ts, src/api/generate-xlsx/styled-columns/index.ts, src/api/types.ts
This PR updates the XLSX generation mapping to include exporter contact details (reagrdless of if they are the same as the application owner).
Update various cypress command (including `completeAndSubmitYourContact`) to accept `useDifferentContactEmail` flag/argument.
- Refactor `XLSX_CONFIG` constants so that:
- `ROW_INDEXES` are seperated from the config - otherwise becomes messy and we have to pass application to the config, when the config doesn't actually require any data.
- Returns both `TITLES` indexes and non-title indexes.
- Add exporter contact details mapping.
- Add E2E test coverage for submitting a single policy with different contact details.
- Added some missing documentation to some E2E commands.
- Simplify `styledColumns`.
- Add TS types for the `ROW_INDEXES`.
=> feat(EMS-1689): Application submission - XLSX - add exporter contact details

e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/password-as-number/sign-in-password-as-number.spec.js, src/ui/server/controllers/insurance/account/sign-in/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/index.ts
* When password is a number only, it caused service to go to problem with service page
* Cast password as a string so graphql does not receive only a number
* Added tests
=> fix(EMS-1729): Account - Sign in - Password as numbers only

e2e-tests/constants/account.js, e2e-tests/cypress/support/insurance/account/complete-and-submit-password-reset-form-maximum-retries.js, e2e-tests/cypress/support/insurance/account/complete-and-submit-sign-in-account-form-maximum-retries.js, src/api/.keystone/config.js, src/api/constants/index.test.ts, src/api/constants/index.ts, src/api/custom-resolvers/mutations/account-sign-in.test.ts, src/api/custom-resolvers/mutations/send-email-password-reset-link.test.ts, src/api/custom-resolvers/mutations/send-email-password-reset-link.ts, src/api/helpers/date/index.test.ts, src/api/helpers/date/index.ts, src/api/helpers/should-block-account/index.test.ts, src/api/helpers/should-block-account/index.ts
This PR fixes an issue where the `shouldBlockAccount` check would include auth retry attempts would include attempts outside of `MAX_AUTH_RETRIES_TIMEFRAME`.
- Create new API constant helper, `DATE_24_HOURS_IN_THE_PAST`.
- Create new API date helper, `getYesterdayDay`. This is used for unit tests.
- Update API `shouldBlockAccount` helper function to use `isAfter` and `isBefore` date-fns functions instead of `isWithinInterval`.
- Rename some API constants since they are not specific to password reset.
- `MAX_PASSWORD_RESET_TRIES` is now `MAX_AUTH_RETRIES`.
- `MAX_PASSWORD_RESET_TRIES_TIMEFRAME` is now `MAX_AUTH_RETRIES_TIMEFRAME`.
=> fix(EMS-1701): Account suspension - fix issue where retries check would include irrelevant retries

e2e-tests/constants/routes/index.js, e2e-tests/constants/routes/insurance/index.js, e2e-tests/content-strings/buttons.js, e2e-tests/content-strings/pages/index.js, e2e-tests/cypress/e2e/journeys/insurance/cookies-saved-visit-directly-when-signed-in.spec.js, e2e-tests/cypress/e2e/journeys/insurance/cookies-saved.spec.js, e2e-tests/cypress/e2e/journeys/insurance/cookies.spec.js, e2e-tests/cypress/e2e/journeys/quote/cookies-saved.spec.js, e2e-tests/cypress/e2e/journeys/quote/cookies.spec.js, e2e-tests/cypress/e2e/pages/cookies-saved.js, e2e-tests/cypress/e2e/pages/cookies.js, e2e-tests/cypress/e2e/pages/index.js, src/ui/server/constants/routes/index.ts, src/ui/server/constants/routes/insurance/index.ts, src/ui/server/constants/templates/index.ts, src/ui/server/content-strings/buttons.ts, src/ui/server/content-strings/pages/index.ts, src/ui/server/controllers/root/cookies/index.test.ts, src/ui/server/controllers/root/cookies/index.ts, src/ui/server/controllers/root/cookies/saved/index.test.ts, src/ui/server/controllers/root/cookies/saved/index.ts, src/ui/server/middleware/insurance/application-access/index.test.ts, src/ui/server/middleware/insurance/application-access/index.ts, src/ui/server/routes/root/index.test.ts, src/ui/server/routes/root/index.ts, src/ui/templates/cookies-saved.njk, src/ui/templates/cookies.njk, src/ui/types/express/index.d.ts
This PR adds a new "Cookies saved" page, replacing the "Cookes updated" success banner.
- Create new route, controller and template for the "Cookies saved" page.
- Add E2E test coverage for the new page in both quote and insurance routes.
- ⚠️ Note there is a lot of existing duplication for the cookies E2E tests, we can improve this in a future PR. 
- Update the existing cookies E2E tests to test for the correct redirection and "return to service" button link depending on how a user got to the page.
=> feat(EMS-1742): Cookies saved page

e2e-tests/content-strings/pages/insurance/account/index.js, e2e-tests/cypress/e2e/journeys/insurance/account/suspended/account-suspended-reactivate-after-link-expired.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/suspended/link-expired/account-suspended-link-expired.spec.js, e2e-tests/cypress/e2e/pages/insurance/account/suspended/index.js, e2e-tests/cypress/e2e/pages/insurance/account/suspended/linkExpired.js, src/api/.keystone/config.js, src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts, src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts, src/api/custom-schema/type-defs.ts, src/api/schema.graphql, src/api/types.ts, src/ui/server/content-strings/pages/insurance/account/index.ts, src/ui/server/controllers/insurance/account/suspended/index.ts, src/ui/server/controllers/insurance/account/suspended/link-expired/index.test.ts, src/ui/server/controllers/insurance/account/suspended/link-expired/index.ts, src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts, src/ui/server/controllers/insurance/account/suspended/verify-email/index.ts, src/ui/server/graphql/mutations/account/verify-account-reactivation-token.ts, src/ui/server/routes/insurance/account/index.test.ts, src/ui/server/routes/insurance/account/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/templates/insurance/account/suspended/link-expired.njk
This PR adds the ability to reactivate an account when a user is on the "link expired" page.
- Update `/account/suspended/verify-email` GET controller to consume the account ID returned from the API response.
- Add a `account/suspended/link-expired` POST route/controller to call the API to send a new reactivation link.
- Update the "account suspended - link expired" page to render a form and some body text.
-  Reactivating an account after requesting a new verifiaction link when trying to become verified wih an expired verification link.
- "Account suspended - link expired" page content.
=> feat(EMS-1738): Account suspension - Ability to reactivate account when token has expired

src/ui/server/controllers/insurance/account/create/your-details/index.test.ts, src/ui/server/controllers/insurance/account/create/your-details/index.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts, src/ui/server/helpers/can-create-an-application/index.test.ts, src/ui/server/helpers/can-create-an-application/index.ts, src/ui/types/express/index.d.ts
This PR should fix an issue where if a user spams particular submit buttons/form POSTs, multiple applications requests would be made.
- In each POST controller that requests application creation from the API, add a `requestedApplicationCreation` flag to the session and after the call has been made, reverse the flag to be false.
- Update `canCreateAnApplication` helper so that if the session has a `requestedApplicationCreation` flag, the helper will return false.
- Documentation improvements.
- Note: unfortunately, it doesn't seem possible to write an E2E test for this scenario (spamming a submit button during a POST).
=> fix(EMS-1345): Add requestedApplicationCreation to session when creating an application

e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/validation/account-password-reset-new-password-valdation.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code-visit-directly-when-signed-in.spec.js, e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/request-new-code/account-sign-in-request-new-code-visit-directly-when-signed-in.spec.js, src/ui/server/controllers/insurance/account/create/your-details/index.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/controllers/insurance/account/sign-in/index.ts, src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.ts, src/ui/server/index.ts, src/ui/server/middleware/headers/security.ts
This PR updates the "enter code" GET controllers to redirect to the dashboard page if the user is already signed in.
- Update the "enter code" controller to redirect to the dashboard if a user session exists.
- Update the "enter code - request new code" controller to redirect to the dashboard if a user session exists.
- Improve some documentation.
- Removed some TODO comments (fix/EMS-1761).
=> feat(EMS-1761): Account sign in - Enter code - Redirect if already signed in

e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js, e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/account-to-apply-online/account-to-apply-online.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/exporter-location/exporter-location.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/letter-of-credit/letter-of-credit.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js, e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js, e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/working-with-buyer.spec.js, e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js, e2e-tests/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js, e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/cypress/support/check-aria-label.js, e2e-tests/cypress/support/check-radio-input-no-aria-label.js, e2e-tests/cypress/support/check-radio-input-yes-aria-label.js, e2e-tests/cypress/support/commands.js, src/ui/templates/components/yes-no-radio-buttons.njk
This PR fixes an issue where any "yes/no" radio inputs would render a misleading arial label that would result in screenreaders mentioning "radio" twice, e.g "Radio label - yes radio radio", instead of "Radio label - yes radio".
- Remove "radio" copy from both inputs in the "yes no radios" nunjuck component.
- Add a new cypress command to check a "yes" and "no" radio aria labels:
- `checkRadioInputYesAriaLabel`
- `checkRadioInputNoAriaLabel`
- Add E2E test for all yes/no radio buttons aria labels.
- Simplify some E2E tests - no need to manually check that yes/no radio inputs exist as other tests will fail if the input does not exist.
=> fix(EMS-1771): Yes/no radio inputs aria labels

src/ui/server/controllers/insurance/account/create/your-details/index.test.ts, src/ui/server/controllers/insurance/account/create/your-details/index.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts, src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts, src/ui/server/helpers/can-create-an-application/index.test.ts, src/ui/server/helpers/can-create-an-application/index.ts, src/ui/types/express/index.d.ts
This PR updates all instances of the UI's application creation requests so that eligibility answers are immediately wiped from the session instead of waiting for an API response.
- Revert previous changes that added `requestedApplicationCreation` to the session as this is not helping to prevent multiple application submission requests/spam.
- Update all instances of application creation requests to wipe the eligibility answers stored in session before calling the API.
=> fix(EMS-1345): UI application creation requests - immediately wipe eligibility answers from the session

src/ui/templates/insurance/your-buyer/company-or-organisation.njk, src/ui/templates/insurance/your-buyer/working-with-buyer.njk
This PR adds some missing form IDs - therefore the form submission script will now find a form when on a page with these forms.
- Add missing IDs to "company or organisation" and "working with buyer" forms.
=> fix(EMS-1345): Add missing form IDs

e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js, src/ui/templates/components/yes-no-radio-buttons.njk, src/ui/templates/insurance/declarations/anti-bribery.njk, src/ui/templates/insurance/declarations/anti-bribery/code-of-conduct.njk, src/ui/templates/insurance/declarations/anti-bribery/exporting-with-code-of-conduct.njk, src/ui/templates/insurance/declarations/confidentiality.njk, src/ui/templates/insurance/eligibility/account-to-apply-online.njk, src/ui/templates/insurance/eligibility/companies-house-number.njk, src/ui/templates/insurance/eligibility/insured-amount.njk, src/ui/templates/insurance/eligibility/insured-period.njk, src/ui/templates/insurance/eligibility/letter-of-credit.njk, src/ui/templates/insurance/eligibility/other-parties.njk, src/ui/templates/insurance/eligibility/pre-credit-period.njk, src/ui/templates/insurance/eligibility/uk-goods-or-services.njk, src/ui/templates/insurance/policy-and-exports/type-of-policy.njk, src/ui/templates/insurance/your-business/broker.njk, src/ui/templates/insurance/your-business/company-details.njk, src/ui/templates/insurance/your-buyer/company-or-organisation.njk, src/ui/templates/insurance/your-buyer/working-with-buyer.njk, src/ui/templates/quote/buyer-body.njk, src/ui/templates/quote/uk-goods-or-services.njk, src/ui/templates/shared-pages/declaration.njk, src/ui/templates/shared-pages/exporter-location.njk
This PR fixes some radio and checkbox accessibility issues where:
- Some instances were unnecessarily rendering a h1 tag, causing duplicate h1 elements on the same page.
- Some legends were rendering inside of a legend - there should only be one legend.
- Update the `yes-no-radio-buttons` nunjucks component:
- Ability to render a custom heading level via new `headingLevel` param.
- Ability to render a span inside a legend, instead of a heading via new `legendSpan` param.
- Rename `heading` param to `legendText` and `headerClass` param to `legendClass` as it's not always a heading.
- Update all relevant instances of `yes-no-radio-buttons` and re-order some params.
- Change some `legendHtml` instances to render a span tag instead of a legend, otherwise duplicate legend's are rendered.
=> fix(EMS-1846): Duplicate h1 headings, radio/checkbox legend issues

src/ui/server/controllers/insurance/account/create/your-details/index.test.ts, src/ui/server/controllers/insurance/account/password-reset/index.test.ts, src/ui/server/controllers/insurance/account/password-reset/index.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts, src/ui/server/controllers/insurance/business/broker/save-and-back/index.ts, src/ui/server/controllers/insurance/business/contact/save-and-back/index.ts, src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts, src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts, src/ui/server/controllers/insurance/business/turnover/save-and-back/index.ts, src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts, src/ui/server/controllers/insurance/your-buyer/company-or-organisation/save-and-back/index.test.ts, src/ui/server/controllers/insurance/your-buyer/company-or-organisation/save-and-back/index.ts, src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.test.ts, src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.ts, src/ui/server/controllers/root/cookies/index.test.ts, src/ui/server/controllers/root/cookies/index.ts, src/ui/server/helpers/task-list/index.ts
This PR updates various UI controllers to ensure that:
- Submitted values and Validation errors are consuming a payload instead of `req.body`.
- API requests are using a payload instead of `req.body`.
- Account sign in, password reset controllers.
- Declarations - How your data will be used controller.
- Your business - various  controllers.
- Your buyer - various  controllers.
- Policy and export - various controllers.
- Cookies  controller.
=> chore(EMS-1864): Update various UI controllers to use and test payload construction

src/ui/server/middleware/headers/security/index.ts
There's currently an issue in the dev environment where some UI request headers do not match or could be undefined. 
We have some middleware that checks these headers and if they don't match, we nullify the headers. One of these headers is used to render a back link in each page which is currently not working.
Unable to replicate the issue locally so need to add some logs so that we can debug in the dev envrionment.
=> fix(EMS-1890): add temporary logs to debug in dev environment

src/ui/server/controllers/insurance/business/broker/save-and-back/index.test.ts, src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts, src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts, src/ui/server/controllers/insurance/business/contact/save-and-back/index.test.ts, src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts, src/ui/server/controllers/insurance/business/turnover/save-and-back/index.test.ts, src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts, src/ui/server/controllers/insurance/your-buyer/company-or-organisation/save-and-back/index.test.ts, src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.test.ts, src/ui/server/controllers/quote/buyer-country/index.ts, src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts, src/ui/server/helpers/get-valid-fields/index.ts
This PR makes various updates to some conditions in UI controllers and simplifies some unit tests.
- Update some UI controller conditions to use `objectHasProperty` and use more destructuring.
- Remove some unnecessary `describe('post - save and back', () => { ... ` blocks in some unit tests.
- Minor documentation improvement.
=> chore(EMS-977-1317): Improve UI controller conditions, simplify some unit tests

e2e-tests/content-strings/cookies-consent.js, e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-apply-page.spec.js, e2e-tests/cypress/e2e/journeys/quote/cannot-apply-page.spec.js, src/ui/server/content-strings/cookies-consent.ts
This PR fixes some typos (missing space), in the cookies banner and also fixes some invalid/misleading E2E tests.
- Fix cookies banner typos in content strings.
- Update 2x "cannot apply" E2E tests so that they are asserting a URL after clicking a link - previously the description mentions this, but was not actually testing this.
=> fix(EMS-1898): Cookies banner typos, invalid/misleading E2E tests

e2e-tests/content-strings/error-messages.js, e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js, src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts, src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts
This PR fixes an issue where when submitting an empty form in the "Quote - policy type" page, the validation error summary would not not display an error message.
- Fix a typo in E2E error message content strings.
- Fix a typo in UI validation function.
- Add missing E2E test coverage.
=> fix(EMS-1901): Quote - policy type - missing error message

e2e-tests/content-strings/fields/index.js, e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js, e2e-tests/pages/quote/policyType.js, e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js, src/ui/server/content-strings/fields/index.ts, src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts, src/ui/templates/quote/policy-type.njk
This PR updates the "kind of policy page in the quote tool so that more information is available in the hints for a user. Also made some technical improvements.
- Update "policy type" hint content strings, and nunjucks template.
- Remove the inset text previously used for multiple contract policies.
- Simplify policy type input, label and hint `data-cy` attributes.
=> feat(EMS-1918): Quote - Kind of policy - copy updates

src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.ts
* `hasDifferentTradingName `and `hasDifferentTradingAddress`,  `isUsingBroker`, `canContactBuyer`, `exporterIsConnectedWithBuyer`, `exporterHasTradedWithBuyer `showed true or nothing on XLSX on submission
* Used `mapYesNoField` for fields
=> fix(EMS-1938): Submission - Trading name and address incorrect XLSX format

e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-16-applications.spec.js, src/ui/server/helpers/pagination/get-total-pages/index.test.ts, src/ui/server/helpers/pagination/get-total-pages/index.ts
This PR fixes an issue where the dasboard pagination would not diplay if the total amount of applications is just over the maximum amount allowed per page, for example if there are ~16-19 applications, pagination would not display because the total pages functionality was not rounding **_up_** to the nearest number.
- Update `getTotalPages` function to use `Math.ceil` instead of `Math.round`, therefore it'll always round up.
- Add E2E test coverage for pagination when there are 16 applications.
=> fix(EMS-1159): Dashboard pagination - Fix issue where "total pages" count would not round up

e2e-tests/insurance/cypress.config.js, e2e-tests/quote/cypress.config.js, e2e-tests/switch-between-services/cypress.config.js
By default Cypress discards any CSP headers, ensure they are adhered to.
* Added `experimentalCspAllowList`.
* Lint fixes
=> fix(cypress): added CSP headers to cypress configuration

e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js, e2e-tests/partials/insurance/taskList.js, src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.test.ts, src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.ts, src/ui/server/helpers/task-list/index.test.ts, src/ui/server/helpers/task-list/index.ts, src/ui/server/helpers/task-list/task-helpers.test.ts, src/ui/server/helpers/task-list/task-helpers.ts, src/ui/types/task-list.ts
This PR fixes an issue where the "eligibility" task in the "initial checks" group of an application's task list would display an empty link ("#").
- Remove "href" definition in `createInitialChecksTasks`.
- Update `generateTaskStatusesAndLinks` task mapping logic to optionally add a href to a task.
- Update `taskLink` function to return an empty string instead of null.
- Make a tasks href an optional type.
- Extract task mapping logic into its own function, `mapTask`.
- Fixed a typo.
- Simplified some E2E task assertions.
=> fix(EMS-806): Task list - remove link from eligibility task

.github/workflows/test.yml, src/api/.keystone/config.js, src/ui/server/helpers/sanitise-environment/index.test.ts, src/ui/server/helpers/sanitise-environment/index.ts
Ensure double quotes environment variables successfully escapes `\\n|\\\n|\\\\n`.
* Updated RegEx with values in double quotes.
* Function argument data type fix
=> fix(escape): escaping environment variables with double quotes

e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-once-and-sign-in.spec.js, e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-twice-and-sign-in.spec.js, src/api/.keystone/config.js, src/api/custom-resolvers/mutations/account-password-reset/index.ts, src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts, src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.ts, src/api/custom-resolvers/mutations/create-an-account/index.ts, src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.ts, src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts, src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.ts, src/api/custom-resolvers/mutations/verify-account-email-address/index.ts, src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts, src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.ts, src/api/helpers/block-account/index.test.ts, src/api/helpers/block-account/index.ts, src/api/helpers/generate-otp-and-update-account/index.ts, src/api/helpers/get-account-verification-hash/index.test.ts, src/api/helpers/get-account-verification-hash/index.ts, src/api/helpers/send-email-confirm-email-address/index.ts, src/api/helpers/update-account/index.test.ts, src/api/helpers/update-account/index.ts, src/api/types/account/index.ts
Somehow, a bug has evolved or has been not been spotted where, when a user creates an account - an email is sent to the provided email address so that the email can be provided. When requesting another verification email link, a token would not be included in the email.
- Extract verification hash and expiry generation from the `createAnAccount` GQL resolver and into a new `generateAccountVerificationHash helper function.
- Update "send confirm email" GQL resolver so that if an account does not have a verification hash, a new one will be generated and added to the account and sent to Notify.
- Create generic `update.account` API helper function, update various resolvers.
- Successfully signing into an account after verification by clicking "request new link" …
=> fix(EMS-2080): Account verification - token not sent via email 

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts, src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
This PR simplifies the policy and export user flow, when a user changes the policy type from "single" to "multiple" and vice versa.
Previously, after changing a policy type, a user would have to complete the entire policy and export section when only 1 additional form is required.
Now, when the 1 additional form is submitted, we redirect the user back to the relevant "check your answers" page.
- Update the UI's "type of policy" controller to, depending on `req.originalUrl`:
- Redirect to "single/multiple policy page" with an additional `/change` in the URL.
- Redirect to an application's "check your answers - policy type".
- Various destructuring improvements.
- Simplify some E2E test coverage.
- Add some missing test coverage.
=> feat(EMS-2076): Policy and exports - Redirect to answer pages when changing policy type

e2e-tests/content-strings/fields/insurance/policy/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js, src/api/.keystone/config.js, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/server/controllers/insurance/policy/name-on-policy/index.test.ts, src/ui/server/controllers/insurance/policy/name-on-policy/index.ts
This PR fixes various bugs on name on policy page / summary list
[EMS-2083](https://ukef-dtfs.atlassian.net/browse/EMS-2083) - Missing question mark at end of label
[EMS-2084](https://ukef-dtfs.atlassian.net/browse/EMS-2084) - Owner name and radio would disappear if validation error
[EMS-2089](https://ukef-dtfs.atlassian.net/browse/EMS-2089) - Summary list was missing `the`
* Fixed typo bugs
* fixed radio disappearing by combining name from owner and payload when rendering template in post controller
* Updated and added e2e test and unit test
=> fix(EMS-2083-2084-2089): Name on policy - Bug fixes

src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
After some data changes (moving a field from `eligibility` into `policy`), one field/row in the XLSX that's generated on application submission is no longer mapped correctly.
- Update "map policy" function to reference the correct object.
=> fix(EMS-2088): Application submission - XLSX mapping

.github/workflows/infrastructure.yml
Rectify alert condition to avoid constant alert condition trigger, ensure availability is always over `99%`.
* Aggregation set to `Average`.
* Operator set to `Less then or equal to`.
* Operand set to `99%`.
* Timeframe set to `5 minute`.
* If the average origin health dips below `99%` over 5 minutes duration on every 1 minute check then an alert group will be triggered. It has not been set to `100%` due to occasional rate-limiter threshold exceed thus reducing the average to `99.8%`.
=> fix(alert-condition): condition updated to average 99 over 5 minutes

src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts, src/ui/server/helpers/map-cover-period-id/index.test.ts, src/ui/server/helpers/map-cover-period-id/index.ts, src/ui/server/helpers/map-total-contract-value/index.test.ts, src/ui/server/helpers/map-total-contract-value/index.ts
2x "yes/no" answer fields in the XLSX generated on application submission were incorrectly mapped after some recent data chagnes.
* Swap the UI mappings for `mapCoverPeriodId` and `mapTotalContractValue`.
- Fixed some typos.
=> fix(EMS-2206): Application submission - XLSX eligibility yes/no answers

src/api/package-lock.json, src/api/package.json, src/ui/package-lock.json, src/ui/package.json
- Dependabot flagged some dependency updates.
- Update `express-rate-limit`.
=> chore(deps): Bump express-rate-limit

e2e-tests/commands/insurance/check-credit-period-with-buyer-input.js, e2e-tests/commands/insurance/check-policy-currency-code-input.js, e2e-tests/content-strings/fields/insurance/policy/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js, e2e-tests/partials/insurance/creditPeriodWithBuyerFormField.js, e2e-tests/partials/insurance/index.js, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/templates/components/credit-period-with-buyer-hint.njk, src/ui/templates/insurance/policy/multiple-contract-policy.njk, src/ui/templates/insurance/policy/single-contract-policy.njk
The "credit period" field in the "tell us about your policy" form(s) requires a copy update. The copy should now be a hint list, with updated copy, instead of a single line of text.
- Update the "credit period" content strings so that the hint is a list with an intro.
- Create cypress function to assert the "credit period" hint, label and input - `checkCreditPeriodWithBuyerInput`, using a new shared field selector, `creditPeriodWithBuyerFormField`.
- Update "single" and "multiple" contract policy E2E tests to use the new cypress function.
- Create `credit-period-with-buyer-hint` nunjucks component.
- Update "single" and "multiple" nunjuck components to use the new "hint" component.
=> fix(EMS-2236): Application - update credit period hint text

e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/index.js, e2e-tests/content-strings/pages/index.js, e2e-tests/content-strings/pages/quote.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/cannot-apply-page.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js, src/ui/server/content-strings/actions.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/index.ts, src/ui/server/content-strings/pages/index.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/server/controllers/insurance/eligibility/exporter-location/index.test.ts, src/ui/server/controllers/insurance/eligibility/exporter-location/index.ts, src/ui/templates/cannot-apply.njk, src/ui/templates/shared-pages/exporter-location.njk
This PR updates the "exporter location" and exit page in the "eligibility" flow, for both the quote tool and No PDF/insurance eligibility.
- Add a hint to "exporter location" field content strings and form.
- Update "exporter location"  page title/label.
- Update the `UNSUPPORTED_COMPANY_COUNTRY` content string, used in the exit page
- Extract the UI's `CONTACT_EFM` action string into the shared `ACTIONS` content strings, since its now shared.
- Add `CONTACT_EFM` action to the "cannot appy" exit page template.
- Fix/update an error message for the "do you have a companies house number" question.
=> feat(EMS-2100-2106-2261): No PDF - Eligibility - Exporter location and exit page content updates

e2e-tests/content-strings/actions.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-not-active/company-not-active.spec.js, src/ui/server/content-strings/actions.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/templates/insurance/eligibility/companies-house-exit.njk
The "Inactive company" exit page had some incorrect content. This PR now aligns the "inactive company" exit page with the new no PDF design.
- Split up/change companies house exit page content strings.
- Update the companies house exit page to conditionally render some text and "action" list items.
=> fix(EMS-2113): No PDF - Eligibility - inactive company exit page

e2e-tests/content-strings/pages/insurance/business/index.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/server/content-strings/pages/insurance/your-business/company/index.ts, src/ui/templates/insurance/your-business/company-details.njk
- "Your business - company details" had some missing intro/body text.
- "Long term cover" exit page had an incorrect "PDF" link.
- Add missing intro/body text.
- Update the "PDF" link used in the "Long term cover" exit page.
=> fix(EMS-2316-2318): No PDF - missing guidance text, PDF link

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, package-lock.json, package.json
This PR updates the "no pdf" branch to have the latest code from `main`.
This should trigger the github PR template to be populated in PRs, because `main-application-no-pdf` is the base branch.
- Merge `main` into `main-application-no-pdf`
=> chore(merge): Merge `main` into `main-application-no-pdf`

e2e-tests/content-strings/pages/quote.js, e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js, src/ui/server/content-strings/pages/quote.ts
The quote tool has a link to start creating a full application - this was pointing to our own "start insurance" page, however it should point to an external GOV page.
- Update the "full application" link.
- Update a quote E2E test to assert the link via externl links instead of the link in content strings.
=> fix(EMS-2341): Quote page - update application link

e2e-tests/content-strings/pages/insurance/policy/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js, src/api/package-lock.json, src/ui/server/content-strings/pages/insurance/policy/index.ts, src/ui/server/helpers/companies-house-search/validation/rules/companiesHouseNumber.ts, src/ui/templates/insurance/policy/type-of-policy.njk
This PR fixes an issue where the "policy type" page had an intro that is no longer required for no PDF.
- Remove intro from "policy type" page.
- Update an E2E test to use more consts/variables (mentioned in another PR).
- Rename a `Joi.string()` const name (mentioned in another PR).
=> fix(EMS-2407): No PDF - Remove policy type intro. Minor tech improvements

src/ui/server/helpers/summary-lists/companies-house/index.test.ts
This PR improves the Companies house summary list unit tests.
- Split up each summary list field assertion into its own test, making debugging easier.
=> chore(EMS-722): Split up Companies house summary list assertions

e2e-tests/content-strings/fields/insurance/export-contract/index.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js, e2e-tests/pages/insurance/export-contract/aboutGoodsOrServices.js, src/ui/server/content-strings/fields/insurance/export-contract/index.ts, src/ui/templates/insurance/export-contract/about-goods-or-services.njk
This PR updates the content strings for "About goods or services" fields so that they are aligned with the latest no PDF design.
- Update E2E test.
=> feat(EMS-2399): No PDF - About goods or services - content updates

src/ui/templates/components/accessible-autocomplete-select.njk, src/ui/templates/insurance/export-contract/about-goods-or-services.njk, src/ui/templates/shared-pages/buyer-country.njk
This PR fixes an issue with all "buyer country" fields, where a red border would be displayed/wrapped around the form input and label.
- Update invalid class name.
- Ensure the class name/div is wrapping the appropriate elements.
- Create a DRY, resuable component for the autocomplete script and select options, `accessibleAutoCompleteSelect`.
=> fix(EMS-2453): Buyer country field - styling issue, DRY autocomplete component

src/ui/templates/components/accessible-autocomplete-select.njk, src/ui/templates/insurance/policy/about-goods-or-services.njk, src/ui/templates/shared-pages/buyer-country.njk
This PR fixes an issue with all "buyer country" fields, where a red border would not be displayed/wrapped around the form input and label.
- Update invalid class name.
- Ensure the class name/div is wrapping the appropriate elements.
- Create a DRY, resuable component for the autocomplete script and select options, `accessibleAutoCompleteSelect`.
=> fix(EMS-2453): Buyer country - fix styling issue

e2e-tests/commands/analytics/check-cookies-consent-banner-does-not-exist.js, e2e-tests/commands/analytics/check-cookies-consent-banner-is-not-visible.js, e2e-tests/commands/analytics/check-cookies-consent-banner-is-visible.js, e2e-tests/content-strings/cookies-consent.js, e2e-tests/content-strings/pages/index.js, e2e-tests/content-strings/pages/insurance/index.js, e2e-tests/insurance/cypress/e2e/journeys/start.spec.js, e2e-tests/pages/insurance/start.js, e2e-tests/partials/cookieBanner.js, e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js, e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js, e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent.spec.js, e2e-tests/quote/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js, src/ui/server/content-strings/cookies-consent.ts, src/ui/server/content-strings/pages/index.ts, src/ui/server/content-strings/pages/insurance/index.ts, src/ui/templates/cookies.njk, src/ui/templates/insurance/start.njk, src/ui/templates/partials/cookies-banner.njk
This PR updates various pieces of content for the start page, cookies banner and cokies page.
- Add "extra" support content block to the start page.
- Update the start page E2E test to assert links via `LINKS`.
- Remove some unnecessary `.should('exist')` checks in cookies E2E tests.
=> style(EMS-2447 2451): Start page, cookies banner, cookies page content improvements

README.md, e2e-tests/commands/shared-commands/assertions/assert-first-and-last-radios.js, e2e-tests/commands/shared-commands/assertions/index.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js, e2e-tests/pages/shared/index.js, src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts, src/ui/templates/components/yes-no-radio-buttons.njk, src/ui/templates/insurance/export-contract/about-goods-or-services.njk
This PR updates the "About goods or services" form to order the yes/no radio buttons in the opposite order ("no" radio button as the first option).
Here, we are setting up patterns/approaches to be used in other future forms that will have the same requirement.
- Create new cypress command to assert multiple radio button input `data-cy` values via index, `assertYesNoRadiosOrder`.
- Update "About goods or services" E2E test to check the ordering of the radio buttons.
- Update `yesNoRadioButtons` nunjucks component to optionally render the "no" radio option as the first option.
- Update "About goods or services" nunjucks template to pass a `noRadioAsFirstOption` flag to the `yesNoRadioButtons` nunjucks component.
- Update SRI documentation.
- Fixed a date issue in a validation unit test.
=> fix(EMS-2399-2418): No PDF - About goods or services - yes/no radio ordering

src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
This PR fixes an issue where a unit test's date assertion was failing due to the month being set to `0`, an invalid month.
- Update mock month in "contract completion date" unit test.
=> fix(test): Invalid month causing unit test to fail

e2e-tests/pages/quote/policyType.js, e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js, src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts, src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts, src/ui/templates/cookies.njk, src/ui/templates/quote/policy-type.njk
This PR fixes an issue where the "Policy type" form validation would not render an inline error.
- Update the "policy type" validation rule to use a field ID for the first radio option, `SINGLE_POLICY_TYPE`, instead of `POLICY_TYPE`; Also simplifying the logic.
- Fix/update nunjucks template.
- Simplify single and multiple radio option references in the "policy type" nunjucks template.
- Fixed a typo.
=> fix(EMS-2492): Quote - Policy type form validation

e2e-tests/commands/insurance/requested-start-date-field.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js, src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts, src/ui/server/shared-validation/requested-start-date/index.test.ts
This PR fixes some issues with the UI and E2E tests where the generated months would be `0`, due to date constructions being index based and the current time of year.
- Fix/update months; Always add 1 so the month's will never be 0.
- Remove some hard coded year values.
=> fix(tests): Mock months generated as 0

.github/workflows/publish.yml
Ensure default branch is not the GitHub base branch.
* Specified `target-branch` to be `main`
=> fix(release-please): specify target branch

e2e-tests/commands/insurance/complete-and-submit-export-value-form.js, e2e-tests/commands/insurance/complete-export-value-form.js, e2e-tests/commands/insurance/date-field.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/insurance/policy/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.ts, src/ui/server/shared-validation/date/index.test.ts, src/ui/server/shared-validation/date/index.ts, src/ui/server/shared-validation/requested-start-date/index.test.ts, src/ui/server/shared-validation/requested-start-date/index.ts, src/ui/types/errors.ts, src/ui/types/index.d.ts
This PR updates the validation rules for the "contract completion date" field, for the Policy type's "single contract policy" form.
- Update content strings (error messages, field hint).
- Extract recently enhanced "requested start date" validation rules into a new "generic date validation" helper function.
- Update `contractCompletionDateRules` to call "generic date validation" helper function.
- Update cypress "check date validation" function to check for errors when there are 2 date fields:
- Dates cannot be the same date.
- Second date cannot be before the first date.
- Second date cannot be after a certain time period.
- Update an error message used for the currency field.
- Update cypress "check date validation" function to have object structured params.
- Minor destructuring and …
=> feat(EMS-2349-2536): No PDF - Policy type - Completion date validation enhancements

e2e-tests/constants/routes/insurance/policy.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value.spec.js, src/ui/server/constants/routes/insurance/policy.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/save-and-back/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/policy/index.test.ts, src/ui/server/routes/insurance/policy/index.ts
This PR adds "save and back" functionality to the "Total contract value" form in the Single contract policy section of a no PDF application
- Add new "save and back" route and POST endpoint.
- Add `SAVE_AND_BACK_URL` page variable to the "Total contract value" GET controller.
- Minor destructuring improvements.
=> feat(EMS-2524): No PDF - Single contract policy - Total contract value - save and back

e2e-tests/commands/insurance/complete-and-submit-pre-credit-period-form.js, e2e-tests/commands/insurance/complete-policy-section.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/broker-email-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/broker-postcode-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-same-name-to-different-name.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/different-name-on-policy-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/entering-details-of-policy-owner.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/name-on-policy-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js, e2e-tests/insurance/cypress/support/application/business/index.js, e2e-tests/insurance/cypress/support/application/policy/index.js, src/ui/server/controllers/insurance/policy/different-name-on-policy/index.test.ts, src/ui/server/controllers/insurance/policy/different-name-on-policy/index.ts, src/ui/server/controllers/insurance/policy/name-on-policy/index.test.ts, src/ui/server/controllers/insurance/policy/name-on-policy/index.ts, src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts, src/ui/server/controllers/insurance/policy/pre-credit-period/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/policy/index.test.ts, src/ui/server/routes/insurance/policy/index.ts
This PR updates the Policy form submission redirects to that the "Pre-credit period" form is part of the flow.
Note - there is no form validation yet, this is purely updating the flow.
- Update the `NAME_ON_POLICY` and `DIFFERENT_NAME_ON_POLICY` forms to redirect to the `PRE_CREDIT_PERIOD` page, instead  of `BROKER`.
- Add a`PRE_CREDIT_PERIOD` POST endpoint redirect to the `BROKER` page.
- Create new cypress command `completeAndSubmitPreCreditPeriodForm`. This will eventually be updated to actually complete the form.
- Update all relevant E2E tests and commands to submit the "Pre-credit period" form before submitting the "broker" form.
- Moved the `completeAndSubmitBrokerForm` cypress command into the policy directory.
=> feat(EMS-2572): No PDF - Policy - Pre-credit period - Form submission, redirection flow

e2e-tests/commands/insurance/complete-and-submit-about-goods-or-services-form.js, e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/uk-goods-and-services-calculate-description.js, e2e-tests/content-strings/uk-goods-and-services-description.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/uk-goods-and-services-calculate-description.ts, src/ui/server/content-strings/uk-goods-and-services-description.ts, src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts, src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
This PR fixes some issues where:
- "About goods or services" had some copy that did not match the No PDF design.
- Some error messages did not match the No PDF design.
- In the "About goods or services" form, if the "description" field is submitted with a value over the maximum amount and a "final destination" country is provided, the submitted country would not be pre-populated with the submitted country.a
- Update various content strings.
- Update `completeAndSubmitAboutGoodsOrServicesForm` cypress command to accept a custom "description" value.
- Update "about goods or services" validation E2E test to include:
- A test for maximum "description" characters.
- A test that all fields have pre-populated values when the "description" field is submitted with a value over the maximum amount. …
=> fix(EMS-2543-2571-2607-2608-2611): No PDF - copy fixes, country pre-population issue

e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js, package-lock.json, package.json, src/ui/package-lock.json, src/ui/package.json, src/ui/server/controllers/insurance/policy/multiple-contract-policy/validation/rules/total-months-of-cover.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/validation/rules/total-months-of-cover.ts
This PR fixes an issue where the "Total months of cover" field of a no PDF application, would allow decimal points and cause a "problem with service" issue.
- Add a validation rule so that "Total months of cover" cannot be submitted with decimal points.
- Bump depedencies.
- Minor destructuring improvements.
=> fix(EMS-2556-2570): No PDF - Multiple contract policy - Total months of cover - decimal places

e2e-tests/commands/insurance/complete-and-submit-pre-credit-period-form.js, e2e-tests/commands/insurance/complete-pre-credit-period-form.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js, e2e-tests/insurance/cypress/support/application/policy/index.js, src/ui/server/controllers/insurance/policy/pre-credit-period/save-and-back/index.test.ts, src/ui/server/controllers/insurance/policy/pre-credit-period/save-and-back/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/policy/index.test.ts, src/ui/server/routes/insurance/policy/index.ts
This PR adds "save and go back" functionality to the "Pre-credit period" form.
- Create a new cypress command to complete the "Pre-credit period" form, `completePreCreditPeriodForm`.
- Simplify `completeAndSubmitPreCreditPeriodForm`.
- Add new "save and go back" route and controller.
- Address TODO comment in a "broker" E2E test, not that we have "save and back" functionality.
- Fixed some typos.
=> feat(EMS-2558): No PDF - Policy - Pre-credit period - Save and back

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js, src/ui/server/controllers/insurance/business/company-details/index.test.ts, src/ui/server/controllers/insurance/business/company-details/index.ts
This PR fixes some issues where, if a user is in one of the following summary lists:
- "Insurance - Check your answers - Your business".
- "Your business - Check your answers".
..and then, when clicking the "change" link to get back to the "Company details" form - the form would always redirect to the "alternative trading address" if the "alternative trading address" answer is "yes".
This should only happen when the "alternative trading address" answer is "yes" _and a full address is not provided._
- Update the "company details" POST controller to determine if a "trading address" field is required.
- Update the logic for "redirect to check/change" routes to include the "trading address" field check.
- Improve E2E test coverage
- Improve the POST redirection documentation.
=> fix(EMS-2557): No PDF - Your business - check/change business trading address

e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js, src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts, src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts, src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts, src/ui/server/controllers/insurance/policy/save-data/policy/index.ts
This PR updates the "save data" functionality for the "policy" section of a No PDF application, so that if the "Pre-credit period" yes/no field is changed from yes to no, the previously provided description (`CREDIT_PERIOD_WITH_BUYER`) is wiped.
- Remove `stripEmptyFormFields` from `save.policy` function.
- Update policy `mapSubmittedData` function to wipe `CREDIT_PERIOD_WITH_BUYER` if `NEED_PRE_CREDIT_PERIOD` is "no"/"false".
- Add E2E test.
- Documentation improvements.
=> feat(EMS-2558): No PDF - Policy - Pre-credit period - wipe a field if answer is changed

e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/index.js, e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js, src/api/constants/supported-currencies/index.ts, src/api/test-mocks/mock-currencies.ts, src/ui/server/constants/supported-currencies.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/index.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/index.test.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.test.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.ts, src/ui/server/test-mocks/index.ts, src/ui/server/test-mocks/mock-currencies.ts
This PR updates the "currency as select options" mapping so that they are specifically ordered as per design, instead of being alphabetical.
Have also fixed/updated various copy to align with the No PDF design.
- Update mock and supported currencies fixtures and constants to export currency codes e.g `GBP`, `EUR` etc.
- Create a new UI helper function to map and specifically sort currencies for a select drop down, `mapAndSortCurrencies`.
- Update `mapCurrenciesAsSelectOptions` to consume new `mapAndSortCurrencies`.
- Rename some E2E test descriptions.
- Documentation improvements.
=> fix(EMS-2538-2654-2658): No PDF - Get a quote currencies ordering, content updates

e2e-tests/commands/insurance/date-field.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js, src/ui/server/helpers/date/get-date-fields-from-timestamp/index.test.ts, src/ui/server/helpers/date/get-days-in-a-month/index.test.ts, src/ui/server/helpers/date/get-days-in-a-month/index.ts, src/ui/server/shared-validation/date/index.test.ts, src/ui/server/shared-validation/date/index.ts, src/ui/server/shared-validation/date/valid-format/index.test.ts, src/ui/server/shared-validation/date/valid-format/index.ts, src/ui/types/index.d.ts, src/ui/types/validation-errors.d.ts
This PR fixes an issue where date validation (currently only used in single/contract policy forms), would transform an invalid day into a valid date. E.g, "**31/02/2024**" would be transformed to "**02/03/2024**".
Now, a validation error is shown if a day is greater than the the total amount of days in the provided month.
- Add new helper function `getDaysInAMonth`.
- Extract some shared date rules into its own function, `validDateFormatRules`.
- Add a validation rule so that if the provided day is greater than the total amount of days in the month, an error will be returned.
- Add E2E  test coverage.
- Remove some unnecessary UI unit tests.
- Extract a type into the `/types` directory.
=> fix(EMS-2566-2657): No PDF - Date validation - Return an error if days is over days in a month

e2e-tests/commands/insurance/check-your-business-summary-list.js, e2e-tests/content-strings/fields/insurance/business/index.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js, src/api/.keystone/config.js, src/api/content-strings/fields/insurance/your-business/index.ts, src/ui/server/content-strings/fields/insurance/your-business/index.ts, src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts, src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
This PR updates some copy and formatting for the "Your business" summary list, in "Check your answers" pages of a no PDF application.
- Update the `ESTIMATED_ANNUAL_TURNOVER` field value to be formatted correctly. (Previously eg `£1500`, now `£1,500`).
- Minor destructuring improvements.
=> style(EMS-2464): No PDF - Your business - Summary list updates

src/ui/templates/components/form-buttons.njk, src/ui/templates/components/single-radio.njk, src/ui/templates/insurance/declarations/anti-bribery.njk, src/ui/templates/insurance/declarations/confidentiality.njk, src/ui/templates/insurance/export-contract/about-goods-or-services.njk, src/ui/templates/insurance/export-contract/check-your-answers.njk, src/ui/templates/insurance/policy/broker.njk, src/ui/templates/insurance/policy/check-your-answers.njk, src/ui/templates/insurance/policy/different-name-on-policy.njk, src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk, src/ui/templates/insurance/policy/multiple-contract-policy.njk, src/ui/templates/insurance/policy/name-on-policy.njk, src/ui/templates/insurance/policy/single-contract-policy-total-contract-value.njk, src/ui/templates/insurance/policy/single-contract-policy.njk, src/ui/templates/insurance/policy/type-of-policy.njk, src/ui/templates/insurance/your-business/alternative-trading-address.njk, src/ui/templates/insurance/your-business/check-your-answers.njk, src/ui/templates/insurance/your-business/companies_house_number.njk, src/ui/templates/insurance/your-business/company-details.njk, src/ui/templates/insurance/your-business/contact.njk, src/ui/templates/insurance/your-business/nature-of-your-business.njk, src/ui/templates/insurance/your-business/turnover.njk, src/ui/templates/insurance/your-buyer/check-your-answers.njk, src/ui/templates/insurance/your-buyer/company-or-organisation.njk, src/ui/templates/insurance/your-buyer/trading-history.njk, src/ui/templates/shared-pages/declaration.njk
This PR adds a new "form buttons" component to be used in any form that has a "continue" and an optional "save and back" button.
This ensures that every instance of such buttons is DRY and consistent. This will also save us some time as we setup new forms.
- Create new component.
- Conditionally render custom submit button text.
- Conditionally render the "save and back" button as a link, if a `saveAndBackAsALink` param is passed.
- Update all nunjucks templates and partials/components that have submit and "save and back" buttons.
List any additional fixes or improvements.
=> chore(EMS-2455): DRY "form buttons" nunjucks component

e2e-tests/constants/field-ids/insurance/policy/index.js, e2e-tests/constants/routes/insurance/policy.js, e2e-tests/content-strings/fields/insurance/policy/index.js, e2e-tests/content-strings/pages/insurance/policy/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js, e2e-tests/pages/insurance/policy/broker.js, src/api/.keystone/config.js, src/api/constants/field-ids/insurance/policy/index.ts, src/api/schema.graphql, src/ui/server/constants/field-ids/insurance/policy/index.ts, src/ui/server/constants/routes/insurance/policy.ts, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/server/content-strings/pages/insurance/policy/index.ts, src/ui/server/controllers/insurance/policy/another-company/index.test.ts, src/ui/server/controllers/insurance/policy/another-company/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/policy/index.test.ts, src/ui/server/routes/insurance/policy/index.ts
This PR sets up a new page/route for an "Another company" form as part of a No PDF's policy section.
Note, this is not setup with the flow, this is simply setting up the page.
- Setup new route, controller, content strings.
- Add E2E test.
- Align policy field content strings between UI and E2E tests.
- Remove some unnecessary `LABEL` definition for the `CREDIT_PERIOD_WITH_BUYER` field (the form uses `PAGE_TITLE` since it's a single field form.
- update some "broker" cypress selector naming conventions to be camelCase.
=> feat(EMS-2583): No PDF - Policy - Another company - Page setup

e2e-tests/commands/insurance/assert-alternative-currency-form.js, e2e-tests/fixtures/currencies.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js, src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts, src/api/custom-resolvers/queries/get-APIM-currencies/index.ts, src/api/custom-schema/type-defs.ts, src/api/helpers/map-currencies/index.test.ts, src/api/helpers/map-currencies/index.ts, src/api/schema.graphql, src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts, src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts, src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts, src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts, src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts, src/ui/server/graphql/queries/APIM/currencies.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.test.ts, src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.ts, src/ui/server/test-mocks/mock-currencies.ts
This PR returns alternative currencies instead of all currencies from API.  Removes supported currencies from alternative currencies
- Added `getAlternativeCurrencies` to remove currencies not in SUPPORTED_CURRENCIES
- Updated tests
- Updated all instances of allCurrencies to alternativeCurrencies
=> chore(EMS-2674): No PDF - Return alternativeCurrencies from getCurrencies() 

e2e-tests/commands/insurance/change-policy-type-to-multiple-and-submit-contract-policy-form.js, e2e-tests/constants/routes/insurance/policy.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js, e2e-tests/insurance/cypress/support/application/policy/index.js, src/api/.keystone/config.js, src/ui/server/constants/routes/insurance/policy.ts, src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts, src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts, src/ui/server/helpers/sanitise-data/index.test.ts, src/ui/server/helpers/sanitise-data/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/policy/index.test.ts, src/ui/server/routes/insurance/policy/index.ts
This PR updates the ability to change a "single contract policy" to a "multiple contract policy", so that when this occurs, a 3rd multiple policy related form is required to be completed before a user is redirected back to a "check or change your answers" page.
This can occur from:
- Policy - check your answers
- Insurance - check "policy" answers.
As part of this PR, have also update some policy data mapping so that if a policy is changed from single to multiple (or vice versa), single or multiple specific fields will be wiped.
- Add "check and change" UI routes for the `EXPORT_VALUE` (multiple policy specific field).
- Update "multiple contract policy" POST controller to redirect to `EXPORT_VALUE` if the route is a "change" or "check and change" route.
- Update the policy …
=> feat(EMS-2535): No PDF - Policy - Change from single to multiple - enhancements

src/api/.keystone/config.js, src/api/constants/external-apis.ts, src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.test.ts, src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts, src/api/helpers/filter-cis-entries/index.test.ts, src/api/helpers/filter-cis-entries/index.ts, src/api/helpers/map-CIS-countries/index.test.ts, src/api/helpers/map-CIS-countries/index.ts, src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts, src/api/helpers/map-currencies/index.test.ts, src/api/helpers/map-currencies/index.ts, src/api/integrations/APIM/index.test.ts, src/api/test-mocks/index.ts
This PR updates the API's currency mapping to filter out the "gold" currency returned from APIM. Gold is not a valid/supported currency for No PDF EXIP application.
- Create `INVALID_CURRENCIES` constant.
- Create new helper function to filter out invalid countries and currencies received by APIM, `filterCisEntries`, removing the need for the `filterCisCountries` function.
- Update `mapCurrencies` to use `filterCisEntries`.
- Improve countries and currencies test mock imports.
=> chore(EMS-2719): No PDF - Currencies - Filter out "gold" currency from APIM

e2e-tests/commands/shared-commands/assertions/assert-different-name-on-policy-field-values.js, e2e-tests/commands/shared-commands/assertions/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-different-name-to-same-name-then-back-to-different-name.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/different-name-on-policy-page.spec.js
This PR ensures that the "different name on policy" feature of a no PDF application wipes the "different name" fields in the following scenario:
1) Submit "different name" as yes.
2) Submit different contact details.
3) Change and submit "different name" as no.
4) Go back, change and submit "different name" as yes.
- Create new DRY cypress command to assert the "different name on policy" field values, `assertDifferentNameOnPolicyFieldValues`.
- Minor test description improvements.
=> chore(EMS-2642): No PDF - Policy - Different name - Improve E2E test coverage

database/exip.sql, e2e-tests/content-strings/error-messages.js, src/api/.keystone/config.js, src/api/schema.prisma, src/api/schema.ts, src/ui/server/content-strings/error-messages.ts
This PR fixes 2x issues in the "Different name on policy" form where:
- The email validation error messages was incorrect.
- The "position" field had an invalid `varchar`.
- Update error message content strings.
- Update DB dump.
=> fix(EMS-2667-2778): No PDF - Policy - Different name on policy - validation

e2e-tests/content-strings/error-messages.js, e2e-tests/content-strings/fields/insurance/policy/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js, src/ui/server/content-strings/error-messages.ts, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/position.test.ts, src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/position.ts, src/ui/templates/insurance/policy/different-name-on-policy.njk
This PR fixes/adds some missing validation rules in the "Different name on policy" form.
- Add `MAXIMUM` definition for the "position" field.
- Update the "position" validation to call/consume `alphaCharactersAndMaxLengthValidation` instead of `emptyFieldValidation`.
- Fix a styling (form input width) issue in the "Different name on policy" form.
=> fix(EMS-2786-2789): No PDF - Policy - Different name on policy - Form validation

e2e-tests/constants/routes/insurance/policy.js, e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-address-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-name-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/connection-to-the-buyer-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/validation/connection-to-the-buyer-validation.spec.js, e2e-tests/pages/your-business/company-details/companyDetails.js, src/ui/server/constants/routes/insurance/policy.ts, src/ui/server/controllers/insurance/business/company-details/index.test.ts, src/ui/server/controllers/insurance/business/company-details/index.ts, src/ui/server/controllers/insurance/business/credit-control/index.test.ts, src/ui/server/controllers/insurance/business/credit-control/index.ts, src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts, src/ui/server/controllers/insurance/policy/other-company-details/index.ts, src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts, src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts, src/ui/templates/insurance/your-business/company-details.njk
This PR fixes some minor issues where some "yes/no" radios were in the incorrect order and the "Other company details" page had a missing "Save and back" button.
- Add `OTHER_COMPANY_DETAILS_SAVE_AND_BACK` route constant.
- Create `HTML_FLAGS` for the "Company details" and "Credit control" controllers, update "Company details" nunjucks template.
- Update "Other company details" controller to pass a `SAVE_AND_BACK_URL` via `pageVariables`.
- Update some unit test ordering.
=> fix(EMS-2809-2810-2811-2821): No PDF - Radio layout/alignment issues, missing "save and back" button

e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-validation.spec.js, src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.test.ts, src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.ts, src/ui/templates/insurance/your-buyer/trading-history.njk
This PR fixes the radio order for trading-history and prior-trading-history page
* Added to HTML flags or to nunjucks for radio order
* Added and updated tests
=> fix(EMS-2808-2812): No PDF - Buyer - Radio order for trading history and prior trading history

e2e-tests/commands/insurance/complete-and-submit-broker-details-form.js, e2e-tests/commands/insurance/complete-broker-details-form.js, e2e-tests/constants/examples/full-address-examples.js, e2e-tests/constants/examples/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address-multiple-lines.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/save-and-back.spec.js, e2e-tests/pages/shared/index.js, src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts, src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts, src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts, src/ui/server/helpers/mappings/map-textarea-fields/index.ts, src/ui/server/helpers/summary-lists/generate-address-object/index.ts, src/ui/templates/insurance/policy/broker-confirm-address.njk
This PR updates the "Confirm broker address" functionality of a no PDF application so that if a "full broker address" (textarea) is submitted with line breaks, it will be played back to the user exactly as it was entered.
- Update `completeBrokerDetailsForm` and `completeAndSubmitBrokerDetailsForm` cypress commands to accept custom values.
- Create `FULL_ADDRESS` E2E constants/examples.
- Add E2E test for submitting and playing back an address with line breaks in the "Confirm broker address" page.
- Update `mapApplicationToFormFields` to map `FULL_ADDRESS`.
- Update "Confirm broker address" GET controller to consume/pass `mapApplicationToFormFields`.
- Update "Confirm broker address" nunjucks component to render the inset text value as raw (safe) HTML.
=> feat(EMS-2854): No PDF - Policy - Confirm broker address - Multi line support

.github/workflows/test.yml
This buyer splits E2E your-buyer tests on different runners
* Added different folders to test.yml for your-buyer
=> chore(test): Split up "Your buyer" E2E tests

e2e-tests/constants/routes/insurance/policy.js, src/ui/server/constants/routes/insurance/policy.ts
This PR changes the "insurance-policy" route to be "policy"
* Changed constants to `policy` instead of `insurance-policy`
=> feat(EMS-2874): No PDF - Policy - Update root URL

e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js, e2e-tests/constants/routes/insurance/policy.js, e2e-tests/content-strings/pages/insurance/your-buyer/index.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/root/your-buyer-root.spec.js, src/ui/server/constants/routes/insurance/policy.ts, src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
This PR fixes the wrong content on the Your Buyer start page and the incorrect routes for policy
* FIxed start page content for your buyer
* Fixed Policy - `Name on policy` and `different name on policy` routes - to `contact` and `contact-details`
=> fix(EMS-3045-3046): No PDF - Policy/Your Buyer - Content and route bugs

e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-trading-history-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-trading-history.spec.js, src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.test.ts, src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.ts, src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts, src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.ts
This PR fixes an issue where `TRADING_HISTORY` fields were not wiped if an answer is changed from yes to no.
* Added to `mapSubmittedData` to wipe all trading history fields if `TRADED_WITH_BUYER` is false
* Added fields to `NULL_OR_EMPTY_STRING_FIELDS`
=> fix(EMS-2969): No PDF - Your Buyer - Check your answers - Trading history fields

e2e-tests/commands/insurance/complete-and-submit-loss-payee-details-form.js, e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-policy-loss-payee-details.spec.js, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.test.ts, src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.ts, src/ui/server/helpers/mappings/map-name-fields/index.test.ts, src/ui/server/helpers/mappings/map-name-fields/index.ts
This PR fixes an issue where the wrong validation was used for the name field on loss payee details
* Used providedAndMaxLength validation for name field
=> fix(EMS-3079): No PDF - Policy - Loss Payee details - Wrong name validation

e2e-tests/commands/insurance/complete-and-submit-private-market-form.js, e2e-tests/commands/insurance/complete-export-contract-section.js, e2e-tests/constants/routes/insurance/export-contract.js, e2e-tests/content-strings/error-messages.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js, src/ui/server/constants/routes/insurance/export-contract.ts, src/ui/server/content-strings/error-messages.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.ts, src/ui/server/test-mocks/mock-application.ts
This PR updates the "Private market" POST controller so that the `ATTEMPTED` field must be provided. If not, validation errors are rendered.
- Update `completeAndSubmitPrivateMarketForm` cypress command to conditionallly submit the form with a yes or no answer.
- Create new `DECLINED_BY_PRIVATE_MARKET` route constant.
- Update E2E test coverage.
- Update the "Private market" POST controller to:
- Check for validation errors.
- Redirect to `DECLINED_BY_PRIVATE_MARKET` if the provided answer is "yes".
- Update UI test mocks.
=> feat(EMS-2938): No PDF - Export contract - Private market - Form validation

e2e-tests/commands/insurance/complete-and-submit-private-market-form.js, e2e-tests/commands/insurance/complete-private-market-form.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/save-and-back.spec.js, e2e-tests/insurance/cypress/support/application/export-contract/index.js, src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.ts, src/ui/server/controllers/insurance/export-contract/private-market/save-and-back/index.test.ts, src/ui/server/controllers/insurance/export-contract/private-market/save-and-back/index.ts, src/ui/server/routes/insurance/export-contract/index.test.ts, src/ui/server/routes/insurance/export-contract/index.ts, src/ui/server/routes/insurance/index.test.ts
This PR adds "save and back" functionality to the "Private market" form, in the "Export contract" section of a no PDF application.
- Create new `completePrivateMarketForm` cypress command.
- Update UI GET controller to generate a real `SAVE_AND_BACK_URL`.
- Create a new UI POST route and controller.
- Simplify an E2E test's `FIELD_IDS` imports/destructuring.
=> feat(EMS-2936): No PDF - Export contract - Private market - Save and back

e2e-tests/commands/insurance/assert-currency-form-fields.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-single-policy-type.spec.js, e2e-tests/shared-test-assertions/currency-form-fields/form-submission.js, src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts, src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts, src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts, src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts, src/ui/server/shared-validation/date/index.test.ts, src/ui/server/test-mocks/mock-application.ts
This PR fixes an issue in the single and multiple contract policy forms where, if the "alternative currency" radio option is selected, but there are other validation errors, the "alternative currency" radio option  would not be pre-selected.
- Update the DRY, shared E2E currency form field assertions (`assertCurrencyFormFields`), to check that the "alternative currency" radio option is checked when there are validation errors.
- Update single and multiple contract policy POST controllers to conditionally use the `POLICY_CURRENCY_CODE` from the submtited values during validation errors.
- Remove some unnecessary `submittedValues` properties  from 2x GET controllers.
- Fix a UI date validation unit test that was failing due to the current time of year.
- Fix an E2E test that was failing due …
=> fix(EMS-3078): No PDF - Single/multiple contract policy - Alternative currency validation - Pre-selected radio

e2e-tests/constants/routes/insurance/policy/loss-payee.js, src/ui/server/constants/routes/insurance/policy/loss-payee.ts
This PR fixes an incorrect URL for the "loss payee - international financial details"  route in a No PDF application.
- Before: `/policy/loss-payee/loss-payee/international-bank-details`
- After: `/policy/loss-payee-international-bank-details`
- Update route constants.
=> fix(EMS-3081): No PDF - Policy - Loss payee details URL

.github/workflows/test.yml, README.md
GitHub Actions has stoped supporting `docker-compose` as per their migration plan https://github.com/actions/runner-images/issues/9557.
- Upgrade to docker `v2` syntax.
=> chore(tech): Upgrade docker syntax to V2

src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.test.ts, src/ui/server/controllers/insurance/account/create/confirm-email/index.test.ts, src/ui/server/controllers/insurance/account/create/resend-confirm-email/index.test.ts, src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/index.test.ts, src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.test.ts, src/ui/server/controllers/insurance/check-your-answers/save-data/index.test.ts, src/ui/server/controllers/insurance/dashboard/index.test.ts, src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts, src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts, src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts, src/ui/server/controllers/insurance/declarations/save-data/index.test.ts, src/ui/server/controllers/insurance/export-contract/save-data/export-contract/index.test.ts, src/ui/server/controllers/insurance/export-contract/save-data/private-market/index.test.ts, src/ui/server/controllers/insurance/policy/save-data/broker/index.api-error.test.ts, src/ui/server/controllers/insurance/policy/save-data/jointly-insured-party/index.api-error.test.ts, src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.api-error.test.ts, src/ui/server/controllers/insurance/policy/save-data/policy-contact/index.test.ts, src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts, src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.test.ts, src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts, src/ui/server/controllers/insurance/your-buyer/save-data/buyer/index.test.ts
This PR fixes some issues reported by SonarCloud, where there are too many nested describe/it blocks in some API error handling unit tests.
For example:
**Before**
```js
describe('api error handling', () => {
describe('update declarations call', () => {
describe('when there is an error', () => {
beforeEach(() => {
// ...
});
it('should throw an error', async () => {
// ...
});
});
});
});
```
**After**
```js
describe('when there is an error calling the API', () => {
beforeAll(() => {
// ...
});
it('should throw an error', async () => {
// ...
});
});
```
- Simplify all API error handling unit tests in the UI's `save-data` directories.
- Ensure the said describe blocks are using `beforeAll` instead of `beforeEach`, since there is only 1 test.
- Remove some unnecessary initial declarations …
=> chore(sonarCloud): Simplify UI unit test error handling describe blocks

e2e-tests/commands/insurance/check-export-contract-summary-list.js, e2e-tests/fixtures/application.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-about-goods-or-services.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-how-will-you-get-paid-total-contract-value-over-threshold.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-how-will-you-get-paid.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/save-and-back.spec.js, src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts, src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.ts, src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts, src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.test.ts, src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.ts, src/ui/server/routes/insurance/export-contract/index.test.ts, src/ui/server/routes/insurance/export-contract/index.ts, src/ui/server/routes/insurance/index.test.ts, src/ui/server/test-mocks/index.ts, src/ui/server/test-mocks/mock-application.ts
This PR adds the ability to change a previously provided answer for the `PAYMENT_TERMS_DESCRIPTION` field, via the "check your answers" summary list.
- Update E2E mock `PAYMENT_TERMS_DESCRIPTION` to use `MULTI_LINE_STRING`.
- Update `checkExportContractSummaryList` and all "How will you get paid" E2E tests to assert the `PAYMENT_TERMS_DESCRIPTION` as a multi line string.
- Add E2E test coverage for changing the `PAYMENT_TERMS_DESCRIPTION` when:
- The application's total contract value is below the threshold.
- The application's total contract value is above the threshold (the user journey differes if so).
- Update "How will you get paid" POST controller to redirect to `PRIVATE_MARKET_CHANGE` or `CHECK_YOUR_ANSWERS`, if the application's total contract value is over the threshold.
- Update …
=> feat(EMS-3089-3112): No PDF - Export contract - Check/change answers - Payment terms description

src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts, src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts, src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts, src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts, src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent-details/index.ts, src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts, src/ui/server/controllers/insurance/policy/other-company-details/index.ts, src/ui/server/controllers/quote/buyer-country/index.test.ts, src/ui/server/controllers/quote/buyer-country/index.ts
This PR updates all UI controllers mapping of previously submitted countries.
Instead of this (simplified example):
```js
if (objectHasProperty(obj[FIELD_ID])) {
let mappedCountries;
if (countryValue) {
mappedCountries = mapCountries(countries, countryValue.isoCode);
} else {
mappedCountries = mapCountries(countries);
}
```
We can just do this instead, because `mapCountries` handles an undefined param:
```js
const mappedCountries = mapCountries(countries, obj[FIELD_ID]?.isoCode);
```
- Update all UI controllers with country mappings, to use the simplified example above.
- Simplify all UI controller unit tests.
=> chore(EMS-3158): No PDF - Simplify previously submitted country mappings

e2e-tests/content-strings/fields/insurance/export-contract/index.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-change-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-change-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js, src/ui/server/content-strings/fields/insurance/export-contract/index.ts, src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.ts, src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-fixed-sum-html.njk
This PR updates the "Agent charges - alternative currency" functionality in the "Export contract" section of a No PDF application so that the "Fixed sum amount" label and input renders a dynamic label and prefix, depending on if the selected currency is an "alternative" currency or not.
- Update field content strings.
- Add and update E2E tests.
- Update the `AGENT_CHARGES` GET and POST controller to render a dynamic `FIXED_SUM_AMOUNT` label.
- Update the `AGENT_CHARGES` GET and POST controller to render a dynamic `FIXED_SUM_AMOUNT` label.
- Add a missing `labelClasses` nunjucks attribute.
- Fix some typos.
- Documentation improvements.
- Simplify some `DYNAMIC_PAGE_TITLE` instances.
=> feat(EMS-3186-3188): No PDF - Export contract - Agent charges - Alternative currency - Prefixes, dynamic label

e2e-tests/commands/keyboard-input.js, e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js, e2e-tests/commands/shared-commands/assertions/check-email-field-rendering.js, e2e-tests/commands/shared-commands/assertions/check-type-attribute.js, e2e-tests/commands/shared-commands/assertions/index.js, e2e-tests/commands/shared-commands/form/click-all-sections-link.js, e2e-tests/commands/shared-commands/form/index.js, e2e-tests/commands/shared-commands/form/submit-and-assert-field-errors.js, e2e-tests/content-strings/error-messages.js, e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details.spec.js, e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/account-password-reset.spec.js, e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js, e2e-tests/shared-test-assertions/email-field-validation/index.js, src/ui/server/content-strings/error-messages.ts, src/ui/templates/insurance/account/create/your-details.njk, src/ui/templates/insurance/account/password-reset/password-reset.njk, src/ui/templates/insurance/account/sign-in/sign-in.njk, src/ui/templates/insurance/export-contract/agent-details.njk, src/ui/templates/insurance/policy/broker-details.njk, src/ui/templates/insurance/policy/check-your-answers.njk, src/ui/templates/insurance/policy/different-name-on-policy.njk, src/ui/templates/insurance/your-business/check-your-answers.njk, src/ui/templates/insurance/your-business/contact.njk
This PR fixes various issues where:
- Email fields would not render with an `email` type attribute.
- An error message had an incorrect `MAXIMUM_CHARACTERS` reference.
- The "Policy - Check your answers" was unnecessarily rendering an additional button.
- The Account - password reset "email" field was rendering as a password field.
- The "Export contract - agent details" autocomplete field was missing a container class name and therefore a red border was missing during validation errors.
- Create new `checkEmailFieldRendering` cypress command.
- Create new `checkTypeAttribute` cypress command.
- Update all E2E tests with email assertions to use `checkEmailFieldRendering` cypress command.
- Update `keyboardInput` cypress command to handle email …
=> fix(EMS-3129-3184-3187-3242): No PDF - Visual design issues - Email fields, content, unnecessary button, styling

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-private-market-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-private-market-yes-to-no.spec.js, src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts, src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts, src/ui/server/controllers/insurance/export-contract/private-market/index.ts
This PR adds the ability to change the "attempted" field in the "Private market" form via the "Check your answers - Export contract" page of a No PDF application.
- Changing the `ATTEMPTED` field from "yes" to "no".
- Changing the `ATTEMPTED` field from "no" to "yes".
- Update `PRIVATE_MARKET` POST controller redirects.
- Update `DECLINED_BY_PRIVATE_MARKET` POST controller redirects.
=> feat(EMS-3231): No PDF - Change your answers - Export contract - Private market

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-declined-description.spec.js, src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts, src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.ts
This PR adds the ability to change the "description" field in the "Declined by private market" form via the "Check your answers - Export contract" page of a No PDF application.
- Update `DECLINED_BY_PRIVATE_MARKET POST` controller redirects.
=> feat(EMS-3232): No PDF - Change your answers - Export contract - Declined by private market 

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-details.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-details.spec.js, src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
This PR adds the ability to change all fields in the "Agent details" form via the "Check your answers - Export contract" page of a No PDF application.
- Update `AGENT_DETAILS` POST controller redirects.
- Update previously created "Change agent details answers" test to correctly assert a new `FULL_ADDRESS` answer.
=> feat(EMS-3235): No PDF - Export contract - Change your answers - Agent details

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-yes-to-no.spec.js, src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent-details/index.ts, src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent-service/index.ts, src/ui/server/controllers/insurance/export-contract/agent/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent/index.ts, src/ui/server/test-mocks/index.ts, src/ui/server/test-mocks/mock-application.ts
This PR adds the ability to change the "Using agent" field in the "Agent" form via the "Check your answers - Export contract" page of a No PDF application.
- Changing the `ATTEMPTED` field from "yes" to "no".
- Changing the `ATTEMPTED` field from "no" to "yes".
- Update `AGENT_DETAILS` POST controller to redirect to `AGENT_SERVICE_CHECK_AND_CHANGE`, if the URL is a "check and change" route and `AGENT_SERVICE` data is not available.
- Update `AGENT_DETAILS` POST controller to redirect to `CHECK_AND_CHANGE_ROUTE`, if the URL is a "check and change" route and `AGENT_SERVICE` data is available.
- Update `AGENT_SERVICE` POST controller to redirect to `AGENT_CHARGES_CHECK_AND_CHANGE`, if the URL is a "check and change" route and the agent is charging.
- Update …
=> feat(EMS-3231): No PDF - Change your answers - Export contract - Agent

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-fixed-sum-amount.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-fixed-sum-to-percentage.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-payable-country.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-percentage-charge.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-percentage-to-fixed-sum.spec.js, src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
This PR adds the ability to change all fields in the "Agent charges" form via the "Check your answers - Export contract" page of a No PDF application.
- Add E2E test coverage for: 
- Fixed sum method - changing the `FIXED_SUM_AMOUNT` field.
- Fixed sum method - change to Percentage method.
- Changing the `PAYABLE_COUNTRY_CODE` field.
- Percentage method - changing the `PERCENTAGE_CHARGE` field.
- Percentage method - change to Fixed sum method.
=> feat(EMS-3237): No PDF - Change your answers - Export contract - Agent charges

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-details.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-details.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-no-to-yes.spec.js, src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts, src/ui/server/controllers/insurance/export-contract/agent-details/index.ts, src/ui/server/test-mocks/index.ts, src/ui/server/test-mocks/mock-application.ts
This PR updates the user flow when in the "Agent details" form via the "Check your answers - Export contract" page of a No PDF application; So that a user is always redirected to "Agent service" after submitting "Agent details"
- Update `AGENT_DETAILS` POST controller redirect logic.
- Remove UI `mockApplicationAgentServiceEmpty` mock.
=> fix(EMS-3241-3235): No PDF - Change your answers - Export contract - Agent details - Redirect logic

e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
This PR updates the E2E test coverage for the "Agent details" form, in the Export contract section of a No PDF application.
A bug was raised where the `COUNTRY_CODE` field in this page would not render a previously submitted value, if other fields have errors.
Unable to replicate this, but have added E2E test coverage for all fields, to ensure that every field retains a previously submitted value, when there are validation errors for other fields.
- Update E2E test coverage.
=> chore(EMS-3191): No PDF - Export contract - Agent details - Validation - Improve E2E test coverage

e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js, src/ui/templates/components/accessible-autocomplete-select.njk, src/ui/templates/insurance/export-contract/agent-charges.njk
This PR fixes an issue in the "Export - contract - Agent charges" form as part of the No PDF application where, when a validation error renders, the error text would display across 2 lines.
- Update the Accessible autocomplete nunjucks component to render an optional input container class name.
- Update the Agent charges nunjucks rows and classes.
- Remove a `assertExpectedValue: false` flag from an E2E test (EMS-3195).
=> fix(EMS-3195-3238): No PDF - Export contract - Agent charges - Country input - Layout issue

e2e-tests/content-strings/links.js, e2e-tests/content-strings/pages/insurance/application-submitted/index.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-name.spec.js, src/ui/server/content-strings/links.ts, src/ui/server/content-strings/pages/insurance/application-submitted/index.ts, src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.test.ts, src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.ts
This PR fixes 2x issues where:
- The "Buyer - Organisation name" `ABOVE_MAXIMUM` error message had the invalid character count.
- The "Application submitted - give feedback" copy should say "Give us feedback", instead of "Give feedback".
- Update`COMPANY_OR_ORGANISATION.NAME` validation function.
=> fix(EMS-3125-3316): No PDF - Buyer - Organsation name error message, Application submitted page content

e2e-tests/fixtures/account-numbers.js, e2e-tests/fixtures/addresses.js, e2e-tests/fixtures/application.js, e2e-tests/fixtures/bic-swift-codes.js, e2e-tests/fixtures/ibans.js, e2e-tests/fixtures/sort-codes.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-international-name.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-international.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-uk-name.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-uk.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk.spec.js, src/ui/server/routes/insurance/index.test.ts, src/ui/server/routes/insurance/policy/loss-payee/index.test.ts, src/ui/server/routes/insurance/policy/loss-payee/index.ts
This PR adds "change your answers" functionality for "Policy - Loss payee", via the "Application - Check your answers" summary list in a No PDF application.
- Changing the "Loss payee - Name" field when financial details are UK.
- Changing the "Loss payee - Name" field when financial details are international.
- Changing the "Loss payee - Financal details - International" fields.
- Changing the "Loss payee - Financal details - UK" fields.
- Add "check and change" UI routes. 
- Introduce DRY E2E fixtures for:
- Account numbers.
- Addresses.
- BIC/Swift codes.
- IBANs.
- Sort codes.
=> feat(EMS-3285-3286): No PDF - Change your answers - Policy - Loss payee

e2e-tests/commands/shared-commands/assertions/check-phase-banner.js, src/ui/templates/partials/phase-banner.njk
This PR updates the phase banner to render "Beta" instead of "Alpha".
- Update the phase banner.
=> style(EMS-3363): No PDF - Update phase banner from "alpha" to "beta"

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-with-broker-summary-list.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-with-broker-summary-list.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
This PR adds E2E test coverage for changing the "Policy - Using broker" answers via the "Application - Check your answers - Policy" summary list.
- Add E2E test coverage for changing `USING_BROKER` from "no" to "yes" via: 
- "Application - Check your answers".
- "Policy - Check your answers".
- Simplify some `checkSummaryList.BROKER` instances to use destructuring.
=> chore(EMS-3287): No PDF - Change your answers - Policy - Broker - E2E tests

e2e-tests/insurance/cypress/e2e/journeys/application-submission/application-submitted.spec.js, e2e-tests/pages/insurance/applicationSubmitted.js, src/ui/templates/insurance/application-submitted.njk
This PR adds a missing full stop to the "give feedback" link/text, in the "Application submitted" page.
- Update nunjucks template.
- Add E2E test.
=> style(EMS-3316): No PDF - Application submitted - Feedback link - Add missing full stop

e2e-tests/commands/insurance/check-your-business-summary-list.js, e2e-tests/commands/insurance/complete-business-section.js, e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js, e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js, e2e-tests/fixtures/application.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-credit-control-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-credit-control-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-credit-control.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
This PR adds E2E tests for changing the `HAS_CREDIT_CONTROL` answer from "yes" to "no" and vice versa.
- Update various cypress commands to consume and pass a `hasCreditControlProcess` param.
- Add E2E tests for changing the `HAS_CREDIT_CONTROL` answer from "yes" to "no" and vice versa, via:
- "Application - Check your answers - Business".
- "Business - Check your answers".
- Simplify some field ID constnats imports/destructuring.
=> chore(EMS-3292): No PDF - Change your answers - Business - Credit control - E2E tests

e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details-validation-account-already-exists-verified-valid-password.spec.js, src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/already-verified/index.test.ts, src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/already-verified/index.ts
This PR fixes an issue where, when a user submits the "create account" form with valid credentials for an account that already exists, an error message would appear in both the email and password fields.
In this scenario, only one error should render in the email field.
- Update UI validation rule.
- Update E2E test.
=> fix(EMS-3459): no pdf - account creation - validation rules

e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount-alternative-currency.spec.js, src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts, src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
This PR fixes an issue where you could not change back to a standard currency after selecting an alternative currency on the Agent charges page
* Added to `mapSubmittedData `to set `ALTERNATIVE_CURRENCY_CODE` to null if it does not equal alternativeCurrencyCode
* Updated tests and e2e tests
=> fix(EMS-3399): no PDF - Export contract - Agent charges - Changing back to standard currency

src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-exporter-business/map-financial-year-end-date/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-exporter-business/map-financial-year-end-date/index.ts
This PR fixes an issue where the "financial year end date" format was not aligned with other XLSX date formats.
- Update `mapFinancialYearEndDate` to use a constant.
=> fix(EMS-3494): no pdf - application submission - XLSX date format

e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/buyer-conditions/submit-an-application-multiple-policy-type-buyer-minimal.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/buyer-conditions/submit-an-application-single-policy-type-buyer-minimal.spec.js, src/api/.keystone/config.js, src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-export-contract-conditions.test.ts, src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-total-contract-value-over-threshold.test.ts, src/api/constants/XLSX-CONFIG/index-single-contract-policy-export-contract-conditions.test.ts, src/api/constants/XLSX-CONFIG/index-single-contract-policy-total-contract-value-over-threshold.test.ts, src/api/constants/XLSX-CONFIG/index.ts, src/api/test-mocks/index.ts
This PR fixes an issue with the XLSX where the formatting index for the "declarations" title be incorrect due to a missing buyer condition.
- Update `XLSX_ROW_INDEXES` to:
- Increment 2x titles if `exporterIsConnectedWithBuyer` is true.
- Increment 2x titles if `totalContractValueOverThreshold` and `exporterHasPreviousCreditInsuranceWithBuyer` are true.
- Increment `AGENT_ADDRESS if `totalContractValueOverThreshold` is true.
- Update API test mocks.
- Add E2E tests for submitting an application (single and multiple contracts) with minimal buyer conditions.
=> fix(EMS-3508): no pdf - application submission - XLSX - buyer conditions

src/api/data-migration/version-1-to-version-2/README.md, src/api/data-migration/version-1-to-version-2/connect-to-database.ts, src/api/data-migration/version-1-to-version-2/create-new-account-status-relationships/index.ts, src/api/data-migration/version-1-to-version-2/get-all-buyer-contacts.ts, src/api/data-migration/version-1-to-version-2/get-all-buyer-relationships.ts, src/api/data-migration/version-1-to-version-2/get-all-buyer-trading-histories.ts, src/api/data-migration/version-1-to-version-2/index.ts, src/api/data-migration/version-1-to-version-2/update-applications/move-buyer-contact-fields.ts, src/api/data-migration/version-1-to-version-2/update-applications/move-buyer-relationship-fields.ts, src/api/data-migration/version-1-to-version-2/update-applications/move-buyer-trading-history-fields.ts, src/api/data-migration/version-1-to-version-2/update-buyers/index.ts, src/api/data-migration/version-1-to-version-2/update-buyers/update-buyer-relationship-ids.ts
This PR fixes 2x issues with "MVP to no-pdf" data migration, where the following issues would occur:
- `AccountStatus` relationship creations would fail.
- Various `Buyer` relationship creations would fail.
- Update the following functions to use raw SQL queries, instead of the KeystoneJS context API.
- `createNewAccountStatusRelationships`
- `moveBuyerContactFields`
- `moveBuyerTradingHistoryFields`
- `updateBuyers`
- `updateBuyerRelationshipIds`
- Create new buyer relationship functions:
- `getAllBuyerContacts`
- `getAllBuyerRelationships`
- `getAllBuyerTradingHistories`
- Update `README.md`.
- Update `connectToDatabase` function.
=> fix(EMS-3524): no pdf - data migration - account, buyer relationships

e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-fully-populated.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-fully-populated.spec.js, src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-final-destination/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-final-destination/index.ts, src/api/test-mocks/mock-application.ts
This PR fixes an issue where the "final destination" row in the XLSX would display as `[Object] [Object]`.
- Update `mapFinalDestination` XLSX mapping function.
- Update some E2E tests to include a `finalDestinationKnown` flag.
=> fix(EMS-3518): no pdf - application submission - XLSX - final destination

e2e-tests/commands/insurance/complete-export-contract-section.js, e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js, e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js, e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/buyer-conditions/traded-with-buyer/outstanding-payments-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/export-contract-conditions/submit-an-application-multiple-policy-type-using-an-agent-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/export-contract-conditions/submit-an-application-multiple-policy-type-using-an-agent-no-charges.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/export-contract-conditions/submit-an-application-multiple-policy-type-using-an-agent-percentage-method.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-fully-populated.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/export-contract-conditions/submit-an-application-single-policy-type-using-an-agent-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/export-contract-conditions/submit-an-application-single-policy-type-using-an-agent-no-charges.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/export-contract-conditions/submit-an-application-single-policy-type-using-an-agent-percentage-method.spec.js, e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-fully-populated.spec.js, src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/map-agent-charge-amount/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/map-agent-charge-amount/index.ts
This PR fixes 2x issues in the XLSX where:
- The "Agent country" field was rendering a country code instead of the country name.
- The "Agent charge amount" field was not rendering a currency code.
- Update `mapAgentChargeAmount` to:
- Consume a list of countries
- Call `getCountryByIsoCode`.
- Call `formatCurrency` with `FIXED_SUM_AMOUNT` as a number (it's saved as a string).
- Various application submission E2E test improvements.
=> fix(EMS-3508-3543): no pdf - application submission - XLSX - agent values

database/exip.sql, e2e-tests/constants/field-ids/insurance/index.js, src/api/.keystone/config.js, src/api/constants/field-ids/insurance/index.ts, src/api/data-migration/version-1-to-version-2/update-applications/add-application-migrated-field.ts, src/api/data-migration/version-1-to-version-2/update-applications/index.ts, src/api/data-migration/version-1-to-version-2/update-applications/update-application-migrated.ts, src/api/schema.graphql, src/api/schema.prisma, src/api/schema.ts, src/ui/server/constants/field-ids/insurance/index.ts, src/ui/server/graphql/queries/application.ts, src/ui/server/helpers/can-submit-application/index.ts, src/ui/server/helpers/flatten-application-data/index.test.ts, src/ui/server/helpers/flatten-application-data/index.ts, src/ui/server/helpers/required-fields/check-your-answers/index.test.ts, src/ui/server/helpers/required-fields/check-your-answers/index.ts, src/ui/server/helpers/required-fields/section-review/index.test.ts, src/ui/server/helpers/required-fields/section-review/index.ts, src/ui/server/test-mocks/mock-application.ts, src/ui/types/application.ts
This PR fixes an issue where, when an application is migrated from V1 (MVP) to V2 (No PDF), application submission would fail due to a missing `sectionReview.eligibility` flat being null.
- In MVP, there is no ability to "check your eligibility answers" and so the `sectionReview.eligibility` flag will always be null.
- In No PDF there is the ability to "check your eligibility answers" and so the flag is expected to be true before application submission. Otherwise, application submission will fail.
- Create a new `migratedV1toV2` flag.
- Update the data migration script to add the `migratedV1toV2` flag to the `Application` table.
- Update the data migration script to set all in progress applications to have a `migratedV1toV2` flag of `true`.
- Update the UI's "get application" GQL query to …
=> fix(EMS-3524): no pdf - data migration - eligibility section review condition

docker-compose.yml, package-lock.json, package.json, src/ui/package-lock.json, src/ui/package.json
This PR changes `default-authentication-plugin` from `mysql_native_password` to `caching_sha2_password`. 
`mysql_native_password` is deprecated in newer versions of MySQL and `caching_sha2_password` is now the default authentication method
`caching_sha2_password` is also more secure
* Changed to caching_sha2_password
- Dependency updates
=> chore(mysql-authentication): docker-compose - MySQL authentication

src/api/.keystone/config.js, src/api/custom-resolvers/mutations/update-company-post-data-migration/index.test.ts, src/api/custom-resolvers/mutations/update-company-post-data-migration/index.ts, src/api/helpers/create-company-sic-codes/index.test.ts, src/api/helpers/create-company-sic-codes/index.ts
This PR improves unit test coverage for error handling in the `updateCompanyPostDataMigration` GraphQL mutation.
- Add unit tests for when there is an error:
- Updating company SIC codes.
- Updating a company address.
- Update `updateCompanyPostDataMigration` to throw an error if there is no `registeredOfficeAddressId`.
- Simplify `createCompanySicCodes` helper function, improve unit test coverage.
=> chore(EMS-3550): no pdf - updateCompanyPostDataMigration unit test coverage

.github/workflows/infrastructure.yml
Ensure MySQL server on Azure version can be explicitly specified and matches the local docker tagged image version.
* Added `--version` flag to `az mysql flexible-server create` command, with value set to latest supported version by [Azure](https://learn.microsoft.com/en-us/azure/mysql/concepts-version-policy).
=> feat(EMS-3547): Azure MySQL Flexible server version set

e2e-tests/content-strings/links.js, src/ui/server/content-strings/links.ts
This PR fixes an issue where the `BRIBERY_ACT_2010_GUIDANCE` link went to an external "page not found".
* Updated the `BRIBERY_ACT_2010_GUIDANCE` link
=> fix(EMS-3604): no PDF - Anti-bribery code of conduct - Incorrect link

.cspell.json, .github/workflows/deployment.yml, .github/workflows/infrastructure.yml
Ensure Azure Front Door WAF security policy is also associated with custom domains.
* Added ` az afd security-policy update` CLI command to associate with:
* AFD endpoint
* AFD custom domains
* Minor deployment fix, ensure AZ CLI extension is pre-installed `rdbms-connect`.
* CSpell update
=> fix(iac): afd custom domains association

src/api/.keystone/config.js, src/api/constants/field-ids/insurance/index.ts, src/api/content-strings/XLSX.ts, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
This PR adds "Member of a group" and "Party to consortium" eligibility answers to the XLSX
* Updated API `FIELD_IDS` constants
* Added rows for `IS_PARTY_TO_CONSORTIUM` and `IS_MEMBER_OF_A_GROUP`
=> feat(EMS-3685): xlsx - Member of a group and party to consortium

.github/workflows/infrastructure.yml
When executing Azure KV creation CLI RBAC is now set as default authorisation method, thus ailing rest of the IaC script due to `Access Policy` usage.
* Set RBAC usage to false.
=> fix(iac): explicit RBAC authorisation to false for Azure KV

src/ui/server/constants/index.ts, src/ui/server/constants/quote.ts, src/ui/server/constants/service-name.ts
This PR addresses a TODO comment where 2x single line constants were stored in the index file.
- Move 2x single line constants into their own directories.
=> chore(EMS-3643): clean constants index

src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-relationship/index.ts
This PR fixes an issue where, when running data migration, the migration would error during declaration versioning updates, if there are any applications that have _not_ been submitted.
- Remove 2x unnecessary `await`'s from a `Promise.all()`.
- Add `await` to the `Promise.all()`.
=> fix(EMS-3633): data migration - declaration versioning

src/api/data-migration/version-1-to-version-2/README.md, src/api/data-migration/version-1-to-version-2/create-new-application-relationships/index.ts, src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/create-loss-payee-financial-uk.ts, src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/update-loss-payee-financial-international-vector.ts, src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/update-loss-payee-financial-uk-vector.ts
This PR fixes an issue where, when the data migration script is run, the international and UK financial database tables would have a NULL vector column.
Therefore, after migration, a user would not be able to complete the "Policy" section and the service would redirect to the "problem with service" page.
- Update `createNewApplicationRelationships` to update the vector columns _after_ other promises have resolved.
- Minor README improvement.
- Fix a typo.
- Add some logging/error handling to `updateLossPayeeFinancialInternationalVector` and `updateLossPayeeFinancialUkVector` so that if some particular data is empty, an error will be thrown.
=> fix(EMS-3633): data migration - financial vector columns

src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.ts, src/api/test-mocks/index.ts, src/api/types/application-types/index.ts, src/ui/server/controllers/insurance/check-your-answers/export-contract/index.test.ts, src/ui/server/controllers/insurance/check-your-answers/export-contract/index.ts, src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts, src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.ts, src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts, src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts, src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts, src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts, src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.test.ts, src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts, src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts, src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts, src/ui/server/helpers/required-fields/export-contract/index.test.ts, src/ui/server/helpers/required-fields/export-contract/index.ts, src/ui/server/helpers/required-fields/prepare-application/index.test.ts, src/ui/server/helpers/required-fields/prepare-application/index.ts, src/ui/server/helpers/summary-lists/export-contract/index.test.ts, src/ui/server/helpers/summary-lists/export-contract/index.ts, src/ui/server/helpers/summary-lists/your-buyer/index.test.ts, src/ui/server/helpers/summary-lists/your-buyer/index.ts, src/ui/types/application.ts
This PR updates various conditions in the service so that any applications that have migrated from V1 to V2 (MVP to No-PDF) and have an "in progress" status, all conditional questions relating to the "contract value threshold" are required.
The reason for this change is:
- In MVP eligibility, we ask if the contract value is over £500k. A user can only proceed if the answer to this question is “no”.
- In No-PDF eligibility, we ask if the contract value is above or below £250k. A user can proceed with either option.
- If the contract value is above £250k, we ask more questions in the application.
- After data migration, it is not possible to determine if migrated MVP applications are specifically above £250k.
- A user has only answered “it’s less than £500k” - it could be less than £250k.
- …
=> chore(EMS-3633): data migration - required fields for in progress applications

src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
This PR fixes an issue where, if an application is migrated from V1 to V2, the "total contract value" eligibility answer would render in the spreadsheet with an answer of "no".
This field is not present in V1/MVP, only in V2/No-PDF. Therefore, the XLSX should have an empty answer for this field.
- Update `mapEligibility` to conditionally map the `TOTAL_CONTRACT_VALUE` field.
=> fix(EMS-3633): data migration - xlsx - total contract value

.github/workflows/lint.yml, .github/workflows/test.yml
This PR splits each E2E directory into a separate job
* Split E2E tests into jobs per directory
* Lint on all /workflow files if any change
=> chore(test-split): e2e - split directories into jobs

e2e-tests/content-strings/error-messages.js, src/ui/server/content-strings/error-messages.ts
This PR fixes an incorrect error message in the eligibility flow.
- Update `HAS_END_BUYER` error message content strings.
=> fix(EMS-3804): eligibility - end buyer - error message

e2e-tests/content-strings/fields/insurance/export-contract/index.js, e2e-tests/content-strings/fields/insurance/your-buyer/index.js, e2e-tests/content-strings/pages/insurance/eligibility/index.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/alternative-currency/alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover-currency/turnover-currency-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/currency-of-late-payments/currency-of-late-payments.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/failed-to-pay/failed-to-pay.spec.js, src/api/content-strings/fields/insurance/your-buyer/index.ts, src/ui/server/content-strings/fields/insurance/export-contract/index.ts, src/ui/server/content-strings/fields/insurance/your-buyer/index.ts, src/ui/server/content-strings/pages/insurance/eligibility/index.ts, src/ui/templates/shared-pages/alternative-currency.njk
This PR introduces a series of minor content iterations throughout EXIPS.
This covers the following tickets:
- EMS-3824
- EMS-3825
- EMS-3837
- EMS-3838
- EMS-3840
- EMS-3841
- Update `PAYABLE_COUNTRY_CODE` summary list title.
- Add `FAILED_PAYMENTS` field hint.
- Update `END_BUYER` page title.
- Update "alternative currency" forms to have a submit button with "continue" copy, instead of "confirm".
- Remove unused `FAILED_PAYMENTS` content string label.
=> style(EMS-3824-25-37-38-40-41): content iterations

e2e-tests/commands/insurance/complete-and-submit-alternative-currency-form.js, e2e-tests/commands/insurance/your-buyer/complete-and-submit-your-buyer-forms.js, e2e-tests/content-strings/fields/insurance/your-buyer/index.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments-non-gbp-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments.spec.js, src/api/.keystone/config.js, src/api/content-strings/fields/insurance/your-buyer/index.ts, src/ui/server/content-strings/fields/insurance/your-buyer/index.ts, src/ui/server/controllers/insurance/your-buyer/outstanding-or-overdue-payments/index.test.ts, src/ui/server/controllers/insurance/your-buyer/outstanding-or-overdue-payments/index.ts, src/ui/templates/insurance/your-buyer/outstanding-or-overdue-payments.njk
This PR fixes an issue where the "outstanding and overdue payments" field labels in the "your buyer" section would not render the previously submitted currency.
- Update `completeAndSubmitAlternativeCurrencyForm` cypress command to consume and pass a `currency` param.
- Update `completeAndSubmitYourBuyerForms` cypress command.
- Update field content strings.
- Viewing the "outstanding/overdue payments" form with an "alternative" currency.
- Viewing the "outstanding/overdue payments" form with a non-GBP currency.
- Update the GET controller to:
- Add the currency to each form field.
- Consume`allCurrencies` instead of only `supportedCurrencies`.
- Fix a nunjucks column layout issue.
=> fix(EMS-3822): your buyer - outstanding/overdue payments - label currencies

src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-single-contract-policy/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-single-contract-policy/index.ts, src/api/package.json, src/api/test-helpers/create-full-application.ts
This PR updates the application submission XLSX mapping to include a new `REQUESTED_CREDIT_LIMIT` row in the "Policy" section.
This field was recently added to the user flow/data model.
- Update `mapSingleContractPolicy` XLSX mapping function
=> style(EMS-3823): application submission - xlsx - credit limit row

src/ui/server/controllers/insurance/business/turnover-currency/index.test.ts, src/ui/server/controllers/insurance/business/turnover/index.test.ts, src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts, src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts, src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts, src/ui/server/controllers/insurance/your-buyer/currency-of-late-payments/index.test.ts, src/ui/server/controllers/insurance/your-buyer/outstanding-or-overdue-payments/index.test.ts, src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
Some UI unit tests had missing test coverage for some `api.keystone.APIM.getCurrencies` conditions - testing when it should or should not be called.
- Add missing unit tests.
=> chore(tests): add missing getCurrencies unit tests

src/api/.keystone/config.js, src/api/content-strings/fields/insurance/your-buyer/index.ts, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-outstanding-payments/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-outstanding-payments/index.ts
This PR adds a new currency code row to the XLSX's "Your buyer" sheet, sent to underwriters during application submission.
- Update `mapOutstandingPayments` function.
List any additional fixes or improvements.
=> style(EMS-3821): application submission - xlsx - payments currency

e2e-tests/commands/insurance/check-export-contract-summary-list.js, e2e-tests/content-strings/fields/insurance/export-contract/index.js, e2e-tests/shared-test-assertions/summary-lists/export-contract/fully-populated.js, e2e-tests/shared-test-assertions/summary-lists/export-contract/minimal.js, src/ui/server/content-strings/fields/insurance/export-contract/index.ts, src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.test.ts, src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.ts
This PR updates the export contract's summary list to include a row for the "fixed sum currency code".
- Update DRY E2E assertions:
- `checkExportContractSummaryList`
- `assertFullyPopulatedExportContractSummaryListRows`
- `assertMinimalExportContractSummaryListRows`
- Update field content strings.
- Update the UI's `agentChargesFields` function.
=> style(EMS-3835-3836): export contract - check your answers - currency code

e2e-tests/commands/shared-commands/assertions/assert-empty-contract-completion-date-field-values.js, e2e-tests/commands/shared-commands/assertions/assert-empty-requested-start-date-field-values.js, e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/pre-credit-period/change-your-answers-pre-credit-period-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/multiple-policy/change-your-answers-change-policy-type-multiple-to-single-to-multiple.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/pre-credit-period/change-your-answers-pre-credit-period-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/single-policy/change-your-answers-change-policy-type-single-to-multiple-to-single.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
- Various E2E assertions were using `should('have.value', ...)` instead of an existing `cy.checkValue` command.
- Update all E2E tests to use `cy.checkValue`.
=> chore(EMS-3850): update all e2e tests to use checkValue command

e2e-tests/commands/shared-commands/assertions/assert-empty-contract-completion-date-field-values.js, e2e-tests/commands/shared-commands/assertions/assert-empty-requested-start-date-field-values.js, e2e-tests/commands/shared-commands/assertions/check-date-field-values.js, e2e-tests/commands/shared-commands/assertions/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js
This PR introduces a DRY `checkDateFieldValues` cypress command.
- Create `checkDateFieldValues` command.
- Update `assertEmptyContractCompletionDateFieldValues` command.
- Update `assertEmptyRequestedStartDateFieldValues` command.
List any additional fixes or improvements.
=> chore(EMS-3898): dry checkDateFieldValues cypress command

e2e-tests/commands/insurance/complete-and-submit-currency-form.js, e2e-tests/commands/insurance/complete-business-section.js, e2e-tests/commands/insurance/complete-buyer-section.js, e2e-tests/commands/insurance/complete-export-contract-section.js, e2e-tests/commands/insurance/export-contract/complete-and-submit-export-contract-forms.js, e2e-tests/commands/insurance/your-business/complete-and-submit-your-business-forms.js, e2e-tests/commands/insurance/your-buyer/complete-and-submit-your-buyer-forms.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/currency-of-agents-charge/change-your-answers-currency-of-agents-charge-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-traded-with-buyer-no-to-yes-outstanding-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/currency-of-agents-charge/change-your-answers-currency-of-agents-charge-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/currency-of-agent-charges/currency-of-agent-charges.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-traded-with-buyer-no-to-yes-outstanding-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/currency-of-late-payments/currency-of-late-payments-change-currency.spec.js, e2e-tests/insurance/cypress/support/application/index.js, e2e-tests/shared-test-assertions/currency-form-fields/prefix.js
Previously, the "alternative currency" functionality had a different flow. This has been removed and is now part of the "currency form" flows.
- Rename `completeAndSubmitAlternativeCurrencyForm` cypress command to `completeAndSubmitCurrencyForm`.
=> chore(EMS-3788): rename 'complete currency form' cypress command

e2e-tests/commands/insurance/complete-multiple-contract-policy-form.js, e2e-tests/commands/insurance/complete-single-contract-policy-form.js, e2e-tests/commands/insurance/date-field.js, e2e-tests/commands/shared-commands/form/complete-date-form-fields.js, e2e-tests/commands/shared-commands/form/index.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
This PR creates a new `completeDateFormFields` cypress command so that instead of this:
```js
cy.keyboardInput(field.dayInput(), '1');
cy.keyboardInput(field.monthInput(), '2');
cy.keyboardInput(field.yearInput(), '2022');
```
We can just do this:
```js
cy.completeDateFormFields({ idPrefix: REQUESTED_START_DATE, day: '1', month: '2', year: '2022' });
```
- Create new command.
- Rename DRY date validation assertions to return day/month/year with an assertion suffix.
=> chore(EMS-3899): dry completeDateFormFields cypress command

e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments.spec.js
This PR updates an "outstanding/overdue payments" E2E test to use an existing command.
- Update E2E test.
=> chore(EMS-3812): outstanding/overdue payments - dry e2e assertion

e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-much-the-agent-is-charging/how-much-the-agent-is-charging.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-non-gbp-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-non-gbp-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments-alternative-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments-non-gbp-currency.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/outstanding-or-overdue-payments/outstanding-or-overdue-payments.spec.js
- Some E2E tests were using `.prefix()` field selectors instead of the `assertPrefix` command.
- Update all `.prefix()` E2E tests to use `cy.assertPrefix`.
=> chore(EMS-3955): update all e2e tests to use assertPrefix command

src/ui/server/helpers/mappings/map-applications/index.ts
- Previously, we had a bug in production where 2x applications were created at the same time without some required properties.
- We were unable to replicate the issue and spent a lot of time debugging.
- One issue occured where the dashboard page was erroring/showing odd behaviour.
- It was hard to track down why this was happening - the reason was because there was no buyer country name or reference number.
- This PR introduces some logging to highlight these, making it easier for future debugging, if this were to happen again.
- Introduce additional logging and documentation to `mapApplication` and `mapApplications`.
=> chore(EMS-3956): add missing property logs to mapApplication helper

src/api/custom-resolvers/mutations/create-an-account/index.test.ts
- The "create account" GQL mutation unit tests had repeated code in some `beforeEach` and `beforeAll` blocks.
- Create ` setupTests` function.
- Update `beforeEach` and `beforeAll` blocks.
=> chore(EMS-3463): dry create account mutation unit tests

e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search.spec.js, src/api/.keystone/config.js, src/api/data-migration/version-2-to-version-3/update-applications/add-policy-requested-credit-limit-field.ts, src/api/tsconfig.json, src/ui/tsconfig.json
This PR fixes an issue with data migration (v2 to v3), where the `requestedCreditLimit` column in the `policy` table was a `tinyint`, instead of an `int`.
- Update `addPolicyRequestedCreditLimitField`.
- Remove now outdated TS config (`suppressImplicitAnyIndexErrors`)
- Fix a typo in an E2E test.
=> fix(EMS-3901): data migration - requestedCreditLimit column

.github/dependabot.yml
- Dependabot runs at a random time. When this is during working hours, it uses a lot of runners.
- Change time to be 3am.
- Update dependabot to run weekly instead of monthly.
=> chore(EMS-3966): update dependabot to run during non working hours

e2e-tests/commands/core-page-checks.js, e2e-tests/commands/insurance/account/assert-password-reveal-button.js, e2e-tests/commands/shared-commands/assertions/check-email-field-rendering.js, e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-enter-code.spec.js, e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/eligible-to-apply-online/eligible-to-apply-online.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js, e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js, e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js, e2e-tests/quote/cypress/e2e/journeys/skip-link.spec.js
Some E2E tests were checking that an element exists, before asserting something in the element.
This is unnecessary because if the element doesn't exist, the proceeding assertion would fail.
- Remove unnecessary `should('exist')` assertions.
=> chore(EMS-3980): remove unnecessary 'should exist' e2e assertions

e2e-tests/insurance/cypress/e2e/journeys/cookies.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/cover-period/cover-period.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/end-buyer/end-buyer.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/have-an-account/have-an-account.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/member-of-a-group/member-of-a-group.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/party-to-consortium/party-to-consortium.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/total-value-insured/total-value-insured.spec.js, e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js, e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js, e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js, e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
The `submitAndAssertFieldErrors` and `submitAndAssertRadioErrors` cypress commands have a default `expectedErrorsCount` value. Therefore, there is no need to pass the same default into these commands.
- Remove `unnecessary` instances of `expectedErrorsCount`.
=> chore(EMS-4005): remove unnecessary expectedErrorsCount params

src/api/.keystone/config.js, src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.test.ts, src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.ts, src/api/custom-resolvers/mutations/create-an-account/index.test.ts, src/api/custom-resolvers/mutations/create-an-account/index.ts, src/api/types/account/index.ts, src/ui/server/shared-validation/date/index.test.ts
- A lot of E2E tests frequently fail locally and in GHA due to the tests triggering calls to Notify as part of the account creation and sign in process.
- This PR updates some API logic so that when running in a dev environment (local or GHA), Notify will **not** be called and instead the API will return a success response.
- Update `accountSignInChecks` GQL mutation to conditionally log and return an account ID and `success=true`.
- Update `createAnAccount` GQL mutation to conditionally log and return an account ID, verification hash and `success=true`.
- Update unit tests.
- Minor documentation improvement.
- Fix a failing date test.
=> chore(EMS-4019): account creation/sign in checks - dev environment

e2e-tests/content-strings/fields/insurance/policy/index.js, e2e-tests/content-strings/links.js, e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js, e2e-tests/pages/insurance/policy/multipleContractPolicyExportValue.js, src/api/.keystone/config.js, src/api/constants/application/versions/index.ts, src/api/content-strings/fields/insurance/policy/index.ts, src/api/content-strings/links.ts, src/ui/server/constants/application/versions/index.ts, src/ui/server/content-strings/fields/insurance/policy/index.ts, src/ui/server/content-strings/links.ts, src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk, src/ui/types/application.ts
This PR updates the "Multiple contract policy - export value" page to include an "intial credit limit" hint.
This new hint tells users that they could be eligible for the "Small Export Builder".
- Add E2E tests.
- Update nunjucks template.
- Minor E2E improvements.
- Update/align application version constants (The UI constants were out of date).
=> feat(EMS-3993): multiple contract policy - small export builder content

.github/dependabot.yml
Combine dependabot directories into 1 for each package-ecosystem
* combines npm and docker package-ecosystems into 1 for directories
* Change timing for npm update for testing
=> chore(EMS-4031): combine dependabot directories into 1

e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-no-to-yes.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-yes-to-no.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js, e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/save-and-back.spec.js, src/ui/server/controllers/insurance/declarations/map-submitted-data/modern-slavery/index.test.ts, src/ui/server/controllers/insurance/declarations/map-submitted-data/modern-slavery/index.ts
This PR updates the data saving mapping for the "Modern slavery" declaration form so that if the answers are changed from "no" to "yes" all conditional fields for "no" answers are wiped.
- Add E2E test coverage for changing the answers from "no" to "yes" and vice versa.
- Update `mapSubmittedData` to appropriately wipe conditional fields.
- Align some test descriptions.
=> feat(EMS-4060): declarations - modern slavery - change answers

src/api/.keystone/config.js, src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.test.ts, src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.ts, src/api/emails/send-application-submitted-emails/index.test.ts, src/api/emails/send-application-submitted-emails/index.ts
This PR fixes an issue where, during application submission the "eligible for small export builder" calculation would incorrectly calculate non GBP currencies.
- Update `multiplePolicyTypeTemplateId.get` to divide instead of multiply.
- Simplify some test mocks.
- Remove some unnecessary `buyerName` instances in `applicationSubmittedEmails.send`.
- Minor documentation improvements.
=> fix(EMS-4088): application submission - small export builder calculation

database/exip.sql, src/api/.keystone/config.js, src/api/constants/application/versions/index.test.ts, src/api/constants/application/versions/index.ts, src/api/constants/application/versions/latest.ts, src/api/data-migration/execute-sql-query.ts, src/api/data-migration/version-1-to-version-2/update-applications/update-application-migrated.ts, src/api/data-migration/version-1-to-version-2/update-applications/update-application-version.ts, src/api/data-migration/version-2-to-version-3/update-applications/update-application-migrated.ts, src/api/data-migration/version-2-to-version-3/update-applications/update-application-version.ts, src/api/data-migration/version-4-to-version-5/README.md, src/api/data-migration/version-4-to-version-5/index.ts, src/api/data-migration/version-4-to-version-5/update-applications/add-broker-fields.ts, src/api/data-migration/version-4-to-version-5/update-applications/index.ts, src/api/data-migration/version-4-to-version-5/update-applications/update-application-migrated-fields.ts, src/api/data-migration/version-4-to-version-5/update-applications/update-application-version.ts, src/api/package-lock.json, src/api/package.json, src/api/schema.graphql, src/api/schema.prisma, src/api/schema.ts, src/api/types/application-types/index.ts, src/ui/server/constants/application/versions/index.ts, src/ui/types/application.ts
This PR adds a data migration script so that when `main-broker-address-lookup` is deployed, we can migrate previous applications data structure into the new data structure required for "broker address lookup".
- Create data migration V4 to V5 index script.
- Create migration helper functions.
- Update `package.json`.
- Update, align application `VERSIONS` constants.
- NOTE: Whilst this migration is for version 5 - version 4 has been added.
- In the near future, version 4 and 5 could be merged into one migration script.
- Version 4 is currently in a different branch and could will be rolled out before version 5.
- In the meantime, decided to keep version 5 separate.
=> feat(EMS-4016): broker address lookup - data migration

e2e-tests/content-strings/error-messages.js, src/ui/server/content-strings/error-messages.ts
- 2x error messages for "Declarations - modern slavery" have some incorrect copy.
=> fix(EMS-4138): declarations - modern slavery - error messages

e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js, src/ui/server/controllers/insurance/policy/broker-manual-address/index.test.ts, src/ui/server/controllers/insurance/policy/broker-manual-address/index.ts, src/ui/templates/insurance/policy/broker-manual-address.njk
In the "Enter manual broker address" page, the primary button requires the label to be `Use this address` instead of `Continue`.
* Added `SUBMIT_BUTTON_COPY` variable to view-controller.
* Updated unit and E2E tests.
=> fix(EMS-4205): enter your brokers address button label

e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-ordnance-survey-invalid-postcode.spec.js, src/api/.keystone/config.js, src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.test.ts, src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.ts, src/api/integrations/ordnance-survey/index.ts
Certain postcodes were still redirecting to problem with service due to ordnance survey 
* Added check if response is 200 or 400 and no success, then to return noAddressesFound flag
* Added apiError return if no response data or success
* Added more e2e tests
* Added documentation
=> fix(EMS-4206): fix certain postcode searches going to problem with service page

src/api/.keystone/config.js, src/api/emails/application/index.test.ts, src/api/emails/application/index.ts
This PR fixes an issue where MDM was returning incorrect file type error from notify on application submission
* set file to hex string before sending to MDM
* Updated test
=> fix(EMS-4204): fix incorrect file format sent to mdm for submission email

src/api/.keystone/config.js, src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/based-in-the-uk/index.test.ts, src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/based-in-the-uk/index.ts
This PR fixes an issue where the user entered building name or number was visible on the generated xlsx spreadsheet as shown below, where the first 1 is not required
* Remove buildingNumberOrName from generated xlsx
* update tests
=> fix(EMS-4216): remove buildingNameOrNumber from xlsx generation

.github/dependabot.yml
Typescript 5.8 is a breaking change causing ui not to compile.  This PR limits the version to below 5.8 for dependabot updates
* Added dependabot condition for typescript
=> chore(EMS-4217): dependabot - limit typescript to below 5.8

.github/dependabot.yml
This PR limits dependabot only updating typescript up to 5.4.5 in the UI directory (but allows newer versions in other directories)
* added an allow section in dependabot to limit version of typescript in ui
=> chore(EMS-4217): dependabot - limit typescript to 5.4 only in ui directory

.github/dependabot.yml
This PR limits dependabot only updating typescript up to 5.4.5 in the UI directory (but allows newer versions in other directories)
* added an allow section in dependabot to limit version of typescript in ui
=> chore(EMS-4217): dependabot - remove typescript version limit
