e2e-tests/content-strings/summary-answers.js
e2e-tests/cypress/integration/journeys/change-your-answers.spec.js
e2e-tests/cypress/integration/journeys/check-your-answers.spec.js
e2e-tests/cypress/integration/journeys/tell-us-about-your-deal/tell-us-about-your-deal.spec.js
ui/server/content-strings/summary-answers.js
ui/server/controllers/tell-us-about-your-deal/index.js
ui/server/controllers/tell-us-about-your-deal/index.test.js
ui/server/helpers/get-currency-by-code.js
ui/server/helpers/get-currency-by-code.test.js
ui/server/helpers/map-answers-to-content.js
ui/server/helpers/map-answers-to-content.test.js

- Save currency as an object
- Update currency answer text

feat/EMS-131 - design/content updates - Answers page

---

e2e-tests/content-strings/error-messages.js
e2e-tests/cypress/integration/journeys/tell-us-about-your-deal/tell-us-about-your-deal-validation.spec.js
ui/server/content-strings/error-messages.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/credit-period.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/credit-period.test.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/pre-credit-period.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/pre-credit-period.test.js

- Credit period: minimum value rule
- Pre-credit period: minimum value rule

feat/EMS-159 - credit period validation updates

---

e2e-tests/content-strings/error-messages.js
e2e-tests/cypress/integration/journeys/tell-us-about-your-deal/tell-us-about-your-deal-policy-type-validation.spec.js
e2e-tests/cypress/integration/journeys/tell-us-about-your-deal/tell-us-about-your-deal-validation.spec.js
ui/server/content-strings/error-messages.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/amount.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/credit-period.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/credit-period.test.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/policy-length.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/policy-length.test.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/pre-credit-period.js
ui/server/controllers/tell-us-about-your-deal/validation/rules/pre-credit-period.test.js
ui/server/helpers/number.js
ui/server/helpers/number.test.js
ui/templates/before-you-start.njk
ui/templates/buyer-based.njk
ui/templates/check-your-answers.njk
ui/templates/company-based.njk
ui/templates/tell-us-about-your-deal.njk
ui/templates/tried-to-obtain-cover.njk
ui/templates/uk-content-percentage.njk

- add decimal/whole number validation to month fields
- add `novalidate` to all forms

feat/EMS-169 - decimal/whole number validation

---

e2e-tests/content-strings/fields.js
e2e-tests/content-strings/footer.js
e2e-tests/content-strings/pages.js
e2e-tests/cypress/e2e/journeys/footer.spec.js
e2e-tests/cypress/e2e/journeys/policy-type/policy-type.spec.js
e2e-tests/cypress/e2e/pages/policyTypePage.js
e2e-tests/cypress/e2e/partials/footer.js
ui/server/content-strings/fields.js
ui/server/content-strings/footer.js
ui/server/content-strings/pages.js
ui/templates/guidance.njk
ui/templates/partials/footer.njk
ui/templates/policy-type.njk
ui/templates/uk-goods-or-services.njk

- Guidance page: Fix a link in
- Company Based page: update heading/title
- UK goods & services page: Add links in expandable content
- Policy type page: Update radio labels
- Footer: remove MGA link

fix/various - copy, content, remove MGA link from footer

---

e2e-tests/content-strings/links.js
e2e-tests/content-strings/pages.js
src/ui/server/content-strings/links.ts
src/ui/server/content-strings/pages.ts
src/ui/templates/index.njk
src/ui/templates/partials/phase-banner.njk
src/ui/templates/quote/check-your-answers.njk

- Update external guidance/application links
- Fix accessibility issues:
- Add `complementary` aria role/landmark to the ohase banner.
- Remove empty/outdated "company group" details being generated on the Answers page.

fix(EMS-248): update external guidance/application links. Fix accessibility issues

---

.github/workflows/infrastructure.yml
.github/workflows/production.yml
.github/workflows/scan_codacy_analysis.yml
.github/workflows/scan_codeql_analysis.yml

In line up for the launch `IaC` and GHA powered `CI/CD` pipelines are required.
This PR aims to introduce and improve existing GHA.
* `infrastructure.yml` : Base infrastructure - Builds ACR
* `production.yml`: Builds, tags, push and creates deployment slots with an eventual WebApp restart.
* Enhancement of existing SCA GHA

build(IaC): Exips production IaC

---

e2e-tests/constants/routes/insurance.js
e2e-tests/content-strings/pages/insurance/eligibility/index.js
e2e-tests/content-strings/pages/insurance/index.js
e2e-tests/cypress/e2e/journeys/insurance/eligibility/check-if-eligible.spec.js
e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
e2e-tests/cypress/e2e/pages/insurance/eligibility/checkIfEligible.js
e2e-tests/cypress/e2e/pages/insurance/eligibility/index.js
e2e-tests/cypress/e2e/pages/insurance/index.js
src/ui/server/constants/routes/insurance.ts
src/ui/server/constants/templates/insurance.ts
src/ui/server/constants/templates/insurance/eligibility/index.ts
src/ui/server/constants/templates/insurance/index.ts
src/ui/server/content-strings/pages/insurance/eligibility/index.ts
src/ui/server/content-strings/pages/insurance/index.ts
src/ui/server/controllers/insurance/eligibility/check-if-eligible/index.test.ts
src/ui/server/controllers/insurance/eligibility/check-if-eligible/index.ts
src/ui/server/routes/insurance/eligibility/index.test.ts
src/ui/server/routes/insurance/eligibility/index.ts
src/ui/server/routes/insurance/index.test.ts
src/ui/server/routes/insurance/index.ts
src/ui/templates/insurance/eligibility/check-if-eligible.njk
src/ui/templates/insurance/start.njk

This PR adds the "check if you're eligiible" page to the insurance flow.
- Add page.
- New routes and directories for `insurance/eligibility`.
- Remove unused import in insurance start page template.
- Improve insurance start page e2e test.

feat(EMS-336): insurance eligibility - check if you're eligible page

---

src/api/custom-schema.ts
src/api/keystone.ts
src/api/package-lock.json
src/api/package.json
src/api/schema.graphql

This PR adds a custom mutation to keystone to send an email with Notify.

feat(EMS-332): Custom mutation for sending emails

---

e2e-tests/content-strings/index.js
e2e-tests/content-strings/uk-goods-and-services-calculate-description.js
e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
e2e-tests/cypress/e2e/partials/index.js
e2e-tests/cypress/e2e/partials/ukGoodsOrServicesCalculateDescription.js
e2e-tests/cypress/support/check-uk-goods-and-services-calculate-description.js
src/ui/server/content-strings/index.ts
src/ui/server/content-strings/uk-goods-and-services-calculate-description.ts
src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.test.ts
src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.ts
src/ui/templates/insurance/eligibility/uk-goods-or-services.njk
src/ui/templates/partials/uk-goods-and-services-calculate-description.njk

This PR adds an expandable "how to calculate" section to the UK Goods and services page of the Insurance eligibility flow.

feat(EMS-425): Insurance eligibility - UK goods-services page with "how to calculate" description

---

e2e-tests/constants/routes/insurance.js
e2e-tests/content-strings/pages/insurance/eligibility/index.js
e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js
e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online.spec.js
e2e-tests/cypress/e2e/pages/insurance/eligibility/eligibleToApplyOnline.js
e2e-tests/cypress/e2e/pages/insurance/eligibility/index.js
src/ui/server/constants/routes/insurance.ts
src/ui/server/constants/templates/insurance/eligibility/index.ts
src/ui/server/content-strings/pages/insurance/eligibility/index.ts
src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
src/ui/server/routes/insurance/eligibility/index.test.ts
src/ui/server/routes/insurance/eligibility/index.ts
src/ui/server/routes/insurance/index.test.ts
src/ui/templates/insurance/eligibility/companies-house-number.njk
src/ui/templates/insurance/eligibility/eligible-to-apply-online.njk
src/ui/templates/insurance/eligibility/insured-amount.njk
src/ui/templates/insurance/eligibility/insured-period.njk
src/ui/templates/insurance/eligibility/letter-of-credit.njk
src/ui/templates/insurance/eligibility/other-parties.njk
src/ui/templates/insurance/eligibility/pre-credit-period.njk
src/ui/templates/insurance/eligibility/uk-goods-or-services.njk
src/ui/templates/quote/uk-goods-or-services.njk

This PR adds the final page to the Insurance eligibility flow - "You are eligible to apply online"
- Add new route and controller for the "you are eligible" page.
- Remove unused variables in various nunjuck templates.

feat(EMS-369): Insurance eligibility - eligible to apply online

---

e2e-tests/content-strings/pages/insurance/eligibility/index.js
e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js
e2e-tests/cypress/e2e/pages/insurance/eligibility/index.js
e2e-tests/cypress/e2e/pages/insurance/eligibility/preCreditPeriod.js
src/ui/server/content-strings/pages/insurance/eligibility/index.ts
src/ui/templates/insurance/eligibility/pre-credit-period.njk

This PR adds an expandable details section to the pre-credit period page in the Insurance eligibility flow.

feat(EMS-461): Insurance eligibility - pre-credit period expandable details

---

README.md

This PR adds more details about EXIP, the code structure/approach and some development principles.
Link to the markdown generation for easier reading: https://github.com/UK-Export-Finance/exip/blob/603970f99be82a24c6dff4fb120fa35dd940ae2e/README.md

chore(EMS-662): update README.md

---

.github/workflows/deploy.sh
.github/workflows/development.yml
.github/workflows/infrastructure.yml
.github/workflows/production.yml
.github/workflows/test.yml
database/exip.sql

`main-application` branch has evolved as an independent MVP. This constitutes for a creation of an independent `dev` containers responsible for running `ui`, `api` and `DB` from ACR.
* Introduction of `exip-dev-ui` WebApp.
* Introduction of `exip-dev-api` WebApp.
* `dev` branch to refer to `main-application` for dev deployments.
* QA specific environment variables introduction, to enable `localhost` DB communication.
* SQL: Foreign key checks disabled during `exip.sql` execution.
* Code quality improvement.
* Code beautification.
* Merged `infrastructure` branch, for IaC development build.
* Enable Azure MySQL flex IaC once available in `UK South` region, ticket raised with Azure.

feat(EMS-470): Development deployment

---

e2e-tests/constants/field-ids/insurance/exporter-business/index.js
e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js
src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
src/ui/templates/insurance/your-business/company-details.njk

* Used `FIELD_IDS` instead of hard coding for data-cy on company-details page

chore(EMS-789): use FIELD_IDS for data-cy variables in the company details page

---

package-lock.json
src/ui/package-lock.json

json5 has a new security issue. Dependabot PRs are having issues with E2E tests for some reason.

chore(deps): bump json5

---

src/ui/package-lock.json
src/ui/package.json
src/ui/server/api/external/index.ts

Bump axios to the latest version which includes a bug fix that seems to be causing us an issue with deployment.
_"fixed AxiosRequestConfig header interface by refactoring it to RawAxiosRequestConfig; "_

chore(deps): bump axios

---

.github/workflows/development.yml

- reverted the deployment dependencies

chore: updated the dependencies for Dev deployments

---

e2e-tests/constants/field-ids/insurance/exporter-business/index.js
e2e-tests/content-strings/error-messages.js
e2e-tests/content-strings/fields/insurance/exporter-business/index.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/nature-of-business-page.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
e2e-tests/cypress/e2e/pages/your-business/nature-of-business/natureOfBusiness.js
src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
src/ui/server/content-strings/error-messages.ts
src/ui/server/content-strings/fields/insurance/your-business/index.ts
src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
src/ui/server/controllers/insurance/business/nature-of-business/index.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.test.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.test.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/index.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/years-exporting.ts
src/ui/server/helpers/whole-number-validation/index.test.ts
src/ui/server/helpers/whole-number-validation/index.ts
src/ui/templates/insurance/your-business/nature-of-your-business.njk

* Added number of employee fields
* Added validation
* Added helper for whole number validation
* Updated and added tests

feat(EMS-642-643): Your business - Nature of your business - Number of employees fields

---

e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-buyer/validation/company-or-organisation-validation-address.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-buyer/validation/company-or-organisation-validation.spec.js
src/ui/server/controllers/insurance/your-buyer/validation/rules/address.ts

Update the maximum characters allowed in the address field of "Company or organisation" form of the "Your buyer" section, to match design.
- Added E2E test coverage to check validation errors when too many characters are submitted.
- Updated all "Your buyer" E2E tests to click through the task list instead of visiting the page directly.

fix(EMS-877): Your buyer - Company or organisation - update address field's maximum characters

---

database/exip.sql

`ReferenceNumber` table `id` column should increment from `10000`.
`AUTO_INCREMENT` set to `10000`.

feat(EMS-945): ReferenceNumber set auto increment

---

e2e-tests/constants/field-ids/insurance/exporter-business/index.js
e2e-tests/content-strings/error-messages.js
e2e-tests/content-strings/fields/insurance/exporter-business/index.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-page.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
e2e-tests/cypress/e2e/pages/your-business/turnover/turnover.js
src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
src/ui/server/constants/routes/insurance/exporter-business.ts
src/ui/server/content-strings/error-messages.ts
src/ui/server/content-strings/fields/insurance/your-business/index.ts
src/ui/server/controllers/insurance/business/company-details/index.ts
src/ui/server/controllers/insurance/business/nature-of-business/index.ts
src/ui/server/controllers/insurance/business/turnover/index.test.ts
src/ui/server/controllers/insurance/business/turnover/index.ts
src/ui/server/controllers/insurance/business/turnover/validation/index.test.ts
src/ui/server/controllers/insurance/business/turnover/validation/index.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.test.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/index.ts
src/ui/server/routes/insurance/business/index.test.js
src/ui/server/routes/insurance/business/index.ts
src/ui/server/routes/insurance/index.test.ts
src/ui/templates/insurance/your-business/turnover.njk

* Added estimated annual turnover field
* Added validation
* Added e2e tests

feat(EMS-645): Company Details - Turnover - Estimated Annual Turnover field

---

e2e-tests/constants/field-ids/insurance/exporter-business/index.js
e2e-tests/content-strings/error-messages.js
e2e-tests/content-strings/fields/insurance/exporter-business/index.js
e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation-email.spec.js
e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation-password.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-page.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
e2e-tests/cypress/e2e/pages/your-business/turnover/turnover.js
e2e-tests/cypress/support/commands.js
e2e-tests/cypress/support/submit-and-assert-errors.js
src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
src/ui/server/content-strings/error-messages.ts
src/ui/server/content-strings/fields/insurance/your-business/index.ts
src/ui/server/controllers/insurance/business/turnover/index.test.ts
src/ui/server/controllers/insurance/business/turnover/index.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/index.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.test.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.ts
src/ui/server/helpers/number/index.test.ts
src/ui/server/helpers/number/index.ts
src/ui/templates/insurance/your-business/turnover.njk

* Added percentage of turnover field
* Added validation
* Added helper for maximum value
* Added tests
* Added cypress command for checking validation `submitAndAssertErrors`

feat(EMS-646): Company Details - Turnover - Percentage of Turnover Field and new shared cypress validation command

---

.github/workflows/publish.yml

- updated the automated release notes file to include `main-application` branch

chore: updated the automated-release-notes file

---

package-lock.json

* NPM audit package update suggestion.
* `http-cache-semantics` updated to `4.1.1`

chore(npm): Package update

---

CHANGELOG.md
package-lock.json
package.json
src/api/package-lock.json
src/ui/package-lock.json

`npm audit` has flagged various vulnerabilities across the microservices.
* Merged `main` with package udpates.
* Myriads of package updates at `root` and `src/api`.

chore(npm-audit): Package updates

---

e2e-tests/content-strings/error-messages.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/broker-email-validation.spec.js
e2e-tests/cypress/e2e/pages/your-business/broker/broker.js
src/ui/server/content-strings/error-messages.ts
src/ui/server/controllers/insurance/business/broker/index.test.ts
src/ui/server/controllers/insurance/business/broker/index.ts
src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.test.ts
src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.ts
src/ui/server/controllers/insurance/business/broker/validation/rules/index.ts
src/ui/templates/components/address-field-input.njk
src/ui/templates/insurance/your-business/broker.njk

* Added broker email field
* Changed data-cy in broker section for input to include -input
* Added tests and e2e tests

feat(EMS-670): Company Details - Broker - Email field

---

e2e-tests/cypress/e2e/journeys/cookies.spec.js
e2e-tests/cypress/e2e/journeys/footer.spec.js
e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body-answer-yes.spec.js
e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-fields-multi-policy-credit-period.spec.js
e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
src/ui/Dockerfile
src/ui/server/index.ts
src/ui/server/middleware/headers/security.ts

Session cookie is not being created on `production` environment.
Though same issue cannot be replicated locally despite using `production` as `NODE_ENV` value, hope following changes will have an impact.
* Docker base image update.
* Session cookie security update by using `__Host-` prefix and custom cookie name.
* Updated E2E tests with custom cookie name.
* Enabled `data:` protocol for `font-src` CSP rule.

fix(cookie): Docker image update + Cookie security

---

.github/workflows/deploy.sh

* SCA - Double quote variables, to avoid globbing.

fix(deployment-script): Code improvement

---

e2e-tests/constants/routes/index.js
e2e-tests/content-strings/footer.js
e2e-tests/content-strings/links.js
e2e-tests/content-strings/pages.js
e2e-tests/cypress/e2e/journeys/accessibility-statement.spec.js
e2e-tests/cypress/e2e/pages/accessibility-statement.js
e2e-tests/cypress/e2e/pages/index.js
e2e-tests/cypress/e2e/partials/footer.js
src/ui/server/constants/routes/index.ts
src/ui/server/constants/templates/index.ts
src/ui/server/content-strings/footer.ts
src/ui/server/content-strings/links.ts
src/ui/server/content-strings/pages.ts
src/ui/server/controllers/root/accessibility-statement/index.test.ts
src/ui/server/controllers/root/accessibility-statement/index.ts
src/ui/server/routes/root/index.test.ts
src/ui/server/routes/root/index.ts
src/ui/templates/accessibility-statement.njk
src/ui/templates/partials/footer.njk

This PR adds the accessibility statement page.
- Setup route, controller and template.
- E2E test coverage.

feat(EMS-1046): Accessibility statement

---

e2e-tests/cypress/e2e/journeys/footer.spec.js

Add an E2E test for the accessibility statement footer link and improve the E2E footer link test descriptions.

fix(EMS-1046): accessibility statement - add missing E2E test for footer link

---

generate-exip-pricing-grid/package-lock.json
generate-exip-pricing-grid/package.json
package-lock.json
package.json
src/api/package-lock.json
src/api/package.json
src/generate-exip-pricing-grid/package-lock.json
src/ui/package-lock.json
src/ui/package.json

Introduction
NPM package updates
Resolution
* `node` and `npm` engine latest version fix.
* Various npm dependencies package updates.
* NPM scripts introduction: `install:all`, `update:all` and `audit:all`.

chore(npm): NPM update

---

database/exip.sql
e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/save-and-back.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/save-and-back.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/validation/working-with-buyer-validation.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/working-with-buyer.spec.js
src/api/.keystone/config.js
src/api/schema.graphql
src/api/schema.prisma
src/api/schema.ts
src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.test.ts
src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.ts
src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.test.ts
src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.ts
src/ui/server/graphql/queries/application.ts
src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
src/ui/server/routes/insurance/index.test.ts
src/ui/server/routes/insurance/your-buyer/index.test.ts
src/ui/server/routes/insurance/your-buyer/index.ts
src/ui/server/test-mocks/mock-buyer.ts
src/ui/types/application.ts

* Save and back functionality for working with buyer page
* Database changes for working with buyer fields
* Added tests
* Changed task status to complete if complete this section

feat(EMS-820): Your buyer - Working with buyer - Save and back

---

e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-multiple-applications.spec.js
e2e-tests/cypress/e2e/pages/insurance/dashboard/index.js
src/ui/server/api/keystone/applications/index.ts
src/ui/server/graphql/queries/applications.ts

⚠️ Need this PR merged first https://github.com/UK-Export-Finance/exip/pull/376
This PR updates the "Get applications" GQL query so that applications are ordered by the most recently updated application.
- Update GQL query to pass `orderBy`.

feat(EMS-937): Dashboard - order applications by most recently updated

---

e2e-tests/content-strings/pages/insurance/index.js
e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/anti-bribery.spec.js
e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/save-and-back.spec.js
src/ui/server/content-strings/pages/insurance/index.ts

Update the dashboard page title to match design.
- Update dashboard page title.
- Update some E2E tests to use `deleteAccountAndApplication` command instead of `deleteAccount`.

fix(EMS-1324): Dashboard page title, update some E2E tests

---

package-lock.json
src/api/package-lock.json
src/ui/package-lock.json
src/ui/package.json

Cross-realm object access in Webpack 5 has been flagged as a `High` vulnerability under `CVE-2023-28154`.
* Webpack updated to `5.76.3`.
* Regular dependencies updates.

fix(CVE-2023-28154): Webpack updated to 5.76.3

---

.github/workflows/dependabot.yml

`Dependabot` custom configuration
* Daily automatic dependencies updates for `npm`, `docker` and `github-actions` ecosystems.
* All PRs will have `chore` label (if present)

feat(dependabot): added dependabot.yml GHA

---

e2e-tests/constants/routes/insurance/account.js
e2e-tests/content-strings/header.js
e2e-tests/content-strings/pages/insurance/account/index.js
e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
e2e-tests/cypress/e2e/journeys/insurance/account/sign-out/account-sign-out.spec.js
e2e-tests/cypress/e2e/journeys/insurance/header-authenticated.spec.js
e2e-tests/cypress/e2e/pages/insurance/account/sign-in/signIn.js
e2e-tests/cypress/support/check-authenticated-header.js
src/api/.keystone/config.js
src/api/schema.graphql
src/api/schema.prisma
src/ui/server/constants/routes/insurance/account.ts
src/ui/server/content-strings/header.ts
src/ui/server/content-strings/pages/insurance/account/index.ts
src/ui/server/controllers/insurance/account/sign-in/index.test.ts
src/ui/server/controllers/insurance/account/sign-in/index.ts
src/ui/server/controllers/insurance/account/sign-out/index.test.ts
src/ui/server/controllers/insurance/account/sign-out/index.ts
src/ui/server/routes/insurance/account/index.test.ts
src/ui/server/routes/insurance/account/index.ts
src/ui/server/routes/insurance/index.test.ts
src/ui/templates/insurance/account/sign-in/sign-in.njk

This PR adds the ability to sign out of an account.
- Add sign out GET route/controller to the UI. This controler wipes the user session and adds a flag to `req.flash`.
- Update the sign in page/controller to consume `req.flash('importantBanner')` and render a banner in the template.
- E2E test coverage.

feat(EMS-1334): Account - sign out

---

e2e-tests/content-strings/footer.js
e2e-tests/cypress.config.js
e2e-tests/cypress/e2e/journeys/contact-us.spec.js
e2e-tests/cypress/e2e/journeys/footer.spec.js
e2e-tests/cypress/e2e/partials/footer.js
src/ui/server/content-strings/footer.ts
src/ui/templates/partials/footer.njk

* Removed contact us details from footer
* Added link to contact to footer
* Updated e2e tests

feat(EMS-1294): Footer - Contact link and remove contact details

---

src/generate-exip-pricing-grid/package-lock.json

fix(directory): removed accidental directory creation

---

.github/workflows/README.md
src/api/Dockerfile
src/ui/Dockerfile

* Execute `npm` pre `USER node`.
* Added `README.md` for `.github` directory

fix(permission): set user node post keystone lauunch

---

src/api/Dockerfile
src/ui/Dockerfile

* Removed non-root user command.

fix(Docker): permissions

---

src/ui/server/constants/index.ts
src/ui/server/controllers/root/cookies/index.ts
src/ui/server/middleware/cookies-consent/index.test.ts
src/ui/server/middleware/cookies-consent/index.ts

* Dev would say cookies rejected when accepted and did not populate with correct cookie choice in cookies page
* Added check for Secure-optionalCookies or optionalCookies in middleware
* Added check in controller for  Secure-optionalCookies or optionalCookies
* Added tests

fix(EMS-1514-1339-1374-1516): Cookies - added Secure-optionalCookies to cookies check

---

database/exip.sql
src/api/schema.ts

* feedback on dev was redirecting to problem with service page
* Changed feedback db fields to allow 1000 characters in schema

fix(EMS-1588): Feedback referralUrl

---

e2e-tests/content-strings/links.js
e2e-tests/cypress/e2e/journeys/insurance/application-submission/application-submitted.spec.js
e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-contact.spec.js
src/ui/server/content-strings/links.ts
src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
src/ui/server/helpers/get-field-by-id/index.ts

* Made minor code fixes for typos
* For getFieldById - refactored to remove duplicate code for id
* Added research link
* Added correct hrefs to template for application-submitted
* Updated e2e test

feat(EMS-1534-1532): Application Submitted - links

---

e2e-tests/content-strings/pages/insurance/account/index.js
e2e-tests/content-strings/pages/insurance/eligibility/index.js
e2e-tests/content-strings/pages/insurance/index.js
e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
e2e-tests/cypress/e2e/pages/insurance/account/create/yourDetails.js
src/ui/server/content-strings/pages/insurance/account/index.ts
src/ui/server/content-strings/pages/insurance/eligibility/index.ts
src/ui/server/content-strings/pages/insurance/index.ts
src/ui/templates/insurance/account/create/your-details.njk
src/ui/templates/insurance/feedback.njk

* Added privacy notice and link to create account details page
* Changed wording for eligibility companies house number page and no companies house number error page
* Updated e2e tests

feat(EMS-1209-1550-1549): Companies house eligibility text change and create account details privacy notice

---

.github/workflows/deploy.sh

Fix base deployment branch for `deploy.sh`
* Changed to `main-application` from `main`.

fix(deploy): change base branch

---

e2e-tests/content-strings/pages/insurance/index.js
e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
e2e-tests/cypress/e2e/pages/insurance/start.js
src/ui/server/content-strings/pages/insurance/index.ts
src/ui/templates/insurance/start.njk

* Rectify text on insurance start page to match designs
* Add extra required text for sign in, about the service and quote under start button

fix(EMS-512): Insurance - Start - Fix and add extra wording

---

e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-signed-in.spec.js
src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
src/ui/types/pages/tell-us-about-your-policy.d.ts

* Authenticated header on Tell us about your policy quote page was missing my applications and sign out links
* Added HEADER page content to pageVariables for tell-us-about-your-policy
* Updated and added e2e test
* Updated insurance/start test to dereference nested page test

fix(EMS-1720): Quote - Tell us about your policy - Header

---

src/ui/server/controllers/insurance/business/broker/index.test.ts
src/ui/server/controllers/insurance/business/broker/index.ts
src/ui/server/controllers/insurance/business/broker/save-and-back/index.test.ts
src/ui/server/controllers/insurance/business/broker/save-and-back/index.ts
src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
src/ui/server/controllers/insurance/business/company-details/index.test.ts
src/ui/server/controllers/insurance/business/company-details/index.ts
src/ui/server/controllers/insurance/business/company-details/save-and-back/index.POST-save-and-back.test.ts
src/ui/server/controllers/insurance/business/company-details/save-and-back/index.ts
src/ui/server/controllers/insurance/business/contact/index.test.ts
src/ui/server/controllers/insurance/business/contact/index.ts
src/ui/server/controllers/insurance/business/contact/save-and-back/index.test.ts
src/ui/server/controllers/insurance/business/contact/save-and-back/index.ts
src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
src/ui/server/controllers/insurance/business/nature-of-business/index.ts
src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts
src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts
src/ui/server/controllers/insurance/business/turnover/index.test.ts
src/ui/server/controllers/insurance/business/turnover/index.ts
src/ui/server/controllers/insurance/business/turnover/save-and-back/index.test.ts
src/ui/server/controllers/insurance/business/turnover/save-and-back/index.ts
src/ui/server/helpers/construct-payload/index.test.ts
src/ui/server/helpers/construct-payload/index.ts
src/ui/server/test-mocks/mock-business-turnover.ts

* Added `constructPayload` helper to make payload from provided fieldIds
* Used constructPayload in your-business section to ensure only relevant fields are provided
* Added and updated unit tests

chore(EMS-1807-1808): Your Business - Construct payload

---

package-lock.json
src/ui/package-lock.json
src/ui/package.json

chore(deps): dependencies updates

---

src/ui/server/controllers/insurance/business/broker/index.ts
src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.test.ts
src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.ts

* Added constructPayload to your buyer section
* Added tests

chore(EMS-1809): Your buyer - construct payload

---

e2e-tests/content-strings/error-messages.js
e2e-tests/content-strings/pages/insurance/eligibility/index.js
package-lock.json
src/api/.keystone/config.js
src/api/package-lock.json
src/ui/server/content-strings/error-messages.ts
src/ui/server/content-strings/pages/insurance/eligibility/index.ts

* Changed insured amount page to read Do you want to be insured for more than £500,000?
* Changed error message to read Select whether you want to be insured for more than £500,000

feat(EMS-1796-1797): Insurance Eligibility - Insured amount

---

e2e-tests/content-strings/error-messages.js
src/ui/server/content-strings/error-messages.ts

* Companies house search error message was incorrect
* Updated error message and e2e test error message

fix(EMS-1946): Your business - Incorrect companies house error message

---

e2e-tests/content-strings/fields/insurance/your-buyer/index.js
e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/working-with-buyer.spec.js
e2e-tests/pages/insurance/your-buyer/workingWithBuyer.js
src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
src/ui/server/index.ts
src/ui/templates/insurance/your-buyer/working-with-buyer.njk

* Added hint for traded with buyer radio
* Added to e2e test

feat(EMS-1899): Your buyer - Working with buyer hint

---

e2e-tests/commands/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js
e2e-tests/commands/insurance/account/complete-sign-in-and-go-to-application.js
e2e-tests/commands/insurance/account/complete-sign-in-and-otp.js
e2e-tests/commands/shared-commands.js
e2e-tests/insurance/cypress/e2e/journeys/account/account-creation-and-sign-in-with-eligibility-answers.spec.js
e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-create-code-dashboard-or-application-redirect.spec.js
e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-with-second-requested-sign-in-code.spec.js
src/api/.keystone/config.js
src/ui/server/api/keystone/applications/index.ts
src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts

* Added redirect to application if only one application for the user
* Added e2e test
* Updated `completeSignInAndGoToApplication` for one application

feat(EMS-1945): Dashboard - Redirect to application or dashboard

---

e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts

This PR updates some copy for a field hint in the "About goods or services" form.

feat(EMS-1968): Policy and exports - About goods or services - copy update

---

.github/workflows/test.yml
e2e-tests/insurance/cypress.config.js
e2e-tests/quote/cypress.config.js
e2e-tests/switch-between-services/cypress.config.js

Ensure Cypress tests are executed on runners only.
* Introduced spec matrix.
* Execution via CLI
* Video recording set to false
* Screenshot upon failure set to false.

fix(cypress): GHA matrix test execution

---

.gitattributes

Ensure EOL files handling is in place
* Added `.gitattributes`

feat(git-attributes): added .gitattribute for EOL file handling

---

database/exip.sql

Update Serbia country code
* Updated to `SRB` from `SCG`.

fix(country-code): updated country code to SRB

---

src/api/Dockerfile
src/ui/Dockerfile

Downgrade Dockerfile base image due to Azure container boot issue.
* Downgraded Dockerfile base image to `20.0-alpine3.16`.

fix(docker): downgraded dockerimage

---

src/api/Dockerfile
src/ui/Dockerfile

Specify which ports docker container is listening on.
* Added `EXPOSE` instruction.

fix(docker-file): added EXPOSE command

---

.github/workflows/infrastructure.yml
docker-compose.yml
src/api/Dockerfile
src/ui/Dockerfile

Ensure exposed ports are readable by Azure Web App.
* Added `PORT` and `WEBSITES_PORT` to IaC.
* Renamed `*_PORT` to `PORT` in `Dockerfile`
* `Timezone` now being referred from GitHub environment variables.
* Added `NODE_ENV` to API container.

fix(ports):  Added `PORT` and `WEBSITES_PORT` to IaC

---

src/api/.keystone/config.js

The automatically generated keystone config has a misaligned piece of text.
- Regenerate keystone config.

fix(keystone): Regenerate keystone config

---

package-lock.json
src/api/Dockerfile
src/api/package-lock.json
src/api/package.json
src/ui/Dockerfile
src/ui/package-lock.json

Update base Dockerfile image
* Updated base Dockerfile image to `node:21.0.0-alpine3.17`
* Kept `UI` container to build image to `node:20.8.1-alpine3.17` due to incompatibility with `saas-loader` used during webpack build, however the production image is using `node:21.0.0`.
* Dependencies updates

fix(dockerfile): Update base Dockerfile image

---

e2e-tests/content-strings/tasks.js
e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
e2e-tests/partials/insurance/taskList.js
src/api/.keystone/config.js
src/ui/server/constants/task-ids.ts
src/ui/server/content-strings/tasks.ts
src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
src/ui/server/helpers/task-list/index.test.ts
src/ui/server/helpers/task-list/index.ts
src/ui/templates/components/task-list.njk
src/ui/types/task-list.ts

This PR updates the task list to have the same wording and ordering as the "No PDF" design.
- Update `createPrepareApplicationTasks` function.
- Update task generation to support hints.
- Update copy.
- Update E2E test coverage.
- Improve task list styling/spacing.

feat(EMS-2066): No PDF - Update task list

---

e2e-tests/content-strings/pages/insurance/eligibility/index.js
e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-if-eligible.spec.js
e2e-tests/pages/insurance/eligibility/checkIfEligible.js
src/ui/server/content-strings/pages/insurance/eligibility/index.ts
src/ui/templates/insurance/eligibility/check-if-eligible.njk

The next phase of EXIP (no PDF) requires some content updates to the "check if eligible" page.
- Update "check if eligible" page content strings, template and E2E test.

feat(EMS-2082-2087): No PDF - 'Check if eligible' page updates

---

.github/workflows/deployment.yml

Resolve target environment
* Updated to `github.ref_name`

fix(gha): target environment reference resolved

---

.github/workflows/deployment.yml

Correct environment variables
* Refactored CLI command

fix(gha): deployment script

---

src/api/package.json
src/ui/package-lock.json
src/ui/package.json

Build fix
* Build fix when `NODE_ENV` set to `production`.

fix(build): build fix

---

e2e-tests/content-strings/pages/index.js
src/ui/server/content-strings/pages/index.ts

The recently updated accessibility statement has some incorrect words and a missing space.
- Update accessibility statement content.

fix(EMS-2197): Accessibility statement copy

---

e2e-tests/insurance/cypress/fixtures/example.json
package-lock.json
src/ui/package-lock.json

`main` has had `main-application` merged, ready for go live.
We need to update `main-application-no-pdf` so that it is up to date.
* Merged `main` into the `main-application-no-pdf` branch.

chore(merge) `main` into `main-application-no-pdf`

---

.cspell.json
.github/workflows/deployment.yml
.github/workflows/infrastructure.yml

Add database to IaC
* Added `MySQL` database
* Added `UKS` VPN VNET peering

feat(iac): database iac addition

---

.cspell.json
.github/workflows/README.md
.github/workflows/deployment.yml
.github/workflows/infrastructure.yml

Ensure database is only deployment when enabled.
* GHA syntax update.
* IaC URL construction.
* Documentation update
* CSpell removed spelling mistake.

fix(deployment): deployment script

---

.cspell.json
.github/workflows/deploy.sh

After various major merges/changes with the `main`/`main-application` and `main-application-no-pdf` branches, the `main-application-no-pdf` has some missing changes in the deployment script and cspell config.
- Update `deploy.sh`.
- Update CSpell config.

fix(merge): cspell and deploy script issues

---

package-lock.json
package.json
src/api/.keystone/config.js
src/api/test-mocks/mock-CIS-countries.ts

- Dependabot flagged a package update.
- Update `commitlint` package version.
- Tidy up

chore(release): Update commitlint version, API test mocks

---

package-lock.json
package.json
src/api/package-lock.json
src/api/package.json
src/ui/package-lock.json
src/ui/package.json

- Dependabot flagged some dependency updates.
- Update dependencies.

chore(deps): bump dependencies

---

e2e-tests/commands/insurance/complete-and-submit-company-details.js
e2e-tests/commands/insurance/complete-company-details-form.js
e2e-tests/content-strings/error-messages.js
e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-different-trading-name-validation.spec.js
e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
src/api/.keystone/config.js
src/api/schema.prisma
src/ui/server/content-strings/error-messages.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.test.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts

This PRs fixes various bugs in nature of your business
- Fixed incorrect error messages for years exporting and tell us about your business
- Added missing validation if employees is below minimum
- Added to tests
- Fixed incorrect camel case for `completeDifferentTradingName`

fix(EMS-2297-2298-2299): No PDF - Nature of your business - Bug fixes

---

e2e-tests/content-strings/error-messages.js
src/ui/server/content-strings/error-messages.ts

This PRs fixes the content in error messages for "Nature of your business" page
- Fixed error messages copy for nature of your business page
- Updated error messages for tests

fix(EMS-2309): No PDF - Nature of your business - Error messages

---

.github/pull_request_template.md

This PR adds a PR template, to save us from manually typing out introduction, resolution and miscellaneous sections.
- Add a `pull_request_template.md` to `.github` directory.

chore(prs): Create pull request template

---

.github/PULL_REQUEST_TEMPLATE.md

This PR changes the emojis used in the PR template which currently do not work.
- Update the PR template.

fix(prs): Pull request template emojis

---

README.md

This PR updates the "no pdf" branch to have the latest code from `main`.
- Merge `main` into `main-application-no-pdf`

chore(merge): Merge `main` into `main-application-no-pdf`

---

.github/PULL_REQUEST_TEMPLATE.md

This PR simplifies the PR template to be aligned with the new standard.
- Remove placeholder list items from the PR template.

chore(prTemplate): Simplify pull request template

---

.github/workflows/deployment.yml

Deployment script consistency
* Added `database` import.
* Removed frivolous deployment variables from `API` environment variable set

fix(deployment): removed frivolous deployment environment variables set

---

.github/workflows/deployment.yml
.github/workflows/infrastructure.yml

Deployment script consistency
* Updated Azure CLI plugin to `1.0.9`
* Removed `API_KEY`, `TLS_CERTIFICATE` and `TLS_KEY` environment variable.
* Updated documentation.

fix(deployment): removed frivolous variables

---

e2e-tests/content-strings/error-messages.js
src/ui/server/content-strings/error-messages.ts

This PR updates some error messages that have "..., like ..." formatting to instead be "... - for example ..."

style(EMS-2658): No PDF - Update error messages

---

e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.test.ts
src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.ts

This PR adds a redirect on "Prior trading history" form POST, if yes is submitted.
- Added redirect to trading-history page
- Added tests

feat(EMS-2412): No PDF - Your buyer - Trading history redirect

---

database/exip.sql
src/api/.keystone/config.js
src/api/schema.prisma
src/api/schema.ts

This PR sets registrationNumber to varChar(100) for registrationNumber
* Updated schema.ts
* Updated sql dump

chore(EMS-2927): Your Buyer - Update DB for registrationNumber

---

e2e-tests/commands/insurance/check-policy-summary-list.js
e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-value.js
e2e-tests/commands/shared-commands/assertions/check-summary-list-field-change.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-change-broker.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-multiple-policy-type.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-single-policy-type.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-pre-credit-period-yes-to-no.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/check-your-answers-policy-multiple-same-name-summary-list.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/check-your-answers-policy-single-different-name-summary-list.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/check-your-answers-policy-single-same-name-summary-list.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-broker.spec.js
e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-different-name-on-policy.spec.js
e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-same-name-on-policy.spec.js
src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee/index.ts
src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.test.ts
src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.ts

This PR adds contact email row if same name on policy without a change link
* Added logic to summary list helper
* Updated e2e tests

feat(EMS-2830): No PDF - Policy - Check your answers - Contact Email

---

e2e-tests/content-strings/pages/insurance/export-contract/index.js
src/ui/package-lock.json
src/ui/package.json
src/ui/server/content-strings/pages/insurance/export-contract/index.ts

This PR updates the start page content for the "Export contract" section of a no PDF application.
- Bump `sass-loader`.

style(EMS-3170): No PDF - Export contract - Start page - Content update

---

e2e-tests/content-strings/pages/insurance/application-submitted/index.js
e2e-tests/insurance/cypress/e2e/journeys/application-submission/application-submitted.spec.js
e2e-tests/pages/insurance/applicationSubmitted.js
src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
src/ui/templates/insurance/application-submitted.njk

This PR updates the "Application submitted" page to have the most recent iterated content.
- Update page gcontent strings.
- Update E2E test.
- Update nunjucks template.

style(EMS-3257): No PDF - Application submitted - Content updates

---

.github/workflows/deployment.yml
.github/workflows/infrastructure.yml
.github/workflows/publish.yml
package-lock.json
package.json

Ensure release please publish appropriate Git tags and deployment does not fail due to dependency nonexistence.
* Reverted publish.yml to release-please GitHub Actions.
* Added missing dependency `@actions/core` required for deployment.
* Updated `azure/login` to `v2`

fix(release-please): updated to GitHub plugin

---

e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts
src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/years-exporting.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.test.ts
src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.test.ts
src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.ts
src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/account-number.test.ts
src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/account-number.ts
src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/sort-code.ts
src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.test.ts
src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.ts
src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.test.ts
src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.ts
src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.test.ts
src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.ts
src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.test.ts
src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.ts
src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.test.ts
src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.ts
src/ui/server/helpers/number-validation/index.test.ts
src/ui/server/helpers/number-validation/index.ts
src/ui/server/shared-validation/number-above-minimum/index.test.ts
src/ui/server/shared-validation/number-above-minimum/index.ts
src/ui/server/shared-validation/number-minimum-maximum-length/index.test.ts
src/ui/server/shared-validation/number-minimum-maximum-length/index.ts
src/ui/types/index.d.ts
src/ui/types/validation-errors.d.ts

This PR fixes an issue where fixed sum input did not accept decimal places
* Added allowDecimalPlaces to number validation files
* Changed to object structure
* Added interface for variables for numberVariables
* Removed wholeNumber from number validation to just number

fix(EMS-3234): no PDF - Validation - Number validation decimal places

---

.github/workflows/deployment.yml

This PR fixes an issue with the deployment.yml file
* Removed repeated line

fix(deployment-yml): deployment.yaml fix

---

.github/workflows/deployment.yml

This PR fixes an issue with the deployment.yml file
* Removed repeated lines

fix(deployment-yml): deployment.yml fix

---

.github/workflows/test.yml
e2e-tests/constants/routes/insurance/index.js
e2e-tests/content-strings/pages/insurance/eligibility/index.js
e2e-tests/insurance/cypress/e2e/journeys/eligibility/contract-too-short/contract-too-short.spec.js
e2e-tests/pages/insurance/eligibility/contractTooShort.js
e2e-tests/pages/insurance/eligibility/index.js
src/ui/server/constants/routes/insurance/index.ts
src/ui/server/constants/templates/insurance/eligibility/index.ts
src/ui/server/content-strings/pages/insurance/eligibility/index.ts
src/ui/server/controllers/insurance/eligibility/contract-too-short/index.test.ts
src/ui/server/controllers/insurance/eligibility/contract-too-short/index.ts
src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
src/ui/server/routes/insurance/eligibility/index.test.ts
src/ui/server/routes/insurance/eligibility/index.ts
src/ui/server/routes/insurance/index.test.ts
src/ui/templates/insurance/eligibility/contract-too-short.njk

This PR adds the "contract too short" exit page in eligibility
* Added template and content string and routes
* Added GET controller
* Added E2E test for page

feat(EMS-2433): no PDF - Eligibility - Contract too short exit page

---

src/api/.keystone/config.js
src/api/helpers/send-email-application-submission-deadline/send-email/index.test.ts
src/api/helpers/send-email-application-submission-deadline/send-email/index.ts

This PR fixes an issue with the submission deadline email where the number of emails sent could not be compared leading to an error
* added await and constant to Promise.all
* returned constant

fix(EMS-1269): no PDF - CRON - Submission deadline email

---

docker-compose.yml

All tests were failing - msql update
* Downgrade sql to 8.4.0

chore(mysql-issue): downgraded mysql version

---

docker-compose.yml

This PR downgrades mysql to latest azure supported version
* Downgrade mysql to 8.0.36

chore(mysql-downgrade): no PDF - MySQL version downgrade

---

e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-with-comma.spec.js
src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts

This PR fixes an issue where fixed sum went to problem with service when submitting a number with commas
* Added strip commas to mapping
* Added tests

fix(EMS-3546): no PDF - Export contract - Agent charges - Fixed sum commas

---

.github/workflows/lint.yml
.github/workflows/sca.yml
package-lock.json
package.json

Ensure `*.yml` files syntax are validated during the pipeline.
* Added `validate:yml`
* Updated `lint-staged` scripts
* Consistent script service name across UKEF repositories.
* Added `prettier:all` script to be added to pipeline as a separate PR

feat(validate-yml): added YAML validation

---

.github/workflows/deploy.sh

This PR changes `feature` deployment branch to `main-iterations`
* change deployment.sh branch to `main-iterations`

chore(deployment-script): deployment - Change feature branch

---

.cspell.json
.github/workflows/deployment.yml
.github/workflows/infrastructure.yml

Add KeyVault to IaC
* Create Azure Key Vault with private a dedicated subnet and private endpoint
* Spell check exception added.
* Fixed conditional database deployment step.

feat(EMS-2186): added key vault

---

.github/workflows/infrastructure.yml
.github/workflows/test.yml

Multiple environment variables were missing during infrastructure deployment.
* YML syntax fixes
* Added respective values to `qa` and `infrastructure` environment.
* JMSEPath syntax fix
* Added Key vault to diagnostics.

feat(EMS-3606): added missing environment variables

---

e2e-tests/content-strings/pages/insurance/export-contract/index.js
src/ui/server/content-strings/pages/insurance/export-contract/index.ts

This PR makes a legal content change for the export contract agent page
* Updated content string and e2e test content string

feat(EMS-3610): no PDF - Export contract - Agent - Content change

---

src/ui/package-lock.json
src/ui/package.json
src/ui/styles/styles.scss

This PR bumps sass-loader
* added correct path to node_modules in styles.scss
* Updated deps

chore(deps): bump sass-loader

---

.github/workflows/test.yml

This PR removes coverage from e2e tests
* Removes coverage from e2e tests

chore(e2e-coverage): iterations - e2e - removed coverage

---

e2e-tests/commands/insurance/declarations/complete-and-submit-declarations-forms.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/save-and-back.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
e2e-tests/insurance/cypress/support/declarations/index.js

This PR introduces a command to complete declarations forms up to a certain form
* Added command to complete declarations forms up to a certain form
* Updated e2e tests to use this command

chore(EMS-3766): e2e - declarations - complete and submit forms command

---

.cspell.json
src/api/.keystone/config.js
src/api/constants/external-apis.ts

- 2x objects returned in the CIS (Country Information System) API response are not countries. These need to be filtered out.
- The API is used by other teams so unfortunately we cannot remove these from the root of the problem.
- Update `INVALID_COUNTRIES` constants.

chore(EMS-3886): update filtering of invalid cis countries

---

.github/workflows/deploy.sh
.github/workflows/deployment.yml
.github/workflows/infrastructure.yml

- The `feature` environment has been deleted.
- We have some feature related flags in the deployment scripts/YMLs.
- Remove instances of `feature`.

chore(deploy): remove feature environment flags

---

src/api/.keystone/config.js

- The build is failing.
- Regenerate API schema.

fix(EMS-3988): regenerate api schema

---

e2e-tests/content-strings/fields/insurance/policy/index.js
e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
e2e-tests/pages/insurance/policy/typeOfPolicy.js
e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
src/api/.keystone/config.js
src/api/content-strings/fields/insurance/policy/index.ts
src/ui/server/content-strings/fields/insurance/policy/index.ts

This PR fixes an issue where in the Application's "type of policy", a part of the hint text would display as "[Object Object]".
- Improve E2E test coverage.
- Update page selectors to use the same approach as other "hint list" selectors (`hintListItem(index)` instead of `.hintList.item1()`, `.hintList.item2()` etc).
- Fix a typo.

fix(EMS-3988): apply - type of policy - hint text

---

e2e-tests/commands/api/index.js
e2e-tests/commands/insurance/account/delete-account.js
e2e-tests/commands/insurance/create-an-abandoned-application.js
e2e-tests/commands/insurance/create-an-application.js
e2e-tests/commands/insurance/create-applications.js
src/api/.keystone/config.js
src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts
src/ui/server/controllers/insurance/business/turnover-currency/save-and-back/index.ts

Some error logs were missing `%o`.
- Add missing `%o` to error logs.

chore(EMS-3970): add missing %o to console error logs

---

.github/dependabot.yml
.github/workflows/deploy.sh

This PR changes dependabot interval and attempts to group PRs
* Added groups so less PRs
* temporarily change to daily

chore(EMS-4031): test dependabot changes

---

.github/dependabot.yml

This PR adds more ignores to dependabot.yml
* Added more ignores to dependabot.yml
* Changed running time

chore(EMS-4031): add ignores to dependabot.yml

---

.github/dependabot.yml

This PR reverts the changes made for testing to dependabot.yml running
* Changed interval to monthly 
* Changed time to 3am

chore(EMS-4031): reverts timing changes to dependabot.yml

---

.github/dependabot.yml

This PR changes the dependabot npm schedule to monthly
* Change dependabot npm schedule to monthly

chore(EMS-4031): change dependabot npm schedule to monthly

---

e2e-tests/content-strings/fields/insurance/declarations/index.js
e2e-tests/content-strings/links.js
e2e-tests/content-strings/pages/insurance/declarations/modern-slavery/index.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-expandable-definition-content.spec.js
e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
src/api/.keystone/config.js
src/api/content-strings/fields/insurance/declarations/index.ts
src/api/content-strings/links.ts
src/ui/server/content-strings/fields/insurance/declarations/index.ts
src/ui/server/content-strings/links.ts
src/ui/server/content-strings/pages/insurance/declarations/modern-slavery/index.ts

This PR updates the "Modern slavery" declaration so that all links link to external pages.
- Update `LINKS` content strings.
- Update page content strings.

style(EMS-4040-44-47): declarations - modern slavery - content iterations

---

e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-eligible-for-small-export-builder-alternative-currency.spec.js
e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-not-eligible-for-small-export-builder-alternative-currency.spec.js
e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js
src/api/.keystone/config.js
src/api/emails/application/get-submitted-confirmation-template-id/index.test.ts
src/api/emails/application/get-submitted-confirmation-template-id/index.ts
src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.test.ts
src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.ts
src/api/emails/application/index.test.ts
src/api/emails/application/index.ts
src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk

- The business is not ready to deploy the "Small export builder" functionality to production.
- We are almost ready to push other functionalities to production.
- Therefore, "Small export builder" functionality needs to be temporarily disabled.
- Disable "Small export bulder" functionality.

chore(EMS-4121): disable small export builder functionality

---

src/api/.keystone/config.js

API container boot failure due to outdated keystone config.
* Executed `npm run dev` on `api` container.

fix(EMS-4125): update keystone config

---

e2e-tests/content-strings/fields/insurance/declarations/index.js
e2e-tests/content-strings/pages/insurance/declarations/anti-bribery/index.js
e2e-tests/content-strings/pages/insurance/declarations/modern-slavery/index.js
src/api/.keystone/config.js
src/api/content-strings/fields/insurance/declarations/index.ts
src/ui/server/content-strings/fields/insurance/declarations/index.ts
src/ui/server/content-strings/pages/insurance/declarations/anti-bribery/index.ts
src/ui/server/content-strings/pages/insurance/declarations/modern-slavery/index.ts

- "Declarations - Modern slavery" content has been updated.
- All instances of "Definition of terms in this declaration" should be simply "Definition of terms".

style(EMS-4136): declarations - content iterations

---

src/api/.keystone/config.js

Keyston configuration was outof sync.
* Executed `npm run dev` on `api`.

chore(keystone): updated keystone configuration

---

e2e-tests/content-strings/error-messages.js
src/ui/server/content-strings/error-messages.ts

- The error messages for "Declarations - Modern slavery" have been updated.

style(EMS-4157): declarations - modern slavery - content iterations

---

src/api/.keystone/config.js

Updated Keystone configuration file.

fix(keystone): updated keystone configuration

---

e2e-tests/content-strings/pages/insurance/policy/index.js
e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-ordnance-survey-invalid-postcode.spec.js
e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-page.spec.js
e2e-tests/pages/insurance/policy/brokerZeroAddresses.js
src/api/.keystone/config.js
src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.test.ts
src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.ts
src/api/integrations/ordnance-survey/index.test.ts
src/api/integrations/ordnance-survey/index.ts
src/api/types/ordnance-survey/index.ts
src/ui/server/content-strings/pages/insurance/policy/index.ts
src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.test.ts
src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.ts
src/ui/templates/insurance/policy/broker-zero-addresses.njk

This PR fixes an issue where certain postcodes (eg A9A 9AA) would redirect to problem-with-service and the building number missing on no-addresses-found page
* Added 400 to accepted ordnance survey statuses
* added status to  OrdnanceSurveyAPIResponse
* Added if to getOrdnanceSurveyAddresses query to return noAddressesFound if ordnance survey returns 400
* Added tests
* Added e2e test
* Updated copy on no-addresses-found page to include building name/number

fix(EMS-4206-4207): fix incorrect problem-with-service when no addresses found

---

src/ui/server/helpers/date/iso-8601/index.test.ts

This PR fixes a failing getISO8601 test
* Fixed getISO8601 test by adding padStart

fix(EMS-4214): fix failing getISO8601 test

---

.github/dependabot.yml

Reverts UK-Export-Finance/exip#3533

Revert "chore(EMS-4217): dependabot - limit typescript to 5.4 only in ui directory"

---

.markdownlint.json
src/api/.keystone/config.js

Update markdown configuration file.
* Updated `.markdownlint.json` file for consistency.
* Keystone configuration update.

chore(github-actions): updated markdown lint configuration
